### ISSUE TITLE
An ability to order execution within a suite using context

### ISSUE THREAD

**Issue by petermanger** [utPLSQL/utPLSQL#1006]
**Is your feature request related to a problem? Please describe.**
There are a particularly complex series of steps setting up the databases used for each test, and on the journey to that state it is useful to run tests and use that state to pipe into the next series of tests.  Currently this is managed by writing one massive test - which is somewhat of a hack and basically promotes expectations to "test" and "context" level.

Whilst this is not technically speaking Unit Testing - this small addition will greatly improve the flexibility of utPLSQL with little impact to purists (in house we argued over this at length).

**Describe the solution you'd like**
An ability to provide order of execution to contexts.

An alternative solution is to allow tests to have order, but I feel this is not in the spirit of unit testing, too granular, and complicates contexts - therefore the context level within a suite is perfect.

**Describe alternatives you've considered**
Various forms of self managing the tests - which nearly always "fight against" the otherwise excellent features of utPLSQL.  The single test with many ut.expects works best.  We use ut.expect to basically manage context and tests, using the always true case to write messages.

**Additional context**
The database has a lot of dynamic table creation and cross database chatter.  The ability to order sets of tests allows for more controlled management and stable testing world in a pragmatic non intrusive manner.

Or - is there a feature I've just totally missed that does this?!
Possible relationship to Issue 938.

**Comment by jgebal** [comment]
Hi @petermanger 

Did you investigate using `--%beforeall`, `--%beforeeach`, `--afterall`, nested suites / contexts to achieve the shared setup?

**Comment by petermanger** [comment]
Hi - thanks for replying :-)

The nested suites feature is not something I think we've properly explored, and will experiment with that. 

Pete

**Comment by jgebal** [comment]
Closing this issue 
@petermanger - please feel free to come back with any feedback or further questions
