### ISSUE TITLE
Add "except tags" or "skip tags"

### ISSUE THREAD

**Issue by alexeyhimself** [utPLSQL/utPLSQL#1007]
**A problem**
When you have tests for example "not for production environment", then how not to run them on production environment using annotation tags? There is no way, because there are "tags", but there are no "except tags":
```
--%tags(not_for_production)
select * from table(ut.run(a_tags => ?));
```

**Suggested solution**
Introduce "a_skip_tags":
```
--%tags(not_for_production)
select * from table(ut.run(a_skip_tags => 'not_for_production'));
```
**Workaround**
Now I can only to put such "non-production" tests in a separate folder or in a separate branch.

**Comment by jgebal** [comment]
This seems like duplicate of #983

**Comment by alexeyhimself** [comment]
@jgebal, true. It's a duplicate, but with a different suggested solution.
