### ISSUE TITLE
Annotation that goes to test report is not stopped by closing parenthesis

### ISSUE THREAD

**Issue by alexeyhimself** [utPLSQL/utPLSQL#1010]
**Describe the bug**
When you write comment after annotation, then this comment becomes the part of test report as well.

**Provide version info**
v3.1.8.3190

**Information about client software**
PLSQL Developer

**To Reproduce**
1. Compile procedures with comments:
```
create or replace package test_demo is
 
  -- %suite (Demo suite)                 this suite name will be used in test report (see below)

  -- %test (Demo test case success)      -- this test case name will be used in test report (see below)
  procedure demo_test_pass;
 
  -- %test (Demo test case failure)      -- this test case name will be used in test report (see below)
  procedure demo_test_failure;
 
end;
/
 
create or replace package body test_demo is
 
  procedure demo_test_pass is
  begin
    ut.expect(1).to_equal(1);
  end;
 
  procedure demo_test_failure is
  begin
    ut.expect(2).to_equal(1);
  end;
 
end;
/
```
2. Run utPLSQL:
```
select * from table(ut.run());
/
```

**Actual behavior**
Comments after closing parenthesis became a part of test report:
```
Demo suite)                 this suite name will be used in test report (see below
  Demo test case success)      -- this test case name will be used in test report (see below [.128 sec]
  Demo test case failure)      -- this test case name will be used in test report (see below [.018 sec] (FAILED - 1)
	 
Failures: 
  1) demo_test_failure
```

**Expected behavior**
Closed annotation parenthesis stops annotation:
```
Demo suite
  Demo test case success [.128 sec]
  Demo test case failure [.018 sec] (FAILED - 1)
	 
Failures: 
  1) demo_test_failure
```

**Additional context**
I didn't expect that comment will become the part of test report

**Comment by jgebal** [comment]
Comments inside annotations are not supported.
If you need to add comment, add it in line before annotation.
Whole line of annotation is considered annotation.

**Comment by jgebal** [comment]
Updated documentation will be part of release 3.1.9.
https://github.com/utPLSQL/utPLSQL/blob/release/v3.1.9/docs/userguide/annotations.md

Hope this helps.
