### ISSUE TITLE
Add explicit "PASSED" status to each test case and overall statistics in test report

### ISSUE THREAD

**Issue by alexeyhimself** [utPLSQL/utPLSQL#1011]
**Is your feature request related to a problem? Please describe.**
2 problems:
1. I can't parse test report to filter out "PASSED" test cases because there is no execution status for them. This is specially important when using utPLSQL-cli in CI auto tests and trying to generate report that I want.
2. I can't define number of PASSED test cases from statistics without additional calculation.

**Describe the solution you'd like**
When test report is formed, now it looks this way:
```
Demo suite
  Demo test case success [.002 sec]
  Demo test case failure [.003 sec] (FAILED - 1)
 
Failures:
 
  1) demo_test_failure
      Actual: 2 (number) was expected to equal: 1 (number)
      at "STAT.TEST_DEMO", line 10 ut.expect(2).to_equal(1);
       
Finished in .008476 seconds
2 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```
I'd wanted to mark explicitly status for each test case (even passed ones):
```
Demo suite
  Demo test case success [.002 sec] (PASSED)
  Demo test case failure [.003 sec] (FAILED - 1)
 
Failures:
 
  1) demo_test_failure
      Actual: 2 (number) was expected to equal: 1 (number)
      at "STAT.TEST_DEMO", line 10 ut.expect(2).to_equal(1);
       
Finished in .008476 seconds
2 tests total, 1 passed, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```
i.e.:
```
  Demo test case success [.002 sec] (PASSED)
```
and:
```
2 tests total, 1 passed, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```

**Describe alternatives you've considered**
1. If I need some post-processing related to PASSED test cases of the report, then I need to make additional calculations to get that info from report. I.e. to get passed test cases I need to filter out strings that consist "(FAILED -" pattern till "Failures:" pattern. Why I can't just grep test report by "(PASSED)"?
2. When I look at test report stats:
```
2 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```
and think about number of passed test cases, then I need to do some math: {tests} - {failed} - {errored} - {disabled} - {warnings} = {passed}. Why so? Why I can't just to see the number in report already?
```
2 tests total, 1 passed, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```

**Comment by pesse** [comment]
Did you try one of the other reporters?
`ut_documentation_reporter` is for human readability, you might be much better off with automatic parsing when using e.g. `ut_junit_reporter`

**Comment by alexeyhimself** [comment]
Yes, I tried them and now using ut_junit_reporter but I could make my own better report if I had these "PASSED" explicitly defined.

**Comment by jgebal** [comment]
Do not parse documentation reporter output on CI.
Use JUnit test reporter and integration is almost out of the box

**Comment by alexeyhimself** [comment]
@jgebal, I'll explain the use case a bit more, adding more context.

We use GitLab runner to run our tests and publish reports. And we use utPLSQL-cli to run tests. When utPLSQL finishes execution it makes a report either in human-readable format ```ut_documentation_reporter``` or in machine-readable format ```ut_junit_reporter```. I'd wanted to get BOTH human-readable and machine-readable formats of report at once - so I could read output in console if I need to and allow GitLab to manage the report on it's own. Is this possible to get several reports at once? Because I've read in a doc, that it's not possible.

I want console output human-readable report because when I commit to CI branch (commit, not merge) then GitLab does not show the report at all. Even if my commit fails CI run. And that's why I don't know the reason of failure. GitLab shows reports only for merges to CI branch. Maybe this is "incorrect development flow" (committing to CI rather than merging to CI) but anyway, we face it.

Now I use ```ut_junit_reporter``` and give it to GitLab. But before giving it to GitLab I parse XML to JSON and then output report to console the way I want to see it, adding explicit "PASSED" states, adding calculation of passed tests:
```
Demo suite
  Demo test case success [.002 sec] (PASSED)
  Demo test case failure [.003 sec] (FAILED)
    Actual: 2 (number) was expected to equal: 1 (number)
    at "STAT.TEST_DEMO", line 10 ut.expect(2).to_equal(1);
        
Finished in .008476 seconds
2 tests total, 1 passed, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```

**Comment by jgebal** [comment]
You can run with as many reports as you want.
We do it ourselves when we test utPLSQL framework on Travis with our build.
[This](https://github.com/utPLSQL/utPLSQL/blob/develop/test/run_tests.sh) is the script that runs our tests.

Once executed, we publish test results and coverage to sonar with sonar-scanner configured [here](https://github.com/utPLSQL/utPLSQL/blob/develop/sonar-project.properties)

With sonar/JUnit, you can have test results/coverage mapped to project-files rather than object-names.

See [utPLSQL-cli readme](https://github.com/utPLSQL/utPLSQL-cli#usage) for cli options and detailed documentation on project based coverage [here](https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/coverage.md#project-based-coverage)

@pesse - looking at cli readme it's not really obvious that you can run with multiple reporters.

**Comment by jgebal** [comment]
@alexeyhimself - I recommend using latest CLI version (3.1.8) - it has several improvements.
You can execute `utplsql run` to see full syntax and help
![image](https://user-images.githubusercontent.com/1398171/67441515-07503380-f5f5-11e9-914a-9485bff76672.png)

**Comment by jgebal** [comment]
Also, with `ut_documentation_reporter` you get real-time report on the screen, as test execution progresses. This s better than waiting for test-run to complete to see results (JUnit-XML).
I'm not sure if GitLab gives real-time build console, but Travis does, and it's a great feature.

**Comment by pesse** [comment]
@jgebal Yes, cli readme needs an update, thanks for pointing this out

**Comment by jgebal** [comment]
@alexeyhimself - if those answers are sufficient, please close the issue.
If not sufficient, please provide some feedback.

Otherwise the issue will be considered closed.
