### ISSUE TITLE
Contexts not rollbacking when description has spaces

### ISSUE THREAD

**Issue by Zvalgas** [utPLSQL/utPLSQL#1023]
**Describe the bug**
When using several contexts --%context(Test case 1 long but informative desription) - not working rollback after each context (each context has --%beforeall procedure that setup data for that particular context)

When changed description naming to --%context(Test_case_1) - all works but naming looks ugly for me; So I have to use after each context --%displayname(Test case 1 long but informative desription), but in documentation I see that you want to remove --%displayname annotation

**Provide version info**
utPLSQL v3.1.3.2402

**Information about client software**
PLSQL Developer

**Comment by pesse** [comment]
In utPLSQL 3.1.3, the part in the context-parenthesis are the context's name, not the description.
This is changed in [version 3.1.9](https://github.com/utPLSQL/utPLSQL/releases/tag/v3.1.9).
To fix your problem, you can do either of these two things:
- use `--%context(context_1)` together with `--displayname(Description 1)`
- update to the current release-version 3.1.9

**Comment by jgebal** [comment]
@Zvalgas 
Thanks for reaching out with the question.

When working with particular version please try to reference the documentation related to that exact version. For 3.1.3 you can see it on [github](https://github.com/utPLSQL/utPLSQL/blob/v3.1.3/docs/index.md) or on our [official site](http://utplsql.org/utPLSQL/v3.1.3/).
The documentation on github (develop branch) is always referring to the currently-developed version (not yet released).

We do our best to improve user (developer) experience with utPLSQL and so some of the functionality is doing through slight changes between versions.

Don't worry too much about the depreciation. It will take some time before the depreciated functionality will be removed and that will happen with a bump of version number from `3.1.z` to `3.y.z`.

We don't have a long-term roadmap/plan on feature removal/decommission at the moment.

Also, as mentioned by @pesse - I also encourage you to update to lates version.

For new features see [release notes](https://github.com/utPLSQL/utPLSQL/releases)
