### ISSUE TITLE
Insufficient Privileges error while running ut.run() in v3.1.9.3270

### ISSUE THREAD

**Issue by pradeep-moganti** [utPLSQL/utPLSQL#1024]
I just started using utPLSQL v3.1.9. I am getting help from http://utplsql.org/utPLSQL/latest/ for installation and usage.
I installed utPLSQL in a schema called UT3. When I try to invoke ut.run() from UT3 schema I am facing few errors. 
Following is the log.

SQL> SELECT banner FROM v$version;
BANNER
--------------------------------------------------------------------------------
Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
PL/SQL Release 12.2.0.1.0 - Production
CORE    12.2.0.1.0      Production
TNS for 64-bit Windows: Version 12.2.0.1.0 - Production
NLSRTL Version 12.2.0.1.0 - Production

SQL> show user;
USER is "UT3"

SQL> select grantee, privilege from sys.dba_sys_privs WHERE grantee  = 'UT3';
GRANTEE    PRIVILEGE
---------- ------------------------------
UT3        CREATE TABLE
UT3        CREATE VIEW
UT3        CREATE PUBLIC SYNONYM
UT3        CREATE SESSION
UT3        CREATE PROCEDURE
UT3        CREATE SEQUENCE
UT3        DROP PUBLIC SYNONYM

7 rows selected.

SQL> select
  2    xmlserialize( content xmltype(ut_run_info()) as clob indent size = 2 ) utp_version
  3    from dual;

UTP_VERSION
--------------------------------------------------------------------------------
<UT_RUN_INFO>
  <SELF_TYPE>UT_RUN_INFO</SELF_TYPE>
  <UT_VERSION>v3.1.9.3270</UT

SQL> begin ut.run(); end;
  2  /
begin ut.run(); end;
*
ERROR at line 1:
ORA-01031: insufficient privileges
ORA-06512: at "UT3.UT_RUNNER", line 180
ORA-06512: at "UT3.UT_TRIGGER_CHECK", line 26
ORA-06512: at "UT3.UT_ANNOTATION_MANAGER", line 301
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 430
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 504
ORA-06512: at "UT3.UT_RUNNER", line 150
ORA-06512: at "UT3.UT", line 134
ORA-06512: at "UT3.UT", line 488
ORA-06512: at "UT3.UT", line 558
ORA-06512: at line 1

Can you please help me if there is something wrong with my installation or understanding?

**Comment by jgebal** [comment]
You're probably missing a create synonym privilege in UT3 schema.

**Comment by pradeep-moganti** [comment]
Let me check that.
In the meantime, is there any document which talks about verifications to be done before using utPLSQL?

**Comment by jgebal** [comment]
How did you install utPLSQL?

If you follow instructions provided in install guide - you should be all set.

I recommend using headless installation.

**Comment by pradeep-moganti** [comment]
After granting following permissions to UT3 schema, we can run test cases without any errors.

CREATE SESSION
CREATE PROCEDURE
CREATE TYPE
CREATE TABLE
CREATE SEQUENCE
CREATE VIEW
CREATE SYNONYM
ALTER SESSION
CREATE TRIGGER

Thanks @jgebal for your quick help.
