### ISSUE TITLE
Junit reporter output not generating an HTML report

### ISSUE THREAD

**Issue by guruo5** [utPLSQL/utPLSQL#1031]
I am using UT_JUNIT_REPORTER for my reports and out put o- path/report.html. The html report is not displayed. Looks like system-out and system-err tags are not handled correctly. The xml report also appends  previous error as well.

**Comment by jgebal** [comment]
Can you provide more information like:
- exact command that you used
- utplsql version installed
- any additional information that could help us help you

With so little amout of information provided I cant even figure you what the problem is exactly.

**Comment by guruo5** [comment]
1. utplsql run User/pswd@testdb.test.com:port/testdb -f=ut_junit_reporter() -o=C:\Users\...\report.html
2. Utplsql - 3.1.8 Utplsql -cli 3.1.8
3. The tests are getting executed and I do get a HTML report, when I try to open the report it's blank. When I look at the xml of the report I can see the details

<?xml version="1.0" encoding="WINDOWS-1252"?>
<testsuites tests="4" disabled="0" errors="1" failures="0" name="" time=".393069" >
<testsuite tests="2" id="1" package="test_betwnstr"  disabled="0" errors="0" failures="0" name="Between string function" time=".182201" >
<testcase classname="test_betwnstr" assertions="1" name="Returns substring from start position to end position" time=".175062" >
<system-out/>
<system-err/>
</testcase>
<testcase classname="test_betwnstr" assertions="1" name="Returns substring when start position is zero" time=".001252" >
<system-out/>
<system-err/>
</testcase>
<system-out/>
<system-err/>
</testsuite>
<testsuite tests="1" id="2" package="test_ut_bl_user_registration"  disabled="0" errors="0" failures="0" name="Password Strength string function" time=".12282" >
<testcase classname="test_ut_bl_user_registration" assertions="8" name="Test Strength of the password" time=".122217" >
<system-out/>
<system-err/>
</testcase>
<system-out/>
<system-err/>
</testsuite>
<testsuite tests="1" id="3" package="zz_test_bl_user_registration"  disabled="0" errors="1" failures="0" name="Pswd strength" time=".083559" >
<testcase classname="zz_test_bl_user_registration" assertions="0" name="Returns pswd strength" time=".083036"  status="Error">
<error>
<![CDATA[
Call params for test are not valid: procedure Schema.ZZ_TEST_BL_USER_REGISTRATION.VALIDATE_PASSWORD_STRENGTH does not exist.
]]>
</error>
<system-out/>
<system-err/>
</testcase>
<system-out/>
<system-err/>
</testsuite>
</testsuites>

The above xml does not render when converted to html

**Comment by pesse** [comment]
I don't think that the JUNIT-Reporter was supposed to create HTML in the first place.
Its output is based on this XSD, which doesn't look like HTML: https://gist.github.com/kuzuha/232902acab1344d6b578

Could you provide an example of what's wrong and what you'd expect?

**Comment by guruo5** [comment]
Any idea on how to generate an HTML report from the Junit reporter?

**Comment by pesse** [comment]
What's the goal you want to achieve?
The only reporter we currently have in utPLSQL that produces HTML is the Coverage HTML reporter (`ut_coverage_html_reporter`)

**Comment by guruo5** [comment]
I appreciate your quick response !  My goal is to get HTML report for my test run.

**Comment by pesse** [comment]
With the purpose of having a nicely formatted result?
That's a task usually done by your CI solution. utPLSQL does not come with a specific reporter to do that at the moment.
If you tell us more about your goals we might be able to give some advice regarding continuous integration (there's even a very lightweight solution based on APEX).

**Comment by guruo5** [comment]
If I am using Jenkins for my CI solution, what plugin I would need to display an HTML report?

**Comment by lwasylow** [comment]
Hi @guruo5  , the documentation about reporters should hopefully help : [http://utplsql.org/utPLSQL/v3.1.9/userguide/reporters.html](http://utplsql.org/utPLSQL/v3.1.9/userguide/reporters.html)
There is an plugin junit or something between those lines, havent use Jenkins for while now.

**Comment by pesse** [comment]
From the Jenkins PlugIn page:
https://plugins.jenkins.io/htmlpublisher
Maybe that's what you're looking for?
Do you already import the JUNIT-output from utPLSQL into Jenkins?

**Comment by jgebal** [comment]
@guruo5 
This is the plugin that you will need.
There are others too but this one works for sure.
https://www.google.com/search?q=jenkins+junit+test+resutls&oq=jenkins+junit+test+resutls

https://wiki.jenkins.io/display/JENKINS/JUnit+Plugin

**Comment by jgebal** [comment]
As an action item, we should probably have a section in documentation or some blog posts about integrating utPLSQL with CI servers like Jenkins.
