### ISSUE TITLE
XML codecoevarge incosistency for multiline statement

### ISSUE THREAD

**Issue by shirish-chavan** [utPLSQL/utPLSQL#1040]
**Describe the bug**
XML code coverage inconsistency for single (multi-line) statement

**Provide version info**
utPLSQL = 3.1.6 and Database = Oracle 12.1 c 

**Information about client software**
What client was used to run utPLSQL tests? 
PLSQL Developer

**To Reproduce**
Run ut.execute in SONAR compatible mode.
e.g
ut.run(''UT3.TEST_PKG_UTPLSQL_FRAME_UTY_10'', ut_coverage_sonar_reporter, a_include_objects=>ut_varchar2_list('PKG_BATCHES')); 

**Expected behavior**
XML code coverage should show full coverage of a multi-line statement.

**Example code**
Snapshots attached Check lines 1860,1864, 1843, 1846 in both snippets. These are single statements executed in both the cases , but there is inconsistency observed in lines covered, same is visible in snippets.

**Additional context**
This is causing inconsistency in SONAR unit coverage.

**Comment by lwasylow** [comment]
Hi, did you test it on latest version of utPlsql, before we do any more investigation?

**Comment by shirish-chavan** [comment]
No, but was it know issue with 3.1.6.

**Comment by lwasylow** [comment]
There are some fixes to reporters in 3.1.7.
Could you try on latest version  of code.

**Comment by jgebal** [comment]
Hi @shirish-chavan 
Can you provide the files/partial files that would indicate the differences in coverage reports?

I'm not sure what do you mean by inconsistency.
Can you explain in detail?
Also, depending on the version of database you're on, you might see different behavior as coverage is gathered using Oracle-provided packages `dbms_profiler` and `dbms_plsql_code_coverage`.

Those are not perfect and can lead to some odd reports depending on how your code is formatted.

Without sample code and sample results it will be impossible to provide valuable help here I'm afraid.

**Comment by shirish-chavan** [comment]
Hi @jgebal 

I am not able to attach code snippets. I am trying to explain it below.
1. Database (12.1 c), schema are same, testcases are same still 2 runs gave 2 different SONAR xml coverages.
2. One statement is spanning over multiple lines.

**Snippet with line numbers from code block**

1843    Rec_Txn_Limt_Pln_Detl_Plan.Min_Amount := COALESCE (
1844    Rec_Txn_Limt_Pln_Detl_Promo.Min_Amount, Rec_Txn_Limt_Pln_Det_Dev.Min_Amount
1845    , Rec_Txn_Limt_Pln_Detl_Plan.Min_Amount) ;
1846    Rec_Txn_Limt_Pln_Detl_Plan.Min_Amount_Resp := COALESCE (
1847    Rec_Txn_Limt_Pln_Detl_Promo.Min_Amount_Resp,
1848    Rec_Txn_Limt_Pln_Det_Dev.Min_Amount_Resp,
1849    Rec_Txn_Limt_Pln_Detl_Plan.Min_Amount_Resp) ;
1850    Pv_Rec_Limit_Level (g_MIN_AMOUNT) :=
1851 
1852    CASE
1853    WHEN Rec_Txn_Limt_Pln_Detl_Promo.Min_Amount IS NOT NULL THEN
1854      g_PROMO
1855    WHEN Rec_Txn_Limt_Pln_Det_Dev.Min_Amount IS NOT NULL THEN
1856      g_DEVICE
1857    ELSE
1858      g_DEVICE_PLAN
1859    END;

**Run 1 (faulty):** 
   1st Statements starting at line 1843 end at 1845, (Coverage shown true at 1843 and false at 1844,1845) 
   
   2nd Statements  starting at line 1846 end at 1849, (Coverage shown true at 1846 and false from 1847 to 1849)
   
   3rd Statements starting at line 1850 end at 1859, ( Coverage shown true at 1850 and false at 1852,1853 and 1855 other in between lines 1851, 1854, 1856, 1857, 1858, 1859 are shown not covered)

**Run 2 (Good):** 

. 1st Statements starting at line 1843 end at 1845, (Coverage shown true from 1843 to 1845) 
  
  2nd Statements  starting at line 1846 end at 1849, (Coverage shown true from 1846 to 1849)

  3rd Statements starting at line 1850 end at 1859, ( Coverage shown true at 1850, 1852,1853, 1855 other in between lines 1851, 1854, 1856, 1857, 1858, 1859 are shown not covered)
 

Any coverage is at statement level it's not possible in single plan (non-conditional) assignment statement to cover one part and not cover rest.
95% of the time it gives results like 2nd run , in between 5% of the time it gives results like 1st run. 

Please let me know for any more details.

**Comment by jgebal** [comment]
What database version are you running on?
We gather coverage based on `DBMS_PROFILER` data.
If the data generated by Oracle `DBMS_PROFILER` package gives us false, we take it as false for line execution.

One question that also comes to my mind is.
Are you compiling packages in between the runs?
Do you always use the same PLSQL_OPTIMIZE_LEVEL when compiling the packages?

The `PLSQL_OPTIMIZE_LEVEL` may have impact on coverage as with level 3, oracle performs a lot of sub-program inlining.

**Comment by jgebal** [comment]
@shirish-chavan 
Would you be able to check coverage tables?
I usually use this query for the purpose.
```
SELECT a.runid, a.run_owner, a.run_comment,
       c.total_occur,
       b.unit_type, b.unit_owner, b.unit_name, c.line#, u.text
  FROM plsql_profiler_runs a
  JOIN plsql_profiler_units b ON ( a.runid = b.runid )
  join plsql_profiler_data c on ( a.runid = c.runid and b.unit_number = c.unit_number)
  LEFT JOIN dba_source u ON (b.unit_name = u.NAME AND b.unit_owner = u.owner AND c.line# = u.line AND b.unit_type = u.TYPE )
 WHERE 1=1
    AND total_occur = 0
--   AND b.unit_name = 'UT_EXPECTATION_CLOB'
 ORDER BY a.runid DESC, line_total_secs DESC,
    b.unit_name, line;
```

If there are inconsistencies (we look at between data for different runs I think it will indicate an internal Oracle coverage reporting issue.

We consider line of code as :
- covered when `total_occur > 0 or total_time > 0` for that line.
- not covered when `total_occur = 0`
- irrelevant (not executable) in any other case


Hope this helps.

**Note**
If we don't hear back from you we will most probably close this issue.

**Comment by lwasylow** [comment]
No reply since Jan. Closing
