### ISSUE TITLE
HTML-Coverage Report can not be shown with https on jenkins

### ISSUE THREAD

**Issue by ThisGuenter** [utPLSQL/utPLSQL#1041]
We are generating html coverage report on Jenkins. 
Our Jenkins interface is delivered via https.

Assets liked in generated HTML report can not be loaded because:

 SEC7137: [Mixed-Content] Der Ursprung "https://<our-jenkins>" wurde in einem sicheren Kontext geladen und hat eine unsichere image-Ressource bei "http://utplsql.org/utPLSQL-coverage-html/assets/loading.gif" geladen, die optional blockiert werden kann.

 SEC7111: [Mixed-Content] Der Ursprung "https://<our-jenkins>" wurde in einem sicheren Kontext geladen, hat aber versucht, eine unsichere style-Ressource bei "http://utplsql.org/utPLSQL-coverage-html/assets/application.css" zu laden.

 SEC7111: [Mixed-Content] Der Ursprung "https://<our-jenkins>" wurde in einem sicheren Kontext geladen, hat aber versucht, eine unsichere script-Ressource bei "http://utplsql.org/utPLSQL-coverage-html/assets/application.js" zu laden.

Issue fixed temporarily by providing assets locally on jenkins and changing body ut_coverage_report_html_helper line 33 
```sql
    c_assets_path constant varchar2(200) := 'https://utplsql.github.io/utPLSQL-coverage-html/assets/';
    c_assets_path constant varchar2(200) := '/userContent/utplsql/';
'''

**Provide version info**
UT_VERSION    
v3.1.9.3270    

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production 
PL/SQL Release 12.2.0.1.0 - Production
CORE	12.2.0.1.0	Production 
TNS for 64-bit Windows: Version 12.2.0.1.0 - Production
NLSRTL Version 12.2.0.1.0 - Production

PARAMETER                 VALUE                          
NLS_LANGUAGE               ENGLISH                         
NLS_TERRITORY              GERMANY                         
NLS_CURRENCY               €                               
NLS_ISO_CURRENCY           GERMANY                         
NLS_NUMERIC_CHARACTERS     ,.                              
NLS_CALENDAR               GREGORIAN                       
NLS_DATE_FORMAT            DD.MM.RRRR                      
NLS_DATE_LANGUAGE          ENGLISH                         
NLS_SORT                   BINARY                          
NLS_TIME_FORMAT            HH24:MI:SSXFF                   
NLS_TIMESTAMP_FORMAT       DD.MM.RRRR HH24:MI:SSXFF        
NLS_TIME_TZ_FORMAT         HH24:MI:SSXFF TZR               
NLS_TIMESTAMP_TZ_FORMAT    DD.MM.RRRR HH24:MI:SSXFF TZR    
NLS_DUAL_CURRENCY          €                               
NLS_COMP                   BINARY                          
NLS_LENGTH_SEMANTICS       BYTE                            
NLS_NCHAR_CONV_EXCP        FALSE                           

**Information about client software**
SQLPlus

**Comment by pesse** [comment]
If you use [utplsql-cli](https://github.com/utPLSQL/utPLSQL-cli), the necessary assets are copied to a folder relative to your output file.
I think this should solve your issue.

**Comment by ThisGuenter** [comment]
@pesse Thanks for your input - will go for solution as proposed in https://github.com/utPLSQL/utPLSQL/issues/518
