### ISSUE TITLE
UT.run 0 results 

### ISSUE THREAD

**Issue by preethileela** [utPLSQL/utPLSQL#1047]
Hi I have been facing issue with test package .test case execution and coverage report generation. 
Created an test package with single proc inside it which would validate the actual and expected cursor result. When I run this test package separately it results the verification result and shows sucess. When I try using. It.run(username.testpackahename) it shows 0 test ,0failed everythin is 0.
I just tried the actual package and test package in same schema to avoid confusion still it doesn't work.i have used annotation as %suite ,%test. Pls help on this.
When I run the test package provided in utplsql GitHub awardbonus it works good.

**Comment by jgebal** [comment]
Can you share your sample code and exact steps we should take to reproduce?
What version of utPLSQL are you using?
What database version are you on?

It's really hard to give meaningful help without ability to reproduce **exactly** your scenario.

**Comment by preethileela** [comment]
I made an mistake in annotation where it makes the 0 tests I have corrected it now. But the second issue for me is ut_coverage_sonar_reporter is not able to get the coverage for the actual package is in another schema.

Ex: applicationpackage(actual package) in schema1.
Test package is in schema1 under user2.

**Comment by jgebal** [comment]
This document could help
https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/coverage.md#schema-based-coverage

**Comment by preethileela** [comment]
I read the document I tried to use same format by providing user1 and user2. Whereas it doesn't    works

**Comment by jgebal** [comment]
hi @preethileela 
Please provide detailed example and steps o reproduce.

**Comment by preethileela** [comment]
I have found RCA. Profiler is not storing across schema objects in order to retrieve the data from there.

**Comment by jgebal** [comment]
I'm closing the issue, as no details provided.
