### ISSUE TITLE
Unit Test of Procedure which is having SYS_REFCURSOR as OUT parameters

### ISSUE THREAD

**Issue by pushpendu91** [utPLSQL/utPLSQL#1057]
I have many procedures where out parameters are mostly SYS_REFCURSORs, in that case how will I create the test cases and how will i get the results back? 
Mainly all these procedures are being called from Java , but I need a unit test framework for these stored procedures.
Can that be done using utPLSQL ??

**Comment by jgebal** [comment]
@pushpendu91 
IS there anything else you need? If not I'll close this issue.

**Comment by jgebal** [comment]
Closing as no reply from the author
