### ISSUE TITLE
Document that utPLSQL does not make use of any costed database options

### ISSUE THREAD

**Issue by john-otoole** [utPLSQL/utPLSQL#1064]
While installing utPLSQL v3.1.10 on a customer's development database recently, we were asked by the customer's DBA team if utPLSQL is using any licensed Oracle database features such as Diagnostics pack / Tuning pack. They saw that it is using DBMS_PROFILER and wondered what else it might be doing. I know that utPLSQL is not using Diagnostics pack / Tuning pack and that it uses DBMS_PROFILER for code coverage. I responded to them with that information. 

Would it be worth stating some of this in the utPLSQL documentation? e.g. on the install.html page of the documentation, explicitly state that utPLSQL does not have any dependency on costed database options such as Diagnostics pack / Tuning pack / Partitioning etc.

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this.

The installation part of the [documentation](https://github.com/utPLSQL/utPLSQL/blob/ea4c9fb851f00de72a97d8282283e1d0f84a6193/docs/userguide/install.md#supported-database-versions) states that

> utPLSQL may be installed on any supported version of Oracle Database may be installed on any supported version of Oracle Database

So the answer is, that it does not use features of Oracle Editions that must be licensed separately. 

However, I guess we could add that to the documentation for clarification purposes.
