### ISSUE TITLE
wrong number or types of arguments in call to 'UT_COVERAGE_HTML_REPORTER'

### ISSUE THREAD

**Issue by itguyforautomation** [utPLSQL/utPLSQL#1066]
OS: MacOS Mojave 10.14.6
Database Version: "Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.6.0.0.0"
SQL Developer Version: 19.2.1.247
utPLSQL Version: v3.1.10.3349
utPLSQL-SQL Developer extension Version : v1.1.1

We are getting an error while running the test coverage report;

I can provide you more details if needed. 

Please guide me.
 
![image](https://user-images.githubusercontent.com/39102994/78594619-a1f4a580-7816-11ea-9ffd-4f6b72f3beaa.png)

**Comment by PhilippSalvisberg** [comment]
I've transferred this issue to the utPLSQL repository since it is not related to the SQL Developer extension.

**Comment by jgebal** [comment]
@itguyforautomation  - any feedback on this issue?

**Comment by itguyforautomation** [comment]
Thanks much for the assistance @jgebal.  
It works!
