### ISSUE TITLE
Improve TeamCity Reporter to provide DisplayName

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL#1071]
Currently, `ut_teamcity_reporter`, which is used for DataGrip integration, doesn't provide `--%displayname` information of tests.

We should improve the TeamCity Reporter to provide that info and let DataGrip show the more useful DisplayName without losing Navigation-Hints.

We should also improve it to work according to the latest TeamCity Service Message specification:
https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html

I will update this issue with more details once I dived into it a bit more.

Implementation of the TeamCity Service Message interpretation can be found here:
https://mvnrepository.com/artifact/org.jetbrains.intellij.deps/teamcity-service-messages/2019.1.4-alpha

**Comment by lwasylow** [comment]
@pesse , is that still valid?
Do you have any more details around it ?
Changes should be fairly easy to make , however not sure the specs.

**Comment by lwasylow** [comment]
Closing as is quite old. Will reopen if needed
