### ISSUE TITLE
ORA-00600: Interner Fehlercode, Argumente: [qcsfbdnp:1], [OTHER_GUID]

### ISSUE THREAD

**Issue by getpreetam** [utPLSQL/utPLSQL#1089]
Dear All,

I am trying to explore utPL/SQL for our project. But somehow when it comes to collection, inequality check returns ORA-00600.
Below are the details: Can you pls have a look ?

DB: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
utPL/SQL: v3.1.10

create or replace type dummy_obj as object (
  id number,
  "name"  varchar2(30),
  "Value" varchar2(30)
);

create or replace type dummy_obj_lst as table of dummy_obj;

SQL> exec ut.expect( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) ).to_equal( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) );
SUCCESS
  Actual: utp3.dummy_obj_lst [ count = 1 ] was expected to equal: utp3.dummy_obj_lst [ count = 1 ]
PL/SQL procedure successfully completed

SQL> exec ut.expect( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) ).to_equal( anydata.convertCollection( dummy_obj_lst( dummy_obj( 2, 'A', '0' ) ) ) );
begin ut.expect( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) ).to_equal( anydata.convertCollection( dummy_obj_lst( dummy_obj( 2, 'A', '0' ) ) ) ); end;
ORA-00600: Interner Fehlercode, Argumente: [qcsfbdnp:1], [OTHER_GUID], [], [3], [], [], [], [], [], [], [], []

**Comment by jgebal** [comment]
@lwasylow, @PhilippSalvisberg 
Any idea why we could get this kind of error?
It seems like some Oracle internal issue.

I tried reproducing it on 11g XE - no issues.
```sql
SQL> create or replace type dummy_obj as object (
id number,
  2    3  "name" varchar2(30),
  4  "Value" varchar2(30)
  5  );
  6  /

Type created.

SQL> create or replace type dummy_obj_lst as table of dummy_obj;
  2  /

Type created.

SQL> exec ut.expect( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) ).to_equal( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) );
SUCCESS
Actual: apps.dummy_obj_lst [ count = 1 ] was expected to equal:
apps.dummy_obj_lst [ count = 1 ]

PL/SQL procedure successfully completed.

SQL> exec ut.expect( anydata.convertCollection( dummy_obj_lst( dummy_obj( 1, 'A', '0' ) ) ) ).to_equal( anydata.convertCollection( dummy_obj_lst( dummy_obj( 2, 'A', '0' ) ) ) );
FAILURE
Actual: apps.dummy_obj_lst [ count = 1 ] was expected to equal:
apps.dummy_obj_lst [ count = 1 ]
Diff:
Rows: [ 1 differences ]
Row No. 1 - Actual:   <ID>1</ID>
Row No. 1 - Expected: <ID>2</ID>
at "anonymous block", line 1

PL/SQL procedure successfully completed.

SQL>
```

**Comment by jgebal** [comment]
I've also run the same test on 12.1 SE - no issues there too.

```sql
SQL> select * from v$version;

BANNER
--------------------------------------------------------------------------------
    CON_ID
----------
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production
         0

PL/SQL Release 12.1.0.2.0 - Production
         0

CORE    12.1.0.2.0      Production
         0


BANNER
--------------------------------------------------------------------------------
    CON_ID
----------
TNS for Linux: Version 12.1.0.2.0 - Production
         0

NLSRTL Version 12.1.0.2.0 - Production
         0


SQL>

```

I assume it must be something related to DB version you're on.
Either you are missing some patches or a patch that was applied introduced this bug.

I cant reproduce it locally :(

**Comment by getpreetam** [comment]
@jgebal  Thank you so much for checking this for me & your time. 
I will try to check this further at my end.

**Comment by PhilippSalvisberg** [comment]
ORA-600 errors are bugs in the Oracle database code. We might find a workaround, if we can reproduce the error in our environment. But I cannot reproduce the error in my 12.1.0.2 environment.

The ORA-600 lookup tool recommends to have a look at MOS document 285899.1. There are some related bugs and fixes listed. However, I suggest to open a SR.

**Comment by getpreetam** [comment]
Thank you @PhilippSalvisberg  for this, even I checked and Bug 21373076 looks relevant to us .. we have 19670108 patch but still receiving ORA-00600. exploring it further!

**Comment by pesse** [comment]
Hey @getpreetam - is still relevant? Otherwise I would like to close the issue, because it seems to be an Oracle bug after all.

**Comment by getpreetam** [comment]
Thanks @pesse , Please close it. It was solved after applying a patch.
