### ISSUE TITLE
utPLSQL Reporter shows Anonymous Block in PLSQL_PROFILER_UNITS

### ISSUE THREAD

**Issue by yenajjj** [utPLSQL/utPLSQL#1090]
I'm running the ut_coverage_cobertura_report via block, but by passing the test suite name. however it shows 0 coverage since when I debugged the UT codes, it's showing anonymous block instead of the test suite package/ procedure name. And user shows to be <anonymous>

Goes something like this. Am I missing any setup required? I

![image](https://user-images.githubusercontent.com/67639072/87821346-4a001d00-c8a2-11ea-99f7-6242c4a6e415.png)

**Comment by lwasylow** [comment]
Have you tried run tests as apps user? Usually privs stopping coverage.

**Comment by yenajjj** [comment]
Yes, tried running using the ut user and as apps as well.
________________________________

**Comment by jgebal** [comment]
Hi @yenajjj 

Can you provide the following information?
- database version
- utPLSQL version
- what exactly are you getting as opposed to what you thing you should be getting
- steps for me to reproduce the issue

I can't figure out what is it that you need after reading your comment.

**Comment by yenajjj** [comment]
Hi,

We're using DB version 12.1. But you can disregard. I ran DBMS Profiler alone and it's doing the same anonymous data.

Best Regards

________________________________
