### ISSUE TITLE
Html coverage report issue

### ISSUE THREAD

**Issue by ksawerykarwacki** [utPLSQL/utPLSQL#1095]
Report stored remotely doesn't load as assets for it are stored on non https address and browser raises issue with mixed content. 

Workaround:
manually download js/css/png files and store them locally.

**Comment by jgebal** [comment]
utPLSQL-cli is using local assets.
You could do the same.
the `ut_html_coverage_reporter` accepts the path to assets in constructor:
```
  constructor function ut_coverage_html_reporter(
    self in out nocopy ut_coverage_html_reporter,
    a_project_name varchar2 := null,
    a_html_report_assets_path varchar2 := null
  ) return self as result,
```

**Comment by pesse** [comment]
Closing due to no further feedback
