### ISSUE TITLE
Code Formatting Standards

### ISSUE THREAD

**Issue by rlove** [utPLSQL/utPLSQL#11]
What code formatting standards should we use if any?

Options

- None (I think this is a bad idea)
- Use something developed by someone else such as one off these:
   - [Toad World - includes one by Steven Feuerstein](https://www.toadworld.com/platforms/oracle/w/wiki/8245.plsql-standards)
   - [Top Coder - Oracle PLSQL Coding Guidelines ](http://www.topcoder.com/i/development/uml/Oracle_PLSQL_Coding_Guidelines.pdf)
  - [Jonathan Ingram - Burleson Consulting](http://www.dba-oracle.com/t_plsql_best_practices_standards.htm)
- Developer our own (most likely by copying what we like from others and put it in the wiki as our decided standard.)

**Comment by PaulWalkerUK** [comment]
Absolutely agree we should have a standard. I'm not too precious about what it is. These are some of my personal thoughts, I'm more than happy to go with the consensus ...

I've personally tended to follow something close to Steven Feurstein's guidelines and find they work quite well for me. One thing I do slightly differently is naming parameters. Steven suggests using `_i`, `_o` and `_io` as *suffixes*, but since I've already got `l_` and `g_` *prefixes* to indicate scope, I put the `i_`, `o_` and `io_` as prefixes as well.

I always go for 4 spaces for indentation, opening brackets usually go on the same line and lots of small, clear procedures/functions that do one specific task

I've never liked the idea of nested subprograms. Since pretty much everything goes in packages, if I want to keep something private, I just don't put it in the spec.

One thing that I've never understood is when dealing with a list, why some people like putting commas at the start of the next line, rather than the end of the preceding line, it always looks odd to me:

```sql
SELECT   col_a
       , col_b
       , col_c
FROM   tab;
```

I always write it as: 

```sql
SELECT col_a,
       col_b,
       col_c
FROM   tab;
```

Just my own personal taste...

**Comment by Shoelace** [comment]
@PaulWalkerUK  I prefer the comma in front.. it allows you to easily do things like

```plsql
SELECT   col_a
--       , col_b
       , col_c
FROM   tab;
```

it also means all the comma's line up without having to put arbitrary spacing afterwards

my suggestion would be something that could be (at least mostly) automated/checked.
i know you can import/export formatting options from sqldeveloper so they can be shared
or something external such as  https://github.com/dnsmkl/fsqlf

**Comment by rlove** [comment]
I flip flop on syntax of my PL/SQL code all the time, hence my question.

I tend to use leading commas for both SQL and multi-line parameters.   But then again, I am not consistent but can be if I have direction.

**Comment by jgebal** [comment]
I recently read some nice posts on:
https://oracle-base.com/blog/2015/11/25/plsql-formatting-more-pearls-of-wisdom-from-bryn/
I like idea of simplicity (all downcase ) even though I was using mixed
case for many many years.

**Comment by PaulWalkerUK** [comment]
I'm really not particular - so long as it's tidy, readable and consistent :smile:

**Comment by Pazus** [comment]
Hello,

Have you established a final formating guide?

**Comment by jgebal** [comment]
Just a proposition:
- lower_snake_case
- aliases over prefixes (for variables)
- plural for collections/tables
- singular otherwise
- functions/procedure names should be meaningful and describe actions performed
- indentation with spaces (3 chars?)
- ANSI over Oracle SQL syntax

The standards cant be too strict and too complex to make contribution easy.

**Comment by Shoelace** [comment]
@jgebal can you explain "aliases over prefixes" ?

other wise i'm happy but would  prefer 4 spaces for indenting. (i personally prefer actual tabs. but i understand the space thing)

**Comment by Pazus** [comment]
In our company PL/SQL developer is used so the most convenient way to format code identically everywhere is to share the beautified config file. Unfortunately I don't know similar tool that is not IDE  dependent or at least the IDE is free. Maybe someone can suggest one?

**Comment by jgebal** [comment]
@Pazus I was also looking for some free PL/SQL and SQL formatting tool about a month ago or so, but found nothing that would be usable. Maybe others were more lucky.

@Shoelace what i had in mind is to rather use:
```sql
procedure update_employee_name( first_name varchar2, last_name varchar2) is
begin
update employees emp
     set emp.first_name = update_employee_name.first_name,
           emp.last_name = update_employee_name.last_name
end;
```
Though, now that I look at it it doesn't look so nice, so maybe plain old prefixes or suffixes for parameters/variables would be better.
```sql
procedure update_employee_name( p_first_name varchar2, p_last_name varchar2) is
begin
update employees emp
     set emp.first_name = p_first_name,
           emp.last_name = p_last_name
end;
```

**Comment by Shoelace** [comment]
just found this as another potential option

https://blogs.oracle.com/LetTheSunShineIn/entry/sql_developer_format_sql_with

**Comment by Shoelace** [comment]
anotehr guideline document i discovered today
http://www.trivadis.com/sites/default/files/downloads/PLSQL_and_SQL_Coding_Guidelines_2_0_HiRes.pdf

**Comment by jgebal** [comment]
Could we agree to use free SQL Developer as a tool for code formatting?
We can probably figure a way of sharing formatter settings.

**Comment by Shoelace** [comment]
@jgebal i did that already. if you look at my comment above from Feb 26 i have attached a sample SQLDeveloper formatter settings.  its not correct anymore but shows you can share them.

unless someone can come up with a specific reason to use another tool, then using the oracle provided developer environment to do formatting of oracle code seems like a reasonable choice.

plus with the command line format option it can be automated as part of a build/pre-commit process

infact here is a modified SQLDeveloper formatter settings file
[utplsql_code_style.xml.txt](https://github.com/utPLSQL/utPLSQL/files/375735/utplsql_code_style.xml.txt)

this version is: all lowercase , 4 space indents, leading commas  and other stuff i've picked.

it can be updated as we decided what needs changing

just remove the .txt extenstion and import from the preferences menu
![image](https://cloud.githubusercontent.com/assets/391364/17020375/25c4c6b6-4f39-11e6-8553-e0da5aa4dc51.png)

once import goto the Oracle formatting bit and choose the new profile
![image](https://cloud.githubusercontent.com/assets/391364/17020400/4646434c-4f39-11e6-9b78-54b92c10181e.png)

**Comment by jgebal** [comment]
@Shoelace great job!
I love the idea of automated formatting.I'll actually plug in a shortcut to my IDE.

**Comment by Shoelace** [comment]
i was going to add a batch/shell file to format teh source directory using the sqldeveloper CLI.. but your welcome to do it first.

**Comment by jgebal** [comment]
I'm to busy during week to contribute.
Might have some time over weekend.

**Comment by Pazus** [comment]
Now as we've finally set formatting rules lets define naming convension.
Choosing from three items from first post personaly I prefer the second one: [Top Coder - Oracle PLSQL Coding Guidelines](http://www.topcoder.com/i/development/uml/Oracle_PLSQL_Coding_Guidelines.pdf). 
Also it has reference to utPLSQL at the botton.

**Comment by jgebal** [comment]
Seems like yesterday we came int some basic agreement on naming conventions.
The standard so far seems to be:
- all lower case
- 2 spaces indent

We didn't come into agreement on code formatter to be used.
It seems essential not to use a paid tool for formatting, as this could prevent contributors from being able to provide properly formatted code.

So far considered options are: SQL Developer, TOAD Freeware.

**Comment by rlove** [comment]
I placed the name rules in https://github.com/utPLSQL/utPLSQL/blob/version3/CONTRIBUTING.md

We will need to do the same for comments for documentation purposes with natural docs.

If a required automatic formatter is used for the code then spacing will not be an issue.   
Although I am still not sold on the idea of using a formatter yet.
