### ISSUE TITLE
Speed up tests with dbms_parallel_execute

### ISSUE THREAD

**Issue by ArinUsole** [utPLSQL/utPLSQL#1102]
Is it possible to speed up the execution of tests using dbms_parallel_execute?

In the test, I go through many steps (in a loop). Can a test be executed in parallel (example in attachment)?

I tried running in parallel, no result is negative.

Example in simple mode:
      [31mActual: refcursor [ count = 2 ] was expected to equal: refcursor [ count = 2 ][0m
      [31mDiff:[0m
      [31mRows: [ 1 differences ][0m
      [31m  PK <NSEID>9249828480</NSEID><NDNUM>2</NDNUM> - Actual:   <NCACN>32216118</NCACN><SCACC>70601810700002720410</SCACC>[0m
      [31m  PK <NSEID>9249828480</NSEID><NDNUM>2</NDNUM> - Expected: <NCACN>32216127</NCACN><SCACC>70601810900002720210</SCACC>[0m
      [36mat "RBR.TEST_TYPICALOPERATIONDOCUMENT", line 18 ut.expect(l_expected).to_equal(l_actual).join_by('NSEID,NDNUM').exclude('NFDID,DODDT');
      at "RBR.TEST_TYPICALOPERATIONDOCUMENT", line 24[0m
       
**Finished in 535.47212 seconds**

[simple.test_typicaloperationdocument.txt](https://github.com/utPLSQL/utPLSQL/files/5297280/simple.test_typicaloperationdocument.txt)
[paralell.test_typicaloperationdocument.txt](https://github.com/utPLSQL/utPLSQL/files/5297283/paralell.test_typicaloperationdocument.txt)

**Comment by PhilippSalvisberg** [comment]
This is currently not supported. This would be an enhancement. See also #881
