### ISSUE TITLE
Installation fails when it comes to UT_COVERAGE 

### ISSUE THREAD

**Issue by ilterkaankaraca** [utPLSQL/utPLSQL#1105]
**Describe the bug**
Headless installation with triggers fails when it comes to UT_COVERAGE 

**Provide version info**
Oracle 11g and utPLSQL  3.1.10

ORA-24344: Erfolg mit Kompilierungsfehler
80/183  PLS-00103: Fand das Symbol "," als eines der folgenden erwartet wurde:
          * & = - + ; < / > at in is mod remainder not rem
          <an exponent (**)> <> or != or ~= >= <= <> and or like like2
          like4 likec between || multiset member submultiset

**Comment by jgebal** [comment]
Is it 11g Release 2?
Please provide:
- full database version
- full error stack including line numbers for errors
- Information on what installation steps that you took to get to this error

**Comment by ilterkaankaraca** [comment]
Hi, I was trying to run the script from TOAD. I ran it with SQL*Plus and it is okay now. Thank you
