### ISSUE TITLE
Issue in Installation of utPLSQL in Existing Schema

### ISSUE THREAD

**Issue by PriyankaKeer** [utPLSQL/utPLSQL#1110]
Hi Team,

Please let us know the steps of Installing utPLSLQL in existing Database schema. 
Have tried installing through **install.sql** and also executed **create grants and synonyms for public.sql** , But utPLSQL is not getting installed. Please help us out in this issue

Thanks and Regards
Priyanka

**Comment by PhilippSalvisberg** [comment]
Hi @PriyankaKeer,

Could you please provide the information we need for a bug report (see https://github.com/utPLSQL/utPLSQL/issues/new?assignees=&labels=&template=bug_report.md&title=).

Thank you.

**Comment by PriyankaKeer** [comment]
**Describe the bug**
Not able to install utPLSQL in existing schema

Provide version info
Information about utPLSQL and Database version:

UTPLSQL Version--v3.1.7.3096
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
"CORE 12.1.0.2.0 Production"
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production
NLS_LANGUAGE AMERICAN
NLS_TERRITORY AMERICA
NLS_CURRENCY $
NLS_ISO_CURRENCY AMERICA
NLS_NUMERIC_CHARACTERS .,
NLS_CALENDAR GREGORIAN
NLS_DATE_FORMAT DD-MON-RR
NLS_DATE_LANGUAGE AMERICAN
NLS_SORT BINARY
NLS_TIME_FORMAT HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY $
NLS_COMP BINARY
NLS_LENGTH_SEMANTICS BYTE
NLS_NCHAR_CONV_EXCP FALSE
x86_64/Linux 2.4.xx

Information about client software
SQLDeveloper and PLSQL developer Tool

**To Reproduce**
Steps to reproduce the behavior:
1. Tried executing install.sql command 
2. And tried with create synonyms and grants for public
3. Both commands showed executing and finished execution in less than a minute
4. utPLSQL is not installed as there are no inbuilt utplslq packages or tables in the schema
5. tried executing a testcase, but it showed ut is not recognised

**Expected behavior**
utPLSQL need to get installed in existing schema

**Example code**
NA

**Additional context**
NA

Thanks and Regards,
Priyanka

**Comment by PhilippSalvisberg** [comment]
What user have you used to run the `install.sql` script? 

The user must be a DBA. Running `install.sql` when connect as the target utPLSQL schema does not work. See also http://utplsql.org/utPLSQL/latest/userguide/install.html#installing-utplsql .

We recommend to install the latests release. This is currently 3.1.10.

**Comment by PriyankaKeer** [comment]
What user have you used to run the `install.sql` script?--SYS USER

The user must be a DBA. Running `install.sql` when connected as the target utPLSQL schema does not work. See also http://utplsql.org/utPLSQL/latest/userguide/install.html#installing-utplsql . ---DBA itself logged in and tried to install
 
We recommend to install the latest release. This is currently 3.1.10. --We have also tried with Latest version..still the same issue

Please Suggest

Thanks in Advance!

**Comment by PhilippSalvisberg** [comment]
Could you please let us know the parameters you used for `install.sql` and share the output produced by script? Thanks.

**Comment by PriyankaKeer** [comment]
> Could you please let us know the parameters you used for `install.sql` and share the output produced by the script? Thanks.

We used below command 
**install.sql name of the existing schema;**

Thanks in Advance!

**Comment by PhilippSalvisberg** [comment]
@PriyankaKeer Is the schema name a secret? Does the log file contain confidential information?  - I cannot reproduce the behaviour you are describing. If you expect us to help you then please provide the requested information. Thanks.

**Comment by PhilippSalvisberg** [comment]
@PriyankaKeer editing a comment is ok, when you fix a typo are formatting errors. But please do not add additional information such as 

>Output is nothing and the command got executed moving the cursor to next line.

You did not get any output? This is very very strange. Could you please provide a screenshot of the SQL*Plus session? Thanks.

**Comment by PriyankaKeer** [comment]
> @PriyankaKeer Is the schema name a secret? Does the log file contain confidential information? - I cannot reproduce the behaviour you are describing. If you expect us to help you then please provide the requested information. Thanks.

No i can provide the schema name..
Its **install.sql apps;**
And there is no such error log..we tried executing the install command, and the command line moved to next line. 
Then we tried executing **create grants and synonyms for public.sql** command. and the command line moved to next line(same as install.sql). 
To check whether the installation is done fine or not, i tried checking all the inbuilt tables and procedures ut.runner, ut.temp etc.., which will be appearing once installation is done.
Even they are not coming up in the schema, which implies that the installation is not done.

Also we tried creating a testcase, but that too didn't work showing compilation error in ut.expect(as installation is not done).

Are we lacking any grants for schema?

Can u pls let us know how to install utPLSQL in an existing schema, if there are any pre-defined steps for it , we will follow that and will try from our side.

Thanks in Advance!

**Comment by PhilippSalvisberg** [comment]
The installation is documented here: http://utplsql.org/utPLSQL/latest/userguide/install.html#installing-utplsql . IMO it is not possible that the [install.sql]() produces an empty `install.log`. Please provided this log file. Thanks. 

Anyway, I did the following (see also attached [install_log.txt](https://github.com/utPLSQL/utPLSQL/files/5743217/install_log.txt) for results of steps 3 to 8): 

1. Downloaded https://github.com/utPLSQL/utPLSQL/releases/download/v3.1.10/utPLSQL.zip 

2. Unzipped utPLSQL.zip

3. Changed to the source directory (in my case `/Users/phs/Downloads/utPLSQL/source`)

```
cd /Users/phs/Downloads/utPLSQL/source
```

4. Started SQLcl as user SYS

```
sql sys/oracle@odb121 as sysdba
```

5. created the user `apps` with the necessary privileges

```sql 
create user apps identified by apps
   default tablespace users
   temporary tablespace temp
   quota unlimited on users;

grant execute on dbms_lock to apps;
grant execute on dbms_crypto to apps;

grant alter session,
      create view,
      create session,
      create table,
      create type,
      select any dictionary,
      create synonym,
      create sequence,
      create procedure 
   to apps;
```

6. Installed utPLSQL (no need to add a semicolon)

```sql
@install.sql apps
```

7. Connected as user apps

```sql
connect apps/apps@odb121
``` 

8. Run a simple test

```sql
set serveroutput on size unlimited
exec ut.expect(1).to_equal(2);
```

I've also attached the 
[install.log](https://github.com/utPLSQL/utPLSQL/files/5743233/install.log) produced by `install.sql`. This file should never be empty.

**Comment by PriyankaKeer** [comment]
Thanks a lot for the quick response.
Will try that and get back to you soon.

Thanks and Regards,
Priyanka

**Comment by PriyankaKeer** [comment]
> Thanks a lot for the quick response.
> Will try that and get back to you soon.
> 
> Thanks and Regards,
> Priyanka

We have omitted the following command as the schema is already existing in the DB.
**create user apps identified by apps
default tablespace users
temporary tablespace temp
quota unlimited on users;**

Installation is done. Thanks a lot @PhilippSalvisberg 

Regards,
Priyanka
