### ISSUE TITLE
Installation support for Amazon RDS

### ISSUE THREAD

**Issue by trebor222** [utPLSQL/utPLSQL#1117]
**Is your feature request related to a problem? Please describe.**

Our organisation is moving over to AWS RDS oracle instances and am finding it difficult to install utPLSQL as the current instructions require SYSDBA and use of sql*plus from the command line (neither of which are available with RDS).

I have been able to install utPLSQL (3.1.10) successfully to an RDS but it has taken a bit of manual work to make this happen. I used rdsadmin.rdsadmin_util.grant_sys_object from the master account to provide dbms_lock and dbms_cypto execution permissions and tried to run install.sql from a local copy of the zip file via SQL Developer. 

The define_ut3_owner_param.sql script never ran happily since was OS interactions. I found there were some initial compilation issues (UT_SUITE type - it was fine after a recompile) and there was a lot of prompting for values and sometimes scripts were not found or variable values were not carried over. 

This makes it harder to have utPLSQL supported in an environment where the databases are being built out on demand.

**Describe the solution you'd like**

To be able to automate the installation of utPLSQL to an AWS RDS so that our current pipelines can deliver an RDS with utPLSQL pre-installed for a requester

**Describe alternatives you've considered**
I have performed the installation manually but this is not a scaleable solution long term for support of spinning up new pre-built RDS instances and coping with new utPLSQL versions etc

**Additional context**

**Note**
> Please do not create issues for generic SQL or PL/SQL questions. There are other forums and communities to help you with those. See [ASKTom](https://asktom.oracle.com) for example.

**Want to discuss**
If you want to discuss your issue, join [our SLACK chat](https://join.slack.com/t/utplsql/shared_invite/zt-d6zor80g-WWqAhbLWioJZUtLYeXetzA).

**Comment by lwasylow** [comment]
Hi
Would it be possible to include installation log?
I don't have an access to. Amazon rds or. Used before. Are there free account to try replicate issue? 
You have mentioned the manual step, can youost them so we can see what helped? Is it only two packages that cause issue?
Sorry for so much questions but this is a new area for me so want to gather as much information as possible. 
Kind regards Łukasz

**Comment by pesse** [comment]
Hey @trebor222 is there still a need for help from your side? If so, could you please provide the installation log?

**Comment by jgebal** [comment]
@trebor222 
Can you provide a follow up on that issue?
If you were able to connect to your AWS RDS from SQLDeveloper, I'm pretty sure you will be ablr to connect using SQLPlus or sqlcl (the SQLPlus replacement from Oracle).

With SQLPlus or SQLCL you should be able to install utPLSQL.
I understand that adding sys-specific grants on AWS RDS require some special handling (calling rdsadmin.rdsadmin_util.grant_sys_object).

I don't think we would be incorporating that into utPLSQL install scripts directly as it is a slippery slope. We might need to add specific stuff for Oracle cloud, AZURE and Google cloud or whatever comes next.
That would easily become unmanageable.
