### ISSUE TITLE
Rollback annotation is not working as expected

### ISSUE THREAD

**Issue by PriyankaKeer** [utPLSQL/utPLSQL#1118]
Hi ,

We have a procedure which updates a value in the table, for the same procedure, we have written a testcase and had tried using %rollback(auto) annotation before testcase declaration.
We observed that though we have added %rollback(auto) or %rollback(manual) annotations, the actual rollback is not happening(after execution of testcase the updated value in the table must get rolled back)

Attaching the code for reference

**CREATE OR REPLACE PACKAGE EMP_TEST
--%suite(emp admin test)

--%rollback(auto)
--%test(emp salary test)
procedure update_emp_sal_test;**

Thanks in Advance!

**Comment by lwasylow** [comment]
Hi
Can you please also put your procedure code?

**Comment by PriyankaKeer** [comment]
> Hi
> Can you please also put your procedure code?

Hi, 
Please find below procedure code

FUNCTION update_emp_sal (
      p_empno         IN NUMBER,
      p_raise         IN NUMBER
   )
   RETURN NUMBER
   IS
      v_sal           NUMBER:=0;
    
   BEGIN
   
      SELECT nvl(sal,0) INTO v_sal FROM emp2 WHERE empno = p_empno;
                v_sal := v_sal + p_raise;
    
      UPDATE emp2 SET sal = v_sal WHERE empno = p_empno;
      
     -- rollback;
      
      commit;
      
      RETURN v_sal;
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
         DBMS_OUTPUT.PUT_LINE('Employee ' || p_empno || ' not found');
         RETURN -1;
      WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE('The following is SQLERRM:');
         DBMS_OUTPUT.PUT_LINE(SQLERRM);
         DBMS_OUTPUT.PUT_LINE('The following is SQLCODE:');
         DBMS_OUTPUT.PUT_LINE(SQLCODE);
         RETURN -1;
         
  END;
  
  
  Thanks in Advance!

**Comment by lwasylow** [comment]
Hi
You cannot use a rollback auto in that scenario as you procedure got a `COMMIT`
Please remove a `COMMIT` from the function and it should work.

**Comment by lwasylow** [comment]
Hi
There is a quite extensive documentation written about `rollback`
http://utplsql.org/utPLSQL/v3.1.10/userguide/annotations.html
Hope that helps
Lukasz

**Comment by PriyankaKeer** [comment]
> Hi
> There is a quite extensive documentation written about `rollback`
> http://utplsql.org/utPLSQL/v3.1.10/userguide/annotations.html
> Hope that helps
> Lukasz

Okay got it. Thanks a lot for quick assistance.
