### ISSUE TITLE
UTPLSQL CLI Error: Detected Oracle driver stuck during Statement initialization after multiple retry

### ISSUE THREAD

**Issue by venkat-kasula** [utPLSQL/utPLSQL#1120]
Hi All, 

When i m trying to execute UTPLSQL CLI , i m getting below error

--------------------------------------
TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Detected Oracle driver stuck during Statement initialization
**WARNING: Caught Oracle stuck during creation of Runner-Statement. Retrying (1)**

--------------------------------------
TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Detected Oracle driver stuck during Statement initialization
**WARNING: Caught Oracle stuck during creation of Runner-Statement. Retrying (4)**

After 4 retries, execution got terminated. Kinldy help me to resolve this issue.

**Comment by pesse** [comment]
Hey @venkat-kasula , can you tell me if and how you were able to resolve the issue?

**Comment by venkat-kasula** [comment]
@pesse  not yet.. i m not able to resolve the issue yet.

**Comment by pesse** [comment]
Duplicate of #1121
