### ISSUE TITLE
Is it possible to use the %suitepath in all reporters ?

### ISSUE THREAD

**Issue by ThisGuenter** [utPLSQL/utPLSQL#1122]
Hi all,
i'm able to call ut_run with the ut_junit_reporter() und provide as parmeter a_paths a suitepath e.g. a_paths => ut_varchar2_list(USER||':my_suitepath'), is this also possible with ut_coverage_cobertura_reporter() and ut_coverage_html_reporter()
Regards Günter

**Comment by pesse** [comment]
Yes.
`a_paths` is independent from the reporters, the suite will just run the defined paths and feed the results to the defined reporter, no matter which one you specified.

**Comment by ThisGuenter** [comment]
Thanks for confirming. I tried, but only the ut_junit_reporter() respect the %suitepath the other reporters show results from all %suitepath's - This is how i call them:

SPOOL ../../../target/tmp/utPLSQL.xml
EXECUTE ut.run(a_paths => ut_varchar2_list(USER||':my_suitepath'), a_reporter => ut_junit_reporter());
SPOOL OFF

SPOOL ../../../target/tmp/cobertura.xml
EXECUTE ut.run(a_paths => ut_varchar2_list(USER||':my_suitepath'), a_reporter => ut_coverage_cobertura_reporter());
SPOOL OFF

SPOOL ../../../target/tmp/cobertura.html
EXECUTE ut.run(a_paths => ut_varchar2_list(USER||':my_suitepath'), a_reporter => ut_coverage_html_reporter(a_html_report_assets_path => '^^HTML_REPORT_ASSETS_PATH'));
SPOOL OFF

**Comment by pesse** [comment]
The mentioned reporters are CodeCoverage reporters, so they will report the coverage of **all** elements, even when only the tests specified in `a_paths` are actually run.
You will have to to limit the coverage scope with the `a_include_objects`, `a_excludee_objects` or `a_coverage_schemes` parameters.
See the documentation for details: http://utplsql.org/utPLSQL/latest/userguide/coverage.html

**Comment by ThisGuenter** [comment]
Thanks Pesse, hoped i would be able to simplify the call to the CodeCoverage reporters, as the list of elements can get quiet large

**Comment by pesse** [comment]
I wonder what you are trying to accomplish.
Feel free to share what you're trying to do - I have a feeling that there might be solutions not of technical nature.

**Comment by ThisGuenter** [comment]
I have several independent components that share one user-schema, i try to separate the unittests on component-level

**Comment by pesse** [comment]
I don't get how coverage fits into that. You can still see the coverage of all the dependent objects from a coverage report over everything. Only thing you don't get is the "overall by coverage %" - but in that case I would question why this information is useful to you.
