### ISSUE TITLE
Bug on issue #1125

### ISSUE THREAD

**Issue by al-hexagon** [utPLSQL/utPLSQL#1126]
**Describe the bug**
https://github.com/utPLSQL/utPLSQL/issues/1125

**Provide version info**
Information about utPLSQL and Database version, 
```sql
set serveroutput on
declare
  l_version varchar2(255);
  l_compatibility varchar2(255);
begin
  dbms_utility.db_version( l_version, l_compatibility );
  dbms_output.put_line( l_version );
  dbms_output.put_line( l_compatibility );
end;
/

19.0.0.0.0
19.7.0

select substr(ut.version(),1,60) as ut_version from dual;
select * from v$version;
select * from nls_session_parameters;
select substr(dbms_utility.port_string,1,60) as port_string from dual;
```

file attached                                                   

**Information about client software**
What client was used to run utPLSQL tests? Was it from TOAD, SQLDeveloper, SQLPlus, PLSQL Developer etc...

SQL Developer with extension for UtPlsql - but this doesn't matter. The output is the same if unit-test run by script or other server / machines

**To Reproduce**
see issue 

**Expected behavior**
covering all lines correctly

**Example code**
see issue

**Comment by al-hexagon** [comment]
[ut3_bug.txt](https://github.com/utPLSQL/utPLSQL/files/6099720/ut3_bug.txt)

**Comment by PhilippSalvisberg** [comment]
duplicates to #1125
