### ISSUE TITLE
PLS-00201: identifier 'UT.EXPECT' must be declared

### ISSUE THREAD

**Issue by bruno5barros** [utPLSQL/utPLSQL#1129]
Hi, 

I hope everyone is well.

I am experiencing this error "Error(18,7): PLS-00201: identifier 'UT.EXPECT' must be declared", I did the installation and I wasn't able to run the test.
Someone knows how to solve it?

Thank you in advance.

Kind regards 
Bruno Barros

![image](https://user-images.githubusercontent.com/67475745/112706739-3cbe1800-8e9e-11eb-8416-6afb037ae932.png)

**Comment by PhilippSalvisberg** [comment]
It looks like utPLSQL has not been installed successfully. 

How did you install utPLSQL (full command line statement)? Which Oracle user did you use for the installation? What error messages did you get? Can you provide some logs? What is the utPLSQL version you've tried to install? What is the version of your Oracle Database?

Thank you.

**Comment by bruno5barros** [comment]
I downloaded the zip and installed using the check update option. I used sys user and my user.
I am using the following versions:
- SQL Developer 20.4.1
- Database 11G
- utplsql_for_SQLDev_1.3.1.zip (href="/utPLSQL/utPLSQL-SQLDeveloper/releases/download/v1.3.1/utplsql_for_SQLDev_1.3.1.zip")

![image](https://user-images.githubusercontent.com/67475745/112717558-78c89b80-8ee5-11eb-9838-ef61ad172470.png)

The version of SQL developer maybe is the problem.

**Comment by PhilippSalvisberg** [comment]
As I mentioned before, I think something went wrong when installing utPLSQL. The issues you have right now are not related to SQLDev. So how exactly have you installed utPLSQL? Can you please post the installation logs here? Thx.

**Comment by bruno5barros** [comment]
Ok, I installed it like I am showing in the picture.

![image](https://user-images.githubusercontent.com/67475745/112719789-9c461300-8ef2-11eb-9f55-5b55e212be30.png)

![image](https://user-images.githubusercontent.com/67475745/112719810-be3f9580-8ef2-11eb-89f9-b1a0a056907e.png)

![image](https://user-images.githubusercontent.com/67475745/112719817-cdbede80-8ef2-11eb-9482-d91be01b3b7e.png)

I did follow these steps, in the end, the SQL developer asks to restart, and its done.

Where I could get the log installation, please?

**Comment by PhilippSalvisberg** [comment]
You installed the SQLDeveloper extension. This is just a client-side component. I'm talking about the core component which needs to be installed in the Oracle Database. See http://utplsql.org/utPLSQL/develop/userguide/install.html . It looks like you have not installed it. Therefore you get errors for `ut.expect`...

**Comment by bruno5barros** [comment]
Great, thanks.
It's Done and working.

**Comment by PhilippSalvisberg** [comment]
Thanks for the feedback. I'm closing the issue.
