### ISSUE TITLE
Is there a way we can execute only few test packages which matches the regular expression?

### ISSUE THREAD

**Issue by PriyankaKeer** [utPLSQL/utPLSQL#1132]
Hi Team, 
Is there a way we can execute only few test packages which matches the regular expression?

I have to execute only few testcases which starts with a specific string, so just wanted to know if we can execute testcases using regular expression.

Thanks in Advance!

**Comment by PhilippSalvisberg** [comment]
No. There are several options to run tests. They are documented here: http://utplsql.org/utPLSQL/develop/userguide/running-unit-tests.html

If this is something you need to do regularly then tagging tests might be the thing you are looking for.

If you are using the SQLDev extension then you can select multiple tests in the navigator and then execute them.

**Comment by PriyankaKeer** [comment]
Hi,
Thanks for the response
What exactly is tagging tests?

**Comment by PhilippSalvisberg** [comment]
http://utplsql.org/utPLSQL/latest/userguide/annotations.html#tags

**Comment by PriyankaKeer** [comment]
> http://utplsql.org/utPLSQL/latest/userguide/annotations.html#tags

Thanks a lot! It seems our issue is sorted now
