### ISSUE TITLE
Execute rights on SYS.DBMS_LOB not granted

### ISSUE THREAD

**Issue by JensKaschuba** [utPLSQL/utPLSQL#1133]
v3.1.10:
Installation fails due to missing execute rights on sys,dbms_lob for installation user.
GRANT EXECUTE ON sys.dbms_lob to <ut3_user>
solves the issue

**Comment by jgebal** [comment]
The DBMS_LOB package is granted to public by default. 
I'm not sure why in your database installation it is not the case. 
I would suggest you reach out to your DBA to check for reasons.

**Comment by barsema** [comment]
I face the same issue.
It is a security best practice to revoke public execute rights on sensitive packages of which  DBMS_LOB is one.

I also don't see a problem with not relying on the public grant.

Please reconsider closing this, the fix is trivial.
