### ISSUE TITLE
Having issues using expect to compare procedure OUT refcursor parameters

### ISSUE THREAD

**Issue by chris-seals** [utPLSQL/utPLSQL#1135]
I have an established code base I'm supporting that has several procedures that return a REFCURSOR. The only way I can typically test this is by assigning a variable, binding the variable, and then printing the variable after procedure execution, but this is tedious and not scalable to many tests.

I've recently found utPLSQL and love it, but I'm struggling in determining how to design a test to see if the REFCURSOR matches another cursor with a straight call at a table.

Older versions had functionality like utAssert.eq_refc_query to compare a refcursor result to a query... [these](http://utplsql.org/utPLSQL/v2.3.1/utassert.html#eq_refc_query) looked hopeful but it seems they are dropped now. 

What's the advisable way to set up testing this situation? This is an example of the manual test I run to ensure my PROC is working.
```
variable rc refcursor;
exec pkg_findinventory.search_by_guid('profile', '8675309', :rc);
print rc;
```

I'd like to compare RC, my actual, to an expected cursor such as 'select * from inventory where guid = '8675309'.. I've tried setting a variable within the tests but that seems a no-go.

Thank you in advance to any suggestions you could provide.

**Comment by PhilippSalvisberg** [comment]
You can compare two refcursors. Here's an example using a standalone expectation:

```sql
set serveroutput on size unlimited
declare 
   c1 sys_refcursor;
   c2 sys_refcursor;
begin
   open c1 for select 1 as col1 from dual;
   open c2 for select 2 as col1 from dual;
   ut.expect(c1).to_equal(c2);
end;
/
```

The output is

```
FAILURE
  Actual: refcursor [ count = 1 ] was expected to equal: refcursor [ count = 1 ]
  Diff:
  Rows: [ 1 differences ]
    Row No. 1 - Actual:   <COL1>1</COL1>
    Row No. 1 - Expected: <COL1>2</COL1>
  at "anonymous block", line 7
```

**Comment by chris-seals** [comment]
Thank you Philipp, I have seen this setup in the documentation, but I'm getting caught in not being able to reference the procedures themselves when setting up my l_actual/l_expected. 

Is something like this possible?

```
declare 
   c1 sys_refcursor;
   c2 sys_refcursor;
begin
   open c1 for pkg_findinventory.search_by_guid('profile', '8675309', :c1); <<<<< this out cursor is what I'd like to analyze
   open c2 for select * from inventory where guid = '8675309';
   ut.expect(c1).to_equal(c2);
end;
/
```

The problem is, I can't do much with that out param cursor aside from printing it as I mentioned before. I'd prefer not to copy out the actual query from inside the pkg as it is quite large. Any way to compare procedure calls in this manner?

Thank you for your patience and suggestions!

**Comment by pesse** [comment]
Does this work?
```
declare 
   c1 sys_refcursor;
   c2 sys_refcursor;
begin
   pkg_findinventory.search_by_guid('profile', '8675309', c1);
   open c2 for select * from inventory where guid = '8675309';
   ut.expect(c1).to_equal(c2);
end;
/
```

**Comment by chris-seals** [comment]
Utilizing `.unordered_columns()` seems to do the trick! Thank you again to both of you.
