### ISSUE TITLE
UTPLSQL Coverage Report is not generated Properly when triggered from Jenkins. It says "Loading ICON" while opening in Browser

### ISSUE THREAD

**Issue by venkat-kasula** [utPLSQL/utPLSQL#1139]
**Describe the bug**
UTPLSQL Dcoker Image is setup on Jenkins & Ran through Jenkins, Execution went well, But when opening Coverage.html report showing "Loading" & Report Is not showing up properly.

Coverage Report Link which is showing error  :https://drive.google.com/file/d/1M8SJKMcZno798kISJWOP1VGn1uT_UbAp/view?usp=sharing

**Provide version info**

```
> ################## utPLSQL cli ###################
> #                                                #
> #   utPLSQL-cli 3.1.8-SNAPSHOT.local             #
> #   utPLSQL-java-api 3.1.8.546                   #
> #   Java-Version: 1.8.0_292                      #
> #   ORACLE_HOME: /usr/lib/oracle/18.3/client64   #
> #   NLS_LANG: null                               #
> #                                                #
> #   Thanks for testing!                          #
> #                                                #
> ##################################################
> 
> Use connection string jdbc:oracle:thin:****/****@10.114.97.90:1521/ORCL
> Successfully connected to database. UtPLSQL core: v3.1.10.3349
> Oracle-Version: 18.0.0.0.0
> Running tests now.
```

**Information about client software**
USed Jenkins Pipeline to trigger the UTPLSQL through DockerImage.

**To Reproduce**
1. Go to Jenkins
2. Click on Run
3. Console Output.. check for Logs
4. Open the coverage.html in Browser.

**Expected behavior**
Browser should open with all Coverage Report.

**Comment by pesse** [comment]
Hi @venkat-kasula,
it looks like your coverage report can not find the folder coverage.html_assets/ (which is located in the same directory as the file coverage.html) where all the additional assets are stored.
This depends on your configuration of Jenkins. Please make sure that you can reach that folder from the location where you open the report.

Cheers,
Sam

**Comment by venkat-kasula** [comment]
@pesse Thnx for the response sam.. Sorry for delay in Looking for your response.
I will look into it & close the issue soon.
