### ISSUE TITLE
UTPLSQL Framwork: Though coverage is displayed in Sonar, unit test numbers are not showing up

### ISSUE THREAD

**Issue by sv00362258** [utPLSQL/utPLSQL#1141]
UTPLSQL Framwork: Though coverage is displayed in Sonar, unit test numbers are not showing up. So enabled debug mode in Sonarqube and did build, it is specifying 'Java CODE Block Indexer' skipped because there is no related file in current project' . I checked UTs and everything is written as mentioned in UTPLSQL document. Any help here would be appreciated

**Comment by lwasylow** [comment]
Can you provide a more information ?
A test used , command executed as well as share sonar properties file and sonar analysis output.

Cheers
Lukasz

**Comment by jgebal** [comment]
Sonar stopped reporting unit tests (counts and details) from some version of sonar server.
We cannot see tests in our own utplsql sonar project too.
This is Sonar decisions. Not sure what was the rationale for it.

**Comment by felipebz** [comment]
Hi,

I found this issue by chance when I was writing a guide on how to import test and coverage data to SonarQube and I think I can take a look at this. I've just tested the import on [my own SonarQube server](https://sonarqube.felipezorzo.com.br/component_measures?id=ut-and-coverage-test&metric=tests&view=list) and on [SonarCloud](https://sonarcloud.io/component_measures?metric=tests&view=list&id=ut-and-coverage-test) and the unit test count is shown correctly. Apparently, nothing changed from the SonarQube side.

**Comment by lwasylow** [comment]
Closed via #1198
