### ISSUE TITLE
Testing using package spec level collections

### ISSUE THREAD

**Issue by MrUrdam** [utPLSQL/utPLSQL#1145]
**Is your feature request related to a problem? Please describe.**
I can not use collection types defined in a package specification. 

**Describe the solution you'd like**
Also allow the collection types from a package specification during ut.expect

**Additional context**
```SQL
DECLARE
  collectionVariable PACKAGE.TYPE_COLLECTION;
BEGIN
  collectionVariable := PACKAGE.TYPE_COLLECTION(1,2);
  ut.expect(anydata.convertCollection(collectionVariable)).to_(have_count(2));

END
```

fails with:
PLS-00201: identifier 'SCHEMA.TYPE_COLLECTION' must be declared
ORA-06612: at "SCHEMA.UT_DATA_VALUE_ANYDATA" line 98
ORA-06550: line 0, column 0:
PL/SQL: Compilation unit analysis terminated
ORA-06512: at "SCHEMA.UT_METADATA", line 278
ORA-06512: at "SCHEMA.UT_DATA_VALUE_ANYDATA", line 70
ORA-06512: at "SCHEMA.UT_DATA_VALUE_ANYDATA", line 114 
ORA-06512: at "SCHEMA.UT, line 33

**Comment by jgebal** [comment]
This is Oracle PL/SQL limitation. 
ANYDATA works only with schema-level types I'm afraid.
Are you able to open a cursor on that package-spec collection type?
```
...
begin
open cur for select * from table(SCHEMA.TYPE_COLLECTION);
...
```
If so, you can use cursor comparison.
If not, the only option is to loop though collection and compare item by item (field by field).

**Comment by MrUrdam** [comment]
Hopefully Oracle will extend the ANYDATA in the future. 
I think they should have done that at the same time they implemented the use of functions defined in a package spec in SQL statements.

I was able to implement my test using cursors only. 
This is ok but does look a bit weird compared to my intended implementation.
Especially for comparisons against a fixed list of items created in the test itself.

**Comment by jgebal** [comment]
As an alternative, use schema level type or use one of predefined types, if you're comparing a simple list of numbers or list of varchars.
