### ISSUE TITLE
Add support for edition based  redefinition

### ISSUE THREAD

**Issue by AlexTM89** [utPLSQL/utPLSQL#1146]
**Is your feature request related to a problem? Please describe.**
We use utPLSQL ver 3.1.7.

When our team start to using oracle edition based redefinition feature, we lost ability of running tests.
When we make schema for framework editioned, we cannot install it without errors.

**Describe the solution you'd like**
We would like to have an ability to install ut plsql into editioned schema and so we can access our tests.

**Additional info**
We cannot access our test because we try to access editioned objects (tests has written in our schema) from non-editioned context (schema where framework installed). After running command "alter user ut enable editions force" in ut schema we have table ut_suite_cache with nested table columns in invalid state. This restrict is by Oracle EBR.

**Comment by jgebal** [comment]
There is another open issue for the same problem:
