### ISSUE TITLE
Is there a way I can run only specific tests (test packages starting with XX%, etc)?

### ISSUE THREAD

**Issue by satyapadala** [utPLSQL/utPLSQL#1148]
When we run ut_runner.run, is there a way we can get it run test packages starting with XX% in a particular schema? Basically, we have a schema called APPS which contains thousands of objects and it takes lot of time to identify the annotations on all these objects.

**Comment by lwasylow** [comment]
Have you considered organized tests into `suites` or `tags` and using them to execute ?
