### ISSUE TITLE
Installation bug, duplicate script call/reference

### ISSUE THREAD

**Issue by dmcghan** [utPLSQL/utPLSQL#1149]
It seems the following line is called twice (see line 166): 
https://github.com/utPLSQL/utPLSQL/blob/75037c8ec46aa280058e047015c9a50a60ec6b0c/source/install.sql#L169

The duplicate generates the following error:
```
ERROR at line 1:
ORA-00955: name is already used by an existing object
ORA-06512: at line 9
```

**Comment by dmcghan** [comment]
Looking closer at `core/coverage/proftab.sql`, I can see it was written as a rerunnable script, so it's interesting that I got the error I did. At any rate, I'm not sure it's being called twice on purpose...

**Comment by jgebal** [comment]
Thanks for reporting this. Fix is on it's way
