### ISSUE TITLE
Error in the User Guide documentation -> Annotations

### ISSUE THREAD

**Issue by VladDr85** [utPLSQL/utPLSQL#1154]
Error in the User Guide documentation -> Annotations
http://utplsql.org/utPLSQL/latest/userguide/annotations.html
Section "Aftertest"
Written   "When multiple --%aftertest procedures are defined for a test, all of them will be executed before invoking the test."
Correctly "When multiple --%aftertest procedures are defined for a test, all of them will be executed after invoking the test."

**Comment by jgebal** [comment]
Thank you for reporting it
