### ISSUE TITLE
Gather Coverage Report for Package functions separately

### ISSUE THREAD

**Issue by RayenMh** [utPLSQL/utPLSQL#1159]
Hi all.

I have a package that contains almost 100 functions.
I create a test package with only 1 function (that execute the 100 functions - i only need the coverage) 

after executing the test package. I get only 1 entry in my html_coverage report that indicate the overall package coverage.

I want to have a solution to get several entries in my html_coverage report : i want to have the coverage % for every single function of the 100 functions available of the package.

I'm using this command using utplsql-cli and i can use an altyernative using ut.run via plsql:
`utplsql run user/userpwd@tnsname -p=example_package -include=PKG_RULES  -f=ut_coverage_html_reporter -o=coverage.html`

the pkg_rules contains 100 functions.
the result in the coverage.html file is the overall %.

![image](https://user-images.githubusercontent.com/48438869/140656120-fbd52efb-a2be-47d1-b741-6c23bba0d22f.png)

is there a way to include objects like this : [Schema_name.][Package_Name.][Function]

any idea?

**Comment by jgebal** [comment]
Hi @RayenMh 
You can click into the package in HTML report to see the coverage on each line of the code.
In Oracle database the package is a compilation unit and coverage is reported at program unit level.

You would need to do one of two:
- ask Oracle to add that feature (coverage at package.procedure level)
- create functions as standalone database objects 
In first case you will not get it fast (if ever)
In second case, I think it's incorrect to move away
from packages for standalone functions. Packages let you organize your code better.

Why do you need coverage on individual functions? What problem are you trying to solve?
A bit more context could help me give you some alternatives.
