### ISSUE TITLE
Multiple Installation cannot completly overwrite the old installation

### ISSUE THREAD

**Issue by PhilippDahlem** [utPLSQL/utPLSQL#1189]
**Describe the bug**
While i was trying to reinstall a newer Version of UTPLSQL ive read in the following documentation (http://utplsql.org/utPLSQL/v3.0.1/userguide/upgrade.html) that the Installation is a total rewrite of the current system.
Unfortunately it was not possible to install over the old version, becasue there where objects beeing dropped that were still cross referenced by other objects , which lead to to an unsuccesful installation.

**Provide version info**
Version 3.0 has been use to overwrite the older Version.
```sql
The command i used in SQL Plus i used to isntall:
@install
which led to the error
**Information about client software**
SQL Plus

**To Reproduce**
Steps to reproduce the behavior:
Try to install over an existing Installation

**Expected behavior**
A compelte full installation of UT PLSQL

Is there currently a way to keep Test-Data and Cases when overwriting an existing installation?

**Comment by PhilippDahlem** [comment]
I was upgrading from 2.x to the newest 3 Version.
The issue i had was, that the during the isntallation there were a set of types who couldnt be deleted due to beeing referenced.

So what i did was to remove all the old files with the unstill_all_objects.sql and then install the newest Version.

We didnt have any Test created so the loss of previous data was not of concern but for the future it will be.

I dont quite get how oyu can isntall over another installation, since it didnt work from 2.x to 3.0.

Can you overwrite existing Installations of the Same Version?

**Comment by lwasylow** [comment]
Hi @PhilippDahlem, the v2 and v3 are two different products. There is no way currently two install v3 over v2 and there is no bridge between them. Tests in v2 will not with v3 as they are implemented different way.
You have to remove old installation and treat a v3 as new product.
Hope that helps.

**Comment by jgebal** [comment]
Hi @PhilippDahlem 
You should really install utPLSQL v3 into separate schema than utPLSQL v2.
There is even a "bridge" solution that allows running utPLSQL v2 tests with utPLSQL v3.
I didn't look into that recently as not many of our users are still on version 2.x.

Please look into project: https://github.com/utPLSQL/utPLSQL-v2-v3-migration

In most of DB configurations you would have:
- utPLSQL v2 living in it's own schema
- test packages living side by side in schema(s) along production (tested) code

If that is the case in your installation, you should be able to easily install utPLSQL v3 into separate schema and use migration utility to start running v2 test packages with v3 test-runnner.

**Comment by PhilippDahlem** [comment]
Thank you [lwasylow](https://github.com/lwasylow) and [jgebal](https://github.com/jgebal) for your quick responses.

This informations is very helpful.
I am going to proceed to setup a diffrent schema for my unit tests and leave the isntallation of v2 or v3 in its own schema so there will be no confusion.

As far as i understood even i want to reinstall a version 3 my Test-Files and Cases wont be touched if they are in a separate schema. That would be ideal.

Kind regards and thank you very much once again 🛩️

**Comment by PhilippDahlem** [comment]
Ive also just verified that ive also upgraged  from Verison3.x to the latest Version and got the same kind of error while executing the "isntall.sql" in SQL Plus.
There are still Types that can not be dropped due to references.

The other Question that i have now is, is there meta data that gets lost when you drop all objects and reinstall the newest version or can you separate all the configurable meta data somewhere else?

**Comment by jgebal** [comment]
Version 3 of utPLSQL is toatlly transportable. It doesn't really rely on any frameworks-specific meta-data.

The concept behind utPLSQL v3 is different than behind v2. This is a sign of time as now almost every major project should use some sort of CI (Continuous Integration) server for their testing.
In the era of DevOps and CI/CD, we support reporting of test runs **outside** of database. 
So you can run your tests today in one DB and tomorrow in another and it really doesn't matter for the framework.

Also, there is no need to register unit tests within the framework anymore.
All tests are automatically recognized by framework by utPLSQL annotations placed in unit test package specification.

If you're used to using utPLSQL v2, you will find utPLSQL v3 a whole new experience.

**Comment by jgebal** [comment]
About your problem:
>There are still Types that can not be dropped due to references.

I would really need more details on this. Are you following the install/uninstall instructions to the letter?
If you could provide script output for both install and uninstall scripts, that would definitely help me help you.

**Comment by PhilippDahlem** [comment]
Hello, i would like to catch up on the topic again.

As of right now i cant provide anymore Details to my issue, cause i cant reinstall but
what i did basicly was to try to reinstall the latest utplsql Version over an existing 3.xx Version.

The Problem i ran into was that first my user was missing grant create context
and the second problem was that the reinstall failed cause the script cant drop types that are referenced by other objects.

So what i did was to drop all the Objects first and then install again. I dropped everything via the "uninstall_all.sql" and reinstalled with "install.sql".

I also would like to know which tables hold critical information like overall configuration of UTPLSQL.

What i want to achieve is a way to reinstall utplsql with the same configuration and settings plus my unit tests.
It would be great if any of you could provide me with the information which tables are the most important and how to transfer them to other plattforms without losing anything.

So far i know that you can install the UTPLSQL in a separate schema than the unit test. What i want to know is which tables are essential that hold the whole configuration in general.

**Comment by lwasylow** [comment]
Ho
So short answer is there are none. All the "configuration" is done in test package as a annotation. You can safely go ahead and reinstall utplsql.
One issue is if your tests are installed inside ut3 schema then make sure you copy them over.

**Comment by jgebal** [comment]
I confirm what was mentioned by @lwasylow 
utPLSQL framework is safe to remove & clean install.
It will detect and run all the tests that are already installed in the database.
No need to backup/restore any configuration. In that regard utPLSQL itself is stateless.
There are cache tables and temporary tables. Those are automatically populated by framework.

So  as long as your TESTS are safe in other schema, clean install (drop utPLQL user or all of framework objects) does no harm.
