### ISSUE TITLE
Test execution data of utPLSQL project not showing on SonarCloud

### ISSUE THREAD

**Issue by felipebz** [utPLSQL/utPLSQL#1198]
Recently I saw [this comment](https://github.com/utPLSQL/utPLSQL/issues/1141#issuecomment-1034603616) saying that the unit test data isn't showing on your SonarCloud project, then I decided to investigate this issue further and I would like to discuss what's the best way to fix it.

Just for reference, this is how the [SonarCloud panel](https://sonarcloud.io/component_measures?metric=tests&id=utPLSQL) looks like now:

![image](https://user-images.githubusercontent.com/13829/156276810-917bde36-3182-4e8c-8369-599da329aa98.png)

And how it should look like:

![image](https://user-images.githubusercontent.com/13829/156276739-209e3bd2-95da-4f48-8203-52a4fb679be0.png)

I saw that the `utplsql-cli` is executed using the user `ut3_test_helper`, but the unit tests are being compiled on users `ut3_tester` and `ut3$user#` and the option `-owner` for the test files is being omitted (line 10):

https://github.com/utPLSQL/utPLSQL/blob/b4d72e391f2e7f5d920ec08744a30431ef201027/test/run_tests.sh#L7-L11

When this option is omitted and there's no other mapping rule to identify the owner of a file by its path, the `ut_file_mapper` package assumes that the owner is the user running the tests, which is the user `ut3_test_helper`: 

https://github.com/utPLSQL/utPLSQL/blob/b4d72e391f2e7f5d920ec08744a30431ef201027/source/core/ut_file_mapper.pkb#L102-L105

But actually the `ut3_test_helper` doesn't own any unit test and, as result, the `test_results.xml` file generated by `ut_sonar_test_reporter` doesn't contain any file path. This is the reason that the unit test data isn't being uploaded to SonarCloud.

The log of the "SonarCloud Scan" step on the GitHub Actions ([example](https://github.com/utPLSQL/utPLSQL/runs/5353130611?check_suite_focus=true)) also shows this, because the files aren't mapped correctly:

```
INFO: Test execution data ignored for 55 unknown files, including:
utplsql.ut3_tester.core.test_ut_utils
utplsql.ut3_tester.core.test_ut_test
(....)
```

One way I found to fix this issue without any changes to the utPLSQL code is executing the `utplsql-cli` twice, one for each schema, like:

```
utPLSQL-cli/bin/utplsql run ${UT3_TESTER_HELPER} (...)  -p='ut3_tester' -test_path=test -owner='ut3_tester'
utPLSQL-cli/bin/utplsql run ${UT3_TESTER_HELPER} (...)  -p='ut3$user#' -test_path=test -owner='ut3$user#'
```

But this would required some other changes to the build pipeline because the generated reports would also be duplicated.

Another alternative, that makes more sense to me, is to **not** assume any default value for the file owner on `ut_file_mapper` and change the `ut_file_mapping` usages ([example](https://github.com/utPLSQL/utPLSQL/blob/develop/source/reporters/ut_sonar_test_reporter.tpb#L35)) to compare the owner only if it's present. With this change, if there's no owner defined on the object-to-file mapping rules, the code will compare only the object name and object type to find the corresponding file, which should be good enough for most situations.

What do you folks think about it?

**Comment by lwasylow** [comment]
I think the CLI should resolve all filepath under `test_path` however the regex is possible not right `gc_file_mapping_regex        constant varchar2(100) := '/(((\w|[$#])+)\.)?((\w|[$#])+)\.(\w{3})$';` and we need to pass some extra options for
```
  -regex_expression="pattern"
  -type_mapping="matched_string=TYPE[/matched_string=TYPE]*"
  -owner_subexpression=subexpression_number
  -type_subexpression=subexpression_number
  -name_subexpression=subexpression_number
``` as per https://github.com/utPLSQL/utPLSQL-cli
I will have a play.

Ideally if we can avoid running twice would be ideal, or changing default behaviour.

**Comment by jgebal** [comment]
I take this back.
We need to rename user `UT3#USER$` to `UT3_USER` 
Unix doesn't like the special chars in folder names and for some reason utPLSQL-cli doesn't pass the paths to runner when the directory is named `UT3#USER$`

**Comment by jgebal** [comment]
The parameters that seem to work for me locally were:
```
  -regex_expression="test/(\w+)(/(\w+))*/(\w+)\.(.{3})$" \
  -owner_subexpression=1 \
  -type_subexpression=5 \
  -name_subexpression=4 \
```

I have tested it locally with UT_DEBUG_REPORTER to see what are the file mappings generated by utPLSQL file mapper.
```
utPLSQL-cli/bin/utplsql run ${UT3_TESTER_HELPER}/${UT3_TESTER_HELPER_PASSWORD}@${CONNECTION_STR} \
-source_path=source -owner=ut3_develop \
-p='ut3_tester.test_file_mapper.default_mappings,ut3$user#.test_be_greater_or_equal.actual_date_greater' \
-test_path=test -c \
  -regex_expression="test/(\w+)(/(\w+))*/(\w+)\.(.{3})$" \
  -owner_subexpression=1 \
  -type_subexpression=5 \
  -name_subexpression=4 \
-f=ut_sonar_test_reporter         -o=test_results.xml \
-f=ut_debug_reporter              -o=debug.log \
-f=ut_documentation_reporter      -o=test_results.log -s
```

**Comment by jgebal** [comment]
@felipebz 
Thanks for bringing this to our attention.
I have wrongly assumed that the issue with test-results not showing in sonar was related to sonar changes, while in fact it was related to tests refactoring that was done some time ago.

I've managed to fix the issue by change to how file mapping is interpreted (owner extracted from file path).
