### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#12]
Similar to #11, I think we should define how the code is documented. The best thing I've found to produce nice output is [NaturalDocs](http://www.naturaldocs.org/). It generates pretty web pages and the comments in the code are easily readable.

Has anyone found anything better?

**Comment by jgebal** [comment]
I think there is s need for 2 docs.

API doc - for developers - describing how things interact - can be
generated from code comments.

User doc - working examples of usage for particular features of v3

**Comment by DDieterich** [comment]
Added some Wiki pages with definitions.  A common terminology in context will help me communicate better.

Did some editing on the v2 features pages.

Would like to add the ER-Diagram I created for the current V2 along with the example repository data from the example test and the v2 call tree examples.  I am looking for a place to put them.

**Comment by rlove** [comment]
I agree with @jgebal.

Just reading the NaturalDocs home page it looks like it may do something similar to [pldoc's](http://pldoc.sourceforge.net/maven-site/)   But as far as on page advertising (no actual usage)  NaturalDocs looks like a better choice.   As it can do both API and Non API documentation.

**Comment by rlove** [comment]
I have now played with Natural Docs.    It's really easy to use, I was able to document a simple pl/sql project quickly, as was able to setup docs.    Using text file processing features I was able to write documentation that was not associated with the code.

**Comment by jgebal** [comment]
Great news @rlove 
So natural doc could go as a standard for the project.

**Comment by Shoelace** [comment]
i have an initial implementation of naturaldocs on my branch https://github.com/shoelace/utplsql/tree/travis_ci_v3

which can be generated with 
```cd NaturalDocs && .\NaturalDocs -i ..\code -o HTML ..\docs\api -p ..\docs```

ive put teh natural docs config files in .\docs and ithe api gets generated into .\docs\api

**Comment by jgebal** [comment]
Hi @Shoelace 
I just had a look at the NaturalDocs you've prepared. It looks nice.
Any plans to move on with v3?

**Comment by DDieterich** [comment]
Jacek,

   We just finished unpacking from the move.  It is good to be back.

   I am a little confused about https://github.com/utPLSQL, so I am not
sure how to help here.

   I was planning to start unit test development on the code at
https://github.com/DDieterich/utplsql_lite.  I am using this other location
to continue the refactoring effort I started.  I am not trying to head-off
in a different direction.  I am just trying to keep moving forward on
something.

   If I remember correctly, we seemed to agree that refactoring is needed.
However, we did not agree on a direction.

   Lots of good work being done by everyone.

Duane

**Comment by DDieterich** [comment]
Yikes!!!  I didn't watch closely.  This is a documentation thread,  Forgive my out-of-place post.  Duane

**Comment by rlove** [comment]
Tasks #58 and #59 have been created to deal with version 3 documentation Framework and Publishing.      This will enable the flushing out of the documentation which will result in additional tasks later on.  

Closing this discussion as it's now redundant.
