### ISSUE TITLE
 ut.run is not declared

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1206]
1-Error1
Identifier UT.RUN must be déclared
2- Error2:
I can't create the template for test, when i click in the button "Create code template",  nothing happens

<img width="516" alt="Erreur" src="https://user-images.githubusercontent.com/98126863/165462845-1b39f99d-901e-42f8-a701-75e6d9b68f4b.PNG">
<img width="528" alt="Erreur2" src="https://user-images.githubusercontent.com/98126863/165462849-8b76c638-88b0-4eb1-9ff4-ce810821829e.PNG">

**Comment by lwasylow** [comment]
Hi Lydia
These seems to be two separate issues.
Second one is for plugin, could you please create it in https://github.com/utPLSQL/utPLSQL-SQLDeveloper

As for the first one. Can you please share more details? There is a template for the issue to fill to help us with resolving the issue. 
Can you also run the sql:
```
select * from all_synonyms where owner=<your utplsql install owner>
```
 Thanks

**Comment by jgebal** [comment]
Hi @LydiaAzzoug 
Do you have utPLSQL framework installed **in database**?
Installing utPLSQL-SQL-Developer extension is not all.
It seems to me that utPLSQL framework is not installed in the database.

Can you confirm that utPLSQL is installed?
https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/install.md

**Comment by LydiaAzzoug** [comment]
@jgebal you're right, I didn't install it but I tried earlier but I didn't really understand how to do it
<img width="673" alt="E2" src="https://user-images.githubusercontent.com/98126863/165498047-5b4e851b-6d49-48e1-b7a8-574a635deb39.PNG">

**Comment by lwasylow** [comment]
Hi Lydia
Install needs to be executed as `sysdba`.
So you have to connect to database for example
`sqlplus user/password@dbname as sysdba`
or
`sqlplus / as sysdba`

This are just example of connection.
Hope that helps.
