### ISSUE TITLE
Execution of 0 test

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1210]
**Is your feature request related to a problem? Please describe.**
I installed the framework and I executed in the same schema (saving the tests in the same database), and all of them work well and they return the correct results but when I tried to execute in another schema (another user who has all the rights) to separate the test packages, I had the following result

**Describe the solution you'd like**
I think that it is necessary to make the link between this user and the database

**Additional context**

<img width="309" alt="Capture" src="https://user-images.githubusercontent.com/98126863/168253482-ecb188d3-755c-4a01-b446-9dbf98bdf778.PNG">

**Comment by lwasylow** [comment]
Hi Lydia, calling test by suitepath require specifying schema e.g.`owner:testsuite` if the `owner ` is omitted, it will default to `current user`.
First make sure that tests you created are deployed in the schema you connect to, otherwise please specify owner as above in suitepath.
Cheers Lukasz

**Comment by LydiaAzzoug** [comment]
Hi, thank you for your feedback
The tests that i created are deployed in the shema i connect to, but I'm not sure I understand your solution.
<img width="993" alt="Capturee" src="https://user-images.githubusercontent.com/98126863/168540958-06e67c5e-1439-4cf5-bb8e-fdaa37b27770.PNG">

**Comment by jgebal** [comment]
Your SUITE and SUITEPATH annotattions are not correctly located.

You see, there are two placements of annotations in utPLSQL.
- Procedure annotations (those are in lines directly before procedure name)
- Package annotations (not associated with any procedure)

So your package is not a valid utPLSQL SUITE as utPLSQL cannot recognize the `--%suite` annotation that is associated with `procedure REF_PORTEUR_IN_CEMACARTE`

To make the package work do the following change:
```sql
create or replace package t3_API_SPEC_TOOLS is

  --%suite
  --%suitepath(PPWERCARD_TEST)

  --%test
  --%disabled
  procedure REF_PORTEUR_IN_CEMACARTE;


```

The most important difference is an empty line between package level annotations and the procedure-specific annotations.


See [this section of annotations documentation](https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/annotations.md#package-level-annotations) for details.


Hope this helps
