### ISSUE TITLE
Error :"UT.EXECT" must be declared

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1212]
I installed the ut3 user on the MBED1 database, and I created a small package called ADDITION in the same database. But after the generation of the test, I have an error during the compilation
**the code:
create or replace PACKAGE BODY ADDITION is

  function test_1 (parameter_1 number,parameter_2 number) return number AS
  BEGIN
      return parameter_1 + parameter_2;
         
  END test_1;

END ADDITION;

<img width="967" alt="cap" src="https://user-images.githubusercontent.com/98126863/170261248-745f2303-63cb-40f9-a57c-140233818be5.PNG">
<img width="867" alt="testAdd" src="https://user-images.githubusercontent.com/98126863/170261274-fddde016-be20-418e-ac4a-0989654ff31d.PNG">

**Note**
> Please do not create issues for generic SQL or PL/SQL questions. There are other forums and communities to help you with those. See [ASKTom](https://asktom.oracle.com) for example.

**Want to discuss**
If you want to discuss your issue, join [our SLACK chat](https://join.slack.com/t/utplsql/shared_invite/zt-d6zor80g-WWqAhbLWioJZUtLYeXetzA).

**Comment by lwasylow** [comment]
Hi Lydia
Looks like installation was not properly done or utPLSQL ia nit installed at all. There should be a public synonym.
Please verify installation.

**Comment by LydiaAzzoug** [comment]
Hello, it can't be a problem with the installation because I already have it on another database and it worked so I think it's either a problem of rights or a synonym

**Comment by lwasylow** [comment]
Hi Lydia
Each database require its own installation.
Cheers Lukasz

**Comment by jgebal** [comment]
@LydiaAzzoug 
utPLSQL consists of packages & tables. It is not a **client software** like TOAD or SQL Developer and it does not require installation on developer (client) machine.
It is installed **into database** and so for each DB that you want utPLSQL to be available on, you will need it to be installed there.

**Comment by jgebal** [comment]
@LydiaAzzoug 
Can you check that the following SQL queries execute successfully?
```
select ut.version() from dual;
select ut3.ut.version() from dual;

```

**Comment by LydiaAzzoug** [comment]
I ran them on UT3 not on MBED1

**Comment by jgebal** [comment]
Can you also try the following block and send the outputs?

```sql
set serveroutput on
declare
  l_actual   integer := 1;
  l_expected integer := 1;
begin
  ut.expect(l_actual).to_equal(l_expected);
end;
/
```

Also run the following 2 queries and show the results:
```sql
select * from all_synonyms where table_owner = 'UT3';
select * from all_objects where owner = 'UT3';
```

**Comment by LydiaAzzoug** [comment]
@jgebal in MBED1 database?

**Comment by LydiaAzzoug** [comment]
**_on MBED1 database:_**

<img width="866" alt="MBED1_requet1" src="https://user-images.githubusercontent.com/98126863/170988147-4d1a4f47-02cc-4bcb-8f21-d4cf604d82a9.PNG">
<img width="716" alt="MBED1_requete2" src="https://user-images.githubusercontent.com/98126863/170988151-ff3ae790-b84d-4491-91f0-6d14cf5064b0.PNG">
<img width="818" alt="MBED1_requete3" src="https://user-images.githubusercontent.com/98126863/170988183-24f85212-be14-4c34-9808-9abb7dd2439a.PNG">


_**On UT3:**_
<img width="748" alt="UT3_requete1" src="https://user-images.githubusercontent.com/98126863/170988309-ba312224-b75b-4cb7-a1d3-503476085601.PNG">
<img width="761" alt="UT3_requete2" src="https://user-images.githubusercontent.com/98126863/170988313-c4a73591-8677-4d2d-8f3a-2f2cb78f0a9d.PNG">
<img width="818" alt="UT3_requete3" src="https://user-images.githubusercontent.com/98126863/170988393-756d0fa5-972f-4438-b1a0-de7e36d8367c.PNG">



Thank you in advance

**Comment by jgebal** [comment]
What instructions did you execute to Install utPLSQL onto your  MBED1 and MBED2 databases?

It seems that you did not install public synonyms.

**Comment by LydiaAzzoug** [comment]
i ran these two queries
1) sqlplus username/password@database @create_synonyms_and_grants_for_public.sql ut3   
2) sqlplus  username/password@database @create_synonyms_and_grants_for_public.sql ut3

I managed to solve the problem earlier but now I have this
<img width="910" alt="erreur00" src="https://user-images.githubusercontent.com/98126863/171175303-a04b6feb-ac3b-415b-89a1-aa497850bba4.PNG">

**Comment by LydiaAzzoug** [comment]
2) •	Sqlplus username/password@database @install_headless.sql

**Comment by jgebal** [comment]
Please share the full output from the script execution as text, not as screenshot.

Thank you

**Comment by LydiaAzzoug** [comment]
Sorry for this late response

[Java Printing.pdf](https://github.com/utPLSQL/utPLSQL/files/8862740/Java.Printing.pdf)

Thank you

**Comment by jgebal** [comment]
Looking at the reply you have provided it seems there is nothing wrong with utPLSQL installation.
The test packages can be compiled and can be executed with `ut.run` procedure from `POWERCARD` schema in your database.


```
Sortie de script 1/1
Elément Package CHECK_UT_INSTALL compilé
Elément Package Body CHECK_UT_INSTALL compilé
check_ut_install
 do_check [,014 sec] (FAILED - 1)
Failures:
 1) do_check
 Should fail here ; utPLQL version is: v3.1.12.3589 ; Cconnected user  at "POWERCARD.CHECK_UT_INSTALL.DO_CHECK", line 4 ut.fail( 'Should fai
Finished in ,016527 seconds
1 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)
Procédure PL/SQL terminée.
FAILURE
 Actual: 1 (number) was expected to equal: 2 (number)
 at "anonymous block", line 2
Procédure PL/SQL terminée.
```


Perhaps there is something wrong when running utPLSQL with SQLDeveloper plugin.
Can you describe step-by-step how you run utPLSQL from SQLDeveloper schema browser?
Were do you click to run your tests?

Are you doing something similar to this?
![utPLSQL-run](https://user-images.githubusercontent.com/1398171/172767861-6ec482fd-d7b2-4e68-b8fa-ed97a619e11f.gif)

You can do it in French if that is more convenient for you and then translate it using some online translator service like google-translate.

**Comment by LydiaAzzoug** [comment]
**Clicking f5 gives this output:**

Elément Package CHECK_UT_INSTALL compilé
Elément Package Body CHECK_UT_INSTALL compilé

check_ut_install
  do_check [,007 sec] (FAILED - 1)
 
Failures:
 
  1) do_check
      Should fail here ; utPLQL version is: v3.1.12.3589 ; Cconnected user is: POWERCARD
      at "POWERCARD.CHECK_UT_INSTALL.DO_CHECK", line 4 ut.fail( 'Should fail here ; utPLQL version is: ' || ut.version() || ' ; Cconnected user is: ' || user  );
       
Finished in ,008895 seconds
1 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)
 


Procédure PL/SQL terminée.

FAILURE
  Actual: 1 (number) was expected to equal: 2 (number)
  at "anonymous block", line 2


Procédure PL/SQL completed

**Comment by jgebal** [comment]
So utPLSQL installation works correctly.

Do you have any other issues?

**Comment by LydiaAzzoug** [comment]
Hi,
I don't have the same error now. I put you a screenshot of the execution result (it gives me no failures even if the result is false 1+1=2 and not 1)
<img width="903" alt="c" src="https://user-images.githubusercontent.com/98126863/173795049-b8784fcb-67ae-4f38-9211-6381087ab5b0.PNG">

Thank you in advance

**Comment by jgebal** [comment]
The test is clearly disabled.
The grey icon in the window indicates it.
![image](https://user-images.githubusercontent.com/1398171/174168575-8625ce24-9d06-49db-a7f9-59facc7515a5.png)

A test cannot fail when it is disabled.
Test is skipped (not executed) and so the test result is not defined.
