### ISSUE TITLE
utPLSQL with TOAD

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1213]
Heloo! is it possible to use utplsql on toad? if yes,  Can you please help me with some steps or documentation that I can refer to? thanks a lot for your help in advance!
**Want to discuss**
If you want to discuss your issue, join [our SLACK chat](https://join.slack.com/t/utplsql/shared_invite/zt-d6zor80g-WWqAhbLWioJZUtLYeXetzA).

**Comment by lwasylow** [comment]
Hi utPLSQL is a database software. It can be used by any cli or gui that access database.
For any specific plugin implementation you have to check with software vendor or plugins.

**Comment by jgebal** [comment]
TOAD has some UI on top of utPLSQL.
The trouble is that it only works with one specific version of utPLSQL as far as I remember.

https://www.quest.com/video/introducing-utplsql-unit-test-integration-in-toad-for-oracle-8141033/

Having that said, as @lwasylow  said, utPLSQL can be used from any Oracle-SQL compliant IDE (TOAD; SQLDeveloper; PL/SQL Developer; DataGrip; etc. )

**Comment by LydiaAzzoug** [comment]
Thank you so much
