### ISSUE TITLE
Detect unit test failures

### ISSUE THREAD

**Issue by jeffreykemp** [utPLSQL/utPLSQL#1214]
**Is your feature request related to a problem? Please describe.**

We want to run our unit tests as a final step in our automated build scripts, and cause the build to be marked as "failed" if any unit test fails. Our system marks the build as "failed" if it raises an unhandled exception.

**Describe the solution you'd like**

Provide an API method to get a count of failures from the time the unit tests were run.

e.g. so we can execute something like this:

    exec ut.run;

    declare
        l_fail_count number;
    begin
        l_fail_count := ut.failed_count;
        if l_fail_count > 0 then
            raise_application_error(-20000, 'Installation fail: ' || l_fail_count || ' unit test(s) failed');
        end if;
    end;
    /

**Describe alternatives you've considered**

At the moment I execute the unit tests in a query, and search for the "FAILED" key word in the output.

    declare
        l_fail_count number := 0;
    begin
        for r in (
            select column_value o from table(ut.run)
        ) loop
            dbms_output.put_line(r.o);
            if r.o like '%(FAILED %' then
                l_fail_count := l_fail_count + 1;
            end if;
        end loop;
        if l_fail_count > 0 then
            raise_application_error(-20000, 'Installation fail: ' || l_fail_count || ' unit test(s) failed');
        end if;
    end;
    /

---

BTW: the link from the github issue template (below) is no longer active and probably should be removed.

> If you want to discuss your issue, join [our SLACK chat](https://join.slack.com/t/utplsql/shared_invite/zt-d6zor80g-WWqAhbLWioJZUtLYeXetzA).

**Comment by lwasylow** [comment]
Hi @jeffreykemp 
I think its looks like a custom reporter that you could write.
Other option I can think of is use one of xml reporters for example junit, select output into xmltype and use xml query?
Thanks Lukasz

**Comment by jgebal** [comment]
Hi @jeffreykemp 
Are your automated build scripts running on any CI/CD server?
Are you running the scripts from shell (bash/powershell/cmd)?
If so, you could leverage [utplsql-cli](https://github.com/utPLSQL/utPLSQL-cli/blob/develop/README.md) instead of writing your own script. This will make it much easier and will allow for greater flexibility like using multiple reporters.


That would be my recommended approach to be honest.

If you really want to use SQL script, you could use `ut_runner.run` procedure.
It is mentioned in [documentation](https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/running-unit-tests.md#ut_runnerrun-procedures)

```
--main test run 
declare
  l_reporter      ut_documentation_reporter := ut_documentation_reporter();
begin
  l_reporter.set_reporter_id( 'd8a79e85915640a6a4e1698fdf90ba74' );
  l_reporter.output_buffer.init();
  ut_runner.run (ut_varchar2_list ('ut3_tester','ut3_user'), ut_reporters( l_reporter ), a_fail_on_errors => true );
end;
/

-- test results report consumer ( can be a separate session )
set arraysize 1
set pagesize 0

select * 
  from table(
         ut_documentation_reporter()
           .set_reporter_id('d8a79e85915640a6a4e1698fdf90ba74')
           .get_lines()
  );
```

**Comment by jeffreykemp** [comment]
Thanks @jgebal , I adapted it to this which suits us fine (running this in sqlplus via jenkins):

```
declare
    l_reporter ut_documentation_reporter := ut_documentation_reporter();
begin
    ut_runner.run(ut_varchar2_list(), ut_reporters(l_reporter),
        a_fail_on_errors => true
    );
    l_reporter.lines_to_dbms_output();
exception
    when others then
        if sqlcode = -20213 /* Some tests failed */ then
            l_reporter.lines_to_dbms_output();
        end if;
        raise;
end;
```

**Comment by jgebal** [comment]
With utplsql-cli you could publish test results in JUnit format on Jenkins using [JUnit plugin](https://plugins.jenkins.io/junit/)

That gives much better overview of failed tests (if any) as well as info on test duration (slow tests) etc.

```
utplsql run user/pass@host:port/sid \
-f=ut_junit_reporter              -o=junit_test_results.xml \
-f=ut_tfs_junit_reporter          -o=tfs_test_results.xml \
-f=ut_documentation_reporter      -o=test_results.log -s
```
You'd get output into 3 files + output into screen.
You'd also get results to screen in real-time (not after entire test-run is finished)
