### ISSUE TITLE
test not found

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1215]
Hi everyone 
<img width="920" alt="Erreur_User" src="https://user-images.githubusercontent.com/98126863/171381434-6fd491dd-126b-43c6-a123-1d74464a3151.PNG">
**Is your feature request related to a problem? Please describe.**
TEST NOT FOUND 0/0 
THE PACKAGE "ADDITION" is in MBED1 DATABASE and the test is in an other scheme which is "MBED1_TEST"

**Describe the solution you'd like**
i think that the problem is with the grant and annotations

**Script:**
create or replace package test_addition is

        -- generated by utPLSQL for SQL Developer on 2022-06-01 11:44:40

        --%suite(ut3)
        --%suitepath(MBED1_TEST)

        --%test
        --%disabled
        procedure test_1;

end test_addition;

create or replace package body test_addition is

        -- generated by utPLSQL for SQL Developer on 2022-06-01 11:44:40

        --
        -- test test_1
        --
        procedure test_1 is
                l_actual   integer := 0;
                l_expected integer := 1;
        begin
                -- arrange

                -- act
                -- addition.test_1;
                l_actual:=addition.test_1(1,2);
                -- assert
                ut.expect(l_actual).to_equal(l_expected);
        end test_1;

end test_addition;

Thank you in advance

**Comment by jgebal** [comment]
The installation was done incorrectly.
The tables of `UT3` user live in `UT_DATA` tablespace but user UT3 has no privileges to allocate space in that tablespace.

As the [ORA-01950 error suggests](https://stackoverflow.com/questions/21671008/ora-01950-no-privileges-on-tablespace-users), user `UT3` does not have privileges on that tablespace.

Whoever was doing installation of UT3 framework, failed to do it correctly.
Please correct the generic error.
One way to do this would be to execute:
`ALTER USER UT3 quota unlimited on UT_DATA;`
