### ISSUE TITLE
ut_realtime_reporter must be declared

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1217]
Hi, 
I ran unit test on toad  but it gave me an error which is as follows: "ut_realtime_reporter must be declared"

Thanks for your help
<img width="633" alt="Capture" src="https://user-images.githubusercontent.com/98126863/177551185-05f3313e-28ed-49b5-a3ca-94c8bef69eca.PNG">

**Comment by pesse** [comment]
Which version of utPLSQL do you have installed on the database?

**Comment by LydiaAzzoug** [comment]
3.1.12

**Comment by pesse** [comment]
Does running the following statement from TOAD give you a result?

```sql
select * from table(ut.run('POWERCARD.TEST_ADDITION'))
```

**Comment by pesse** [comment]
So utplsql works fine - I'd say it's a TOAD issue.

**Comment by LydiaAzzoug** [comment]
I think so too, I'll try to update Toad to get the latest version.


Thank you
