### ISSUE TITLE
When running examples one by one, the cache does not get invalidated

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#122]
When running examples one by one in following way:
- create test package 1
- execute test 1
- drop test package 1
- create test package 2
- execute test 2
- drop test package 2

The test package 2 is not visible, as the test takes sub-second to execute.

**Comment by jgebal** [comment]
I'm not sure if this is a real use-case issue, but it makes it hard to keep examples isolated.
I had to put some workaround in place to seep for 1 second between examples

**Comment by Pazus** [comment]
This is because last_ddl_time is date column...
Maybe the comparison method should be changed to invalidate cache if last_ddl_time is more *or equal* to the value stored in cache.
