### ISSUE TITLE
java.sql.SQLRecoverableException: Closed Connection

### ISSUE THREAD

**Issue by varianjv** [utPLSQL/utPLSQL#1228]
**Describe the bug**
java.sql.SQLRecoverableException: Closed Connection 
This seems to happen after 4 hours.

**Provide version info**
Database version 12.2.0.1.0
UT Version v3.1.10.3349

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
PL/SQL Release 12.2.0.1.0 - Production
"CORE	12.2.0.1.0	Production"
TNS for Linux: Version 12.2.0.1.0 - Production
NLSRTL Version 12.2.0.1.0 - Production

NLS_LANGUAGE	AMERICAN
NLS_TERRITORY	IRELAND
NLS_CURRENCY	€
NLS_ISO_CURRENCY	IRELAND
NLS_NUMERIC_CHARACTERS	.,
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_DATE_LANGUAGE	AMERICAN
NLS_SORT	BINARY
NLS_TIME_FORMAT	HH12:MI:SSXFF AM
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH24:MI:SSXFF
NLS_TIME_TZ_FORMAT	HH12:MI:SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH24:MI:SSXFF TZR
NLS_DUAL_CURRENCY	€
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	CHAR
NLS_NCHAR_CONV_EXCP	FALSE

x86_64/Linux 2.4.xx

**Information about client software**
utplsql cli 
utPLSQL-cli 3.1.8-SNAPSHOT.local
utPLSQL-java-api 3.1.8.546

**To Reproduce**
Run the following.
./utplsql run username/password@database:1521/utplsqltestdb -s -t 780 -f=ut_coverage_html_reporter -o=coverage.html

**Expected behavior**
Expect the reports to be produced.

**Additional context**
Our database is fairly large, 4.9 million relevant lines.
If I pass a -p parameter to keep it to one subset of tests it runs (approx 3 hours) and generates the coverage report.
However I need a complete report so removed the -P
Seems to always time out after 4 hours.
Running locally on the db server (to avoid any network/firewall timeout) shows the same result.
Nothing in the Oracle alert log/tracefiles, in fact the sql is still running in the database after the disconnect indicating a timeout on the client.

**Comment by lwasylow** [comment]
Hi can you move this ticket to utPLSQL-cli project? 
The client is separate tool from utPLSQL.
Did you tried running directly on database using sql/plsql?

Thanks

**Comment by varianjv** [comment]
I will move it (sorry).
Im new to generating a coverage report so im not sure of the syntax required to do that

**Comment by varianjv** [comment]
Gonna just close this as ive opened it in the right queue now
