### ISSUE TITLE
Ability to access test name and description at runtime

### ISSUE THREAD

**Issue by sosdarko** [utPLSQL/utPLSQL#1230]
> edited by @jgebal
It would be very neat if we could access in a runtime the name of the test that is currently executing. 
That would be similar to name of the function that implements the test, but the name of the test, annotated in the spec would be better.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Note**
> Please do not create issues for generic SQL or PL/SQL questions. There are other forums and communities to help you with those. See [ASKTom](https://asktom.oracle.com) for example.

**Want to discuss**
If you want to discuss your issue, join [our SLACK chat](https://join.slack.com/t/utplsql/shared_invite/zt-xwm68udy-4cF_3PNEyczYEbWr38W5ww).

**Comment by lwasylow** [comment]
Hi, you can track in session table as each test is recorded in database using `dbms_application_info.set_module( gc_module, gc_action )`. 
Could you please put in more details of what you trying to achieve? Once we know a problem we could look at the possible solutions. 
Cheers Lukasz

**Comment by jgebal** [comment]
You can access all the information that you need already using `sys_context` at runtime.
See [this section](https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/annotations.md#sys_context) of documentation.

I assume what you are looking for is something like:
```sql

create or replace package test_call is
  --%suite(The description of the suite)
  
  --%test(The description of the test)
  procedure test1;

end;
/

create or replace package body test_call is

  procedure test1 is
  begin
    ut.expect(sys_context('ut3_info','suite_package')).to_equal(user||'.test_call');
    ut.expect(sys_context('ut3_info','test_name')).to_equal(user||'.test_call.test1');
    ut.expect(sys_context('ut3_info','test_description')).to_equal('The description of the test');
    ut.expect(sys_context('ut3_info','suite_description')).to_equal('The description of the suite');
  end;

end;
/
```

**Comment by sosdarko** [comment]
Yes, that's exactly what I wanted, thanks Jacek.
As for what I needed this for, I have a log mechanism during tests, and the name of the test as a possible identifier. Instead of giving it explicitly, with this, I can achieve two things: make the call to log same for every test; remove the possibility of human error in matching the name passed to log call to actual test I'm in.
