### ISSUE TITLE
Exclude Columns to compare from Cursor

### ISSUE THREAD

**Issue by Arunosaur** [utPLSQL/utPLSQL#1241]
**Is your feature request related to a problem? Please describe.**
The sys_refcursor I need to compare with has columns as part of the result set, whose actual values will be unkwon to me to build it in the expectations. But, I want to compare the rest of the columns. One of the column is id and is sequence generated and is brought back in the cursor and the other one is the last change timestamp which at the time of insert or update would be unknown to me.
**Describe the solution you'd like**
While comparing cursors to exclude columns like id and timestamps to be excluded for comparison.
**Describe alternatives you've considered**
I just count the number of rows.
**Additional context**

**Note**
> Please do not create issues for generic SQL or PL/SQL questions. There are other forums and communities to help you with those. See [ASKTom](https://asktom.oracle.com) for example.

**Want to discuss**
If you want to discuss your issue, join [our SLACK chat](https://join.slack.com/t/utplsql/shared_invite/zt-xwm68udy-4cF_3PNEyczYEbWr38W5ww).

**Comment by lwasylow** [comment]
Hi Arunosaur
I'm nit entirely sure what's is the problem?
Have you tried exclude option as described ij Advanced data comparison, Excluding elements from data comparison?
I believe this should work for you.
Kind regards Lukasz

**Comment by jgebal** [comment]
As mentioned by @lwasylow it's already implemented.
The syntax `ut.expect( actual_cursor ).to_equal( expected_cursor ).exclude('ID,CREATE_TIME');` should do the trick.
Please have a look at [this part of documentation](https://www.utplsql.org/utPLSQL/latest/userguide/advanced_data_comparison.html#excluding-elements-from-data-comparison).
