### ISSUE TITLE
Call params for test are not valid: procedure XXX.UT_API_SITE_WEB.TEST1; does not exist.

### ISSUE THREAD

**Issue by claytonedk** [utPLSQL/utPLSQL#1259]
**Describe the bug**
I am having this error when running a test. I tried to create my test package in 3 different schemas but I had always the same error, I even tried to create it in UT3 schema with no success.

Here is the UT test package:
create or replace package ut_api_site_web is

   -- generated by utPLSQL for SQL Developer on 2023-06-21 11:08:28

   --%suite
   --%suitepath(bnq)
   
   --%test
   procedure test1;

end ut_bnqk_api_site_web;
/

create or replace package body ut_api_site_web is

   -- generated by utPLSQL for SQL Developer on 2023-06-21 11:08:28
   procedure test1
   is
   begin
      ut.expect(1).to_equal(1);
   end test1;
end ut_bnqk_api_site_web;
/

**Provide version info**
Database version
12.1.0.1.0
12.1.0.0.0

utPLSQL version
v3.1.13.3592

Server info
Oracle Database 12c Release 12.1.0.1.0 - 64bit Production
PL/SQL Release 12.1.0.1.0 - Production
"CORE	12.1.0.1.0	Production"
TNS for Linux: Version 12.1.0.1.0 - Production
NLSRTL Version 12.1.0.1.0 - Production

NLS params
NLS_LANGUAGE	CANADIAN FRENCH
NLS_TERRITORY	CANADA
NLS_CURRENCY	$
NLS_ISO_CURRENCY	CANADA
NLS_NUMERIC_CHARACTERS	, 
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	RR-MM-DD
NLS_DATE_LANGUAGE	CANADIAN FRENCH
NLS_SORT	CANADIAN_M
NLS_TIME_FORMAT	HH24:MI:SSXFF
NLS_TIMESTAMP_FORMAT	RR-MM-DD HH24:MI:SSXFF
NLS_TIME_TZ_FORMAT	HH24:MI:SSXFF TZR
NLS_TIMESTAMP_TZ_FORMAT	RR-MM-DD HH24:MI:SSXFF TZR
NLS_DUAL_CURRENCY	$
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	CHAR
NLS_NCHAR_CONV_EXCP	FALSE

x86_64/Linux 2.4.xx

**Comment by jgebal** [comment]
What is the user that executed the test package the same as user owning the test package?
What command / UI is used to execute the test package?
Please give exact error message you see when executing the command.

Also, what fo you see when executing commands:
```sql
srt serveroutput on
begin
  ut_api_site_web.test1;
end;
/
```

**Comment by claytonedk** [comment]
I executed your plsql anonym block and it ran successfully:
Procédure PL/SQL terminée.

I executed the test package with the same user that I used to compile the test package. I use SQL Developer to run utPLSQL.

**Comment by jgebal** [comment]
What is the username?

What happens when you run the following blocks:
```sql
set serveroutput on
begin
  ut_api_site_web.test1;
end;
/
begin
  ut.run('ut_api_site_web.test1');
end;
/
```

**Comment by claytonedk** [comment]
I use my user KUHC7028.

set serveroutput on
begin
  ut_api_site_web.test1;
end;
/

begin
  ut.run('ut_api_site_web.test1');
end;
/

SUCCESS
  Actual: 1 (number) was expected to equal: 1 (number)


Procédure PL/SQL terminée.

ORA-06512: à "UT3.UT_SUITE_MANAGER", ligne 345
ORA-06512: à "UT3.UT_SUITE_MANAGER", ligne 369
ORA-06512: à "UT3.UT_SUITE_MANAGER", ligne 457
ORA-06512: à "UT3.UT_SUITE_MANAGER", ligne 553
ORA-06512: à "UT3.UT_RUNNER", ligne 146

ORA-20204: Suite test KUHC7028.ut_api_site_web.test1 does not exist



Erreur commençant à la ligne: 7 de la commande -
begin
  ut.run('ut_api_site_web.test1');
end;
Rapport d'erreur -
ORA-20204: Suite test KUHC7028.ut_api_site_web.test1 does not exist
ORA-06512: à "UT3.UT_RUNNER", ligne 158
ORA-06512: à "UT3.UT", ligne 143
ORA-06512: à "UT3.UT", ligne 566
ORA-06512: à "UT3.UT", ligne 733
ORA-06512: à ligne 2

If I run this:
begin
  ut.run('ut_api_site_web');
end;
/

I get this:
tests for a package
  test1; [,003 sec] (FAILED - 1)
 
Failures:
 
  1) test1;
      Call params for test are not valid: procedure KUHC7028.UT_API_SITE_WEB.TEST1; does not exist.
Finished in ,004424 seconds
1 tests, 0 failed, 1 errored, 0 disabled, 0 warning(s)
 


Procédure PL/SQL terminée.

**Comment by claytonedk** [comment]
It worked after I recompiled the test package in TOAD using the same user, very strange. Now it works in SQL Deveoper. I will continue my investigation...

**Comment by claytonedk** [comment]
I created the test package using TOAD and tried to run tests for my schema:
SELECT *
FROM TABLE(ut.run('kuhc7028'))

but I got the same error. So my theory that it works in TOAD is not true.

I am running out of options and theories ...

**Comment by claytonedk** [comment]
Ok ok very strange, the fact is that if I compile in TOAD it works. So the problem is when compiling / creating the test package in SQL Developer. I don't know what can it be.

**Comment by jgebal** [comment]
What version of SQLDeveloper are you using?
Can you open the package specification  after it is compiled using oblect navigator to see if the package is the same as the source code?
The new version of SQLDeveloper had some issue where it removed empty lines.
Another possible issue could be codepage of compiled source but I would bet on the removal of empty lines.

**Comment by jgebal** [comment]
@claytonedk ?
I am closing this issue as I had no feedback from you.
It is SQLDeveloper related issue.
