### ISSUE TITLE
Lack of detailed information about differences in sys_refcursor only - "ORA-01762: vopdrv: view query block not in FORM" 

### ISSUE THREAD

**Issue by AndrzejKoziel** [utPLSQL/utPLSQL#1260]
**Describe the bug**
Lack od detailed information about differences in sys_refcursor only - "ORA-01762: vopdrv: view query block not in FORM" raised.
Assert raises only aboive exception if asserted sys_refCursor differs by row count, columns count or values. 

Exception:
  ORA-01762: vopdrv: view query block not in FROM
    ORA-06512: at "UT3.UT_COMPOUND_DATA_HELPER", line 555
    ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 252
    ORA-06512: at "UT3.UT_EQUAL", line 311
    ORA-06512: at "UT3.UT_EXPECTATION_BASE", line 28
    ORA-06512: at "UT3.UT_EXPECTATION", line 123

**Provide version info**
Information about utPLSQL and Database version, 

TEST ENV 1 
------------------------------------------------------------
11.2.0.1.0
11.2.0.0.0
 PL/SQL procedure successfully completed.

UT_VERSION                                                  
v3.1.13.3592                                                
1 row selected.

BANNER                                                                          
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production    
PL/SQL Release 11.2.0.1.0 - Production                                          
CORE	11.2.0.1.0	Production                                                      
TNS for 64-bit Windows: Version 11.2.0.1.0 - Production                         
NLSRTL Version 11.2.0.1.0 - Production                                          

5 rows selected.

PARAMETER                      VALUE                                   

NLS_LANGUAGE                   AMERICAN                                
NLS_TERRITORY                  AMERICA                                 
NLS_CURRENCY                   $                                       
NLS_ISO_CURRENCY               AMERICA                                 
NLS_NUMERIC_CHARACTERS         .,                                      
NLS_CALENDAR                   GREGORIAN                               
NLS_DATE_FORMAT                DD-MON-RR                               
NLS_DATE_LANGUAGE              AMERICAN                                
NLS_SORT                       BINARY                                  
NLS_TIME_FORMAT                HH.MI.SSXFF AM                          
NLS_TIMESTAMP_FORMAT           DD-MON-RR HH.MI.SSXFF AM                
NLS_TIME_TZ_FORMAT             HH.MI.SSXFF AM TZR                      
NLS_TIMESTAMP_TZ_FORMAT        DD-MON-RR HH.MI.SSXFF AM TZR            
NLS_DUAL_CURRENCY              $                                       
NLS_COMP                       BINARY                                  
NLS_LENGTH_SEMANTICS           BYTE                                    
NLS_NCHAR_CONV_EXCP            FALSE                                   

17 rows selected.

PORT_STRING                                                 
IBMPC/WIN_NT64-9.1.0                                        
1 row selected.

TEST ENV 2
------------------------------------------------------------
18.0.0.0.0
18.0.0
 PL/SQL procedure successfully completed.

UT_VERSION                                                  

v3.1.9.3270                                                 
1 row selected.

BANNER                                                                          
BANNER_FULL                                                                     
BANNER_LEGACY                                                                   
    CON_ID
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production             
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0                                                                                                                                          
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production             
         0
                                                                                
1 row selected.

PARAMETER                     

VALUE                                                           

NLS_LANGUAGE                  
AMERICAN                                                        
                                                                                
NLS_TERRITORY                 
AMERICA                                                         
                                                                                
NLS_CURRENCY                  
$                                                               
                                                                                
NLS_ISO_CURRENCY              
AMERICA                                                         
                                                                                
NLS_NUMERIC_CHARACTERS        
.,                                                              
                                                                                
NLS_CALENDAR                  
GREGORIAN                                                       
                                                                                
NLS_DATE_FORMAT               

PARAMETER                     

VALUE                                                           

DD-MON-RR                                                       
                                                                                
NLS_DATE_LANGUAGE             
AMERICAN                                                        
                                                                                
NLS_SORT                      
BINARY                                                          
                                                                                
NLS_TIME_FORMAT               
HH.MI.SSXFF AM                                                  
                                                                                
NLS_TIMESTAMP_FORMAT          
DD-MON-RR HH.MI.SSXFF AM                                        
                                                                                
NLS_TIME_TZ_FORMAT            
HH.MI.SSXFF AM TZR                                              
                                                                                
NLS_TIMESTAMP_TZ_FORMAT       
DD-MON-RR HH.MI.SSXFF AM TZR                                    

PARAMETER                     

VALUE                                                           

                                                                                
NLS_DUAL_CURRENCY             
$                                                               
                                                                                
NLS_COMP                      
BINARY                                                          
                                                                                
NLS_LENGTH_SEMANTICS          
BYTE                                                            
                                                                                
NLS_NCHAR_CONV_EXCP           
FALSE                                                           
                                                                                

17 rows selected.

PORT_STRING                                                 
x86_64/Linux 2.4.xx                                         
1 row selected.

**Information about client software**
Toad 16.2.98,
SQL*Plus: Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

**To Reproduce**
Execute UT_TEST_1 and UT_TEST_2 test from below code.

**Expected behavior**
Clear info about differences in asserted sys_refcursors.

**Example code**
------------------------------ ----------------------------------------
CREATE TABLE TEST_1
(
  RECEIVE_DATE  DATE,
  ID            NUMBER,
  TIMESTAMP     TIMESTAMP(6)
);

CREATE TABLE TEST_2
(
  RECEIVE_DATE  DATE,
  ID            NUMBER,
  TIMESTAMP     TIMESTAMP(6)
);

CREATE OR REPLACE PACKAGE UT_TEST AS

  --%suite(TEST)

  --%test()
  PROCEDURE UT_TEST_1;

    --%test()
  PROCEDURE UT_TEST_2;

END UT_TEST;
/

CREATE OR REPLACE PACKAGE BODY UT_TEST AS

  --%test()
  PROCEDURE UT_TEST_1 IS
  
    c_expect Sys_Refcursor;
    c_actual Sys_Refcursor;
    timestamp_1 timestamp(6) := systimestamp;
    timestamp_2 timestamp(6) := systimestamp;
  BEGIN
    --ARRANGE
        insert into Test_1 t
        (t.ID,
        t.RECEIVE_DATE,
        t.TIMESTAMP)
        values
        (1,
        sysdate,
        timestamp_1);
        
        insert into Test_2 t
        (t.ID,
        t.RECEIVE_DATE,
        t.TIMESTAMP)
        values
        (1,
        sysdate,
        timestamp_2
        );
        
        
     OPEN c_expect FOR
       select * from Test_1;
     
     Open c_actual FOR
       select * from Test_2 where id = 3;
  

    --ASSERT
    ut.expect(c_actual).to_equal(c_expect);
  
  
  END;

    --%test()
  PROCEDURE UT_TEST_2 IS
  
    c_expect Sys_Refcursor;
    c_actual Sys_Refcursor;
    timestamp_1 timestamp(6) := systimestamp;
    timestamp_2 timestamp(6) := systimestamp;
  BEGIN
    --ARRANGE
        insert into Test_1 t
        (t.ID,
        t.RECEIVE_DATE,
        t.TIMESTAMP)
        values
        (1,
        sysdate,
        timestamp_1);
        
        insert into Test_2 t
        (t.ID,
        t.RECEIVE_DATE,
        t.TIMESTAMP)
        values
        (1,
        sysdate,
        timestamp_2
        );
        
        
     OPEN c_expect FOR
       select * from Test_1;
     
     Open c_actual FOR
       select ID from Test_2 where id = 3;
  

    --ASSERT
    ut.expect(c_actual).to_equal(c_expect);
  
  
  END;

END UT_TEST;
/
**Additional context**

**Comment by jgebal** [comment]
Hi @AndrzejKoziel 
I think it may be related to the fact that your table has a column name that is same as datatype name (TIMESTAMP).

I have tried the same tests on  my local DB (Oracle 21c XE) and I got the following output:
```
TEST
  ut_test_1 [1.555 sec] (FAILED - 1)
  ut_test_2 [.287 sec] (FAILED - 2)

Failures:

  1) ut_test_1
      Actual: refcursor [ count = 0 ] was expected to equal: refcursor [ count = 1 ]
      Diff:
      Rows: [ 1 differences ]
        Row No. 1 - Missing:  <RECEIVE_DATE>09-JUL-23</RECEIVE_DATE><ID>1</ID><TIMESTAMP> 2023-07-09T14:31:24.032922</TIMESTAMP>
      at "UT3.UT_TST.UT_TEST_1", line 47 ut.expect( c_actual ).to_equal( c_expect );

  2) ut_test_2
      Actual: refcursor [ count = 0 ] was expected to equal: refcursor [ count = 1 ]
      Diff:
      Columns:
        Column <RECEIVE_DATE> [data-type: DATE] is missing. Expected column position: 1.
        Column <TIMESTAMP> [data-type: TIMESTAMP] is missing. Expected column position: 3.
      Rows: [ 1 differences ]
        Row No. 1 - Missing:  <RECEIVE_DATE>09-JUL-23</RECEIVE_DATE><ID>1</ID><TIMESTAMP> 2023-07-09T14:31:25.538665</TIMESTAMP>
      at "UT3.UT_TST.UT_TEST_2", line 94 ut.expect( c_actual ).to_equal( c_expect );

Finished in 1.859007 seconds
2 tests, 2 failed, 0 errored, 0 disabled, 0 warning(s)

```

**Comment by jgebal** [comment]
Well. I really can't tell why you have this problem
I have tested the same on Oracle 11g XE and it still works fine.
```
select * from v$version;
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
PL/SQL Release 11.2.0.2.0 - Production
CORE	11.2.0.2.0	Production
TNS for Linux: Version 11.2.0.2.0 - Production
NLSRTL Version 11.2.0.2.0 - Production
```

Maybe your DB version is too old.
Do you have all latest patches applied?

Did you (or your customer) consider upgrading?
This DB is out of support from Oracle corporation.
