### ISSUE TITLE
Transaction control if teardown/setup contains DDL

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#127]
If the suite/test has transaction control set to "auto" and  its setup/teardown contains ddl then implicit commits are issued and the execution failes with "ORA-01086 savepoint never established in this session"

We shoud figure out how to deal with that. Should we ignore that or warn somehow?

**Comment by rlove** [comment]
If possible I would capture the exception and report as it as assertion error for that test.

**Comment by jgebal** [comment]
Do we have ability to set transaction control for a single test with annotations?

**Comment by Pazus** [comment]
Yes

**Comment by jgebal** [comment]
How about having following options for rollback:
- no -> rollback is disabled
- yes -> rollback is enabled and causes test failure if commit was done
-auto -> rollback is enabled and no issue gets reported if commit was done

**Comment by Pazus** [comment]
I think we should leave two currently implemented options. If an error occurred in a setup/teardown procedure of a test, we have to report the test failed. If it occurred in a suite, mark all the sub-items failed.
What do you think?

**Comment by jgebal** [comment]
Failing tests or suite on teardown will be hacky.
I think that printing the information that test made a commit and auto-rollback was not executed would be better.
We should indicate the problem and possible solutions. Something like;
Test "test name" executed a commit and auto-rollback was not possible. 
To remove this warning, set atuo-rollback=false or remove commits in the test and tested code.

**Comment by jgebal** [comment]
Is auto-rollback propagating down, so I can disable it on suite level and it will be disabled for whole suite?

**Comment by jgebal** [comment]
I guess an example demonstrating the feature would be nice.

Maybe a test of ETL process that inserts data from stage table into employees and commits?

What I'd like to see is:
We have a default behavior with savepoints.
If it overridden it propagates down.
Overrides can be explicitly overridden on lower levels again.

**Comment by Pazus** [comment]
exception is handled now. Should close the issue?

**Comment by jgebal** [comment]
Closing, as it's handled now.
