### ISSUE TITLE
utplsql 3.1.12 is compatible with TOAD 17 version ?

### ISSUE THREAD

**Issue by Nareshdevops2** [utPLSQL/utPLSQL#1279]
Hi Team,

We are using utplsql 3.1.12 version and TOAD 17.0 patch 1 version. We are trying to install utplsql in TOAD but getting the below error message.

"Toad for oracle has been tested against utplsql 3.1.4 through 3.1.9. You have utplsql 3.1.12 installed."

Can you please let me know which version of Toad is compatible with utplsql 3.1.12?

regards,
Naresh

**Comment by lwasylow** [comment]
Hi
Utplsql is compatible with all versions of Oracle.
For details of specific third party tool and their plugins you have to check with plugin creator.

Cheers Lukasz
