### ISSUE TITLE
Is it possible to have a procedure in UT for data-setup?

### ISSUE THREAD

**Issue by anil1kuppa** [utPLSQL/utPLSQL#131]
I have a package WIE_MAT_TXN_PROCESSOR. Inside the package, I've the procedures:
DERIVE_MATERIALS
INVOKE_PROCESSOR

In my ut package (UT_WIE_MAT_TXN_PROCESSOR), I've the below procedures:
UT_SETUP
UT_TEARDOWN
UT_DERIVE_MATERIALS
UT_INVOKE_PROCESSOR.

I had written another procedure in my package called MISC_RECEIPT. But, the problem is that this procedure is also run by the suite. Is it possible to declare the procedures to be run and not be run to ensure that some of the procedures are not run by the suite? The procedure 'MISC_RECEIPT' was needed to run a script which will trigger the data creation. This procedure could be called by different other packages, hence I wanted to put it in spec.

**Comment by jgebal** [comment]
What version are you using?

**Comment by anil1kuppa** [comment]
I realized that if I don't prefix a procedure with 'UT_' , the procedure would not be run in unit testing.

**Comment by jgebal** [comment]
@anil1kuppa If you are just starting with UTPLSQL I recommend trying out v3, thought it's still alpha.
