### ISSUE TITLE
ut.runner failes with wrong schema provided

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#134]
it failes with not nice exception
```
begin
  ut.run('123123',ut_documentation_reporter);
end;
```

**Comment by jgebal** [comment]
I think this is a valid behaviour. The only thing is that framework should throw a named exception like: "invalid schema name (the schema name) provided" / "Invalid package name (the package name) provided" / "Suitepath (the path) not found"
The same goes when you specify valid schema, but non existing package.

I wonder what would happen if I specify a valid schema and a valid package, but the package is not a utPLSQL v3 package.
