### ISSUE TITLE
Resolve errors on Travis when running mkdocs

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#147]
We had to disable mkdocs generation on Travis at it was failing builds.
Failed builds to investigate:
https://travis-ci.org/utPLSQL/utPLSQL/builds/189814811#L2853

@rlove Can you help out with this one?
Also. We need to share knowledge on how to build the documentation from code as currently we do not know how to do that and we do not have proper comments in code to generate such documentation.
As the code gets more and more stable, that should be part of our DNA.

**Comment by rlove** [comment]
I am unsure of why that build failed.   I have re-enabled mkdocs generation in the build and it is now working.   I had it enabled for the 3.0.0.0Alpha1 release.  mkdocs is under active development and we are pulling down the latest released version on each build, so it's possible they had a bad build out.   But I have not investigated that.

mkDocs is configuration is stored in mkdocs.yml

-  new markdown files in docs directory need to be added to this to get it generate the html
-  Renames/deletes of markdown files  in docs directory need to be reflected in this file as well.

We are using the strict: true option in the file to cause an error when we have done this wrong.

You can always run mkdocs locally.    It's pretty easy to install and I have installed on both my windows machine and mac machine and works in both places.   I just have to use a bash shell on windows to run our test script, but if desired you can call mkdocs directly from a command prompt without bash.   Just look at the bash script to see the command line parameters.

the script we use to generate the docs is:   `.travis/build_docs.sh`

**Comment by jgebal** [comment]
it's now working - closing
