### ISSUE TITLE
Adding jenkins and teamcity to Travis CI

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#149]
Not sure if that is a good idea, but we could add the following docker images to our Travis CI.
https://blog.jetbrains.com/teamcity/2016/06/teamcity-on-docker-hub-its-official-now/
https://jenkins.io/blog/2014/08/12/official-jenkins-lts-docker-image/

With that we could then create jobs on each of the CI systems, run all the examples as a demo of UT reporting capabilities and publish the Unit Test results from both Jenkins and Teamcity somewhere (githubpages)?
That would be a nice demo of ability to run UT's on both CI's.

**Comment by Pazus** [comment]
Sounds like a great idea!

**Comment by jgebal** [comment]
Closing as it's just nice to have and it will bring maintenance cost to the delivery process.
