### ISSUE TITLE
Collaboration & communication

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#15]
I've setup a slack team:
https://utplsql.slack.com/
If you want to join, ping me with your mail and i'll send an invite.
@PaulWalkerUK I guess it would be best to add you as admin there.

**Comment by jgebal** [comment]
So fat @rlove has managed to join the slack.
Slack allows invite-only by email and I really do not have your emails to send you invites.
If we could get connected on linked-in, like Robert did with me today, we could exchange emails non-publicly.

**Comment by Shoelace** [comment]
join teh utplsql slack chat here..
utplsql-slack-invite.herokuapp.com

**Comment by jgebal** [comment]
@PaulWalkerUK 
@rlove, @Shoelace and @DDieterich are on slack.
Would be great if you could join.

**Comment by jgebal** [comment]
@stevenfeuerstein 
Are you interested in the refresh on utplsql or you leave it up to community?

**Comment by stevenfeuerstein** [comment]
I am not sure what you are asking me, but generally I am not active on the utPLSQL project now; I leave it all up to the community.

Cheers, Steven

**Comment by jgebal** [comment]
@stevenfeuerstein 
Thanks Stephen. This is what i was asking about. There is an initiative born to create utPLSQL v3, so jut wanted to check in with you, since you're on github.

**Comment by jgebal** [comment]
@Pazus would you be able to join slack?

**Comment by Pazus** [comment]
The invitation requested.

**Comment by jgebal** [comment]
http://utplsql-slack-invite.herokuapp.com/

**Comment by jgebal** [comment]
Since we now have a link to slack invite on readme file, I'd like us to close this discussion.
Are you OK with that?

**Comment by Pazus** [comment]
Ok

С уважением, Павел Капля.
