### ISSUE TITLE
No data found when running UTPLSQL v3 on schema with no ut pacakges

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#150]
If there are no suite packages defined the suite_manager raises an exception.
```
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 313
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 407
ORA-06512: at "UT3.UT_RUNNER", line 15

ORA-01403: no data found
```

**Comment by jgebal** [comment]
@Pazus will you be able to look into this?

**Comment by Pazus** [comment]
yep, also faced that it fixed in the branch i work on, can separate the change though

**Comment by Shoelace** [comment]
you could argue that "NO_DATA_FOUND"  is a valid exception.

but i agree that it should be handled
