### ISSUE TITLE
Started to play with the latest version

### ISSUE THREAD

**Issue by NickStrange** [utPLSQL/utPLSQL#153]
Looks like you guys have done some terrific work.

I have downloaded the latest version. and successfully run RunAllExamples.sql
as utplsql - to do that I had to alter user utplsql quota unlimited on users;

apart from that it all worked well
I had a lot more problems when trying to run as a different user  - I had to:

grant create public synonym to utplsql 
create public synonym ut_suite for ut_suite;
create public synonym ut_event_listener for ut_event_listener;
create public synonym ut_test for ut_test;
create public synonym UT_SUITE_ITEMS for UT_SUITE_ITEMS;
create public synonym UT_REPORTERS for UT_REPORTERS;
create public synonym UT for UT;

grant execute on ut to public;
grant execute on ut_documentation_reporter to public;

Now I can run a basic test - but I cant runAllexamples 
I get PLS-00714 supertypes AUTHID is DEFINER and subtype and subtypes are not in the same schema for the type ut_custom_reporter in my local schema

**Comment by Pazus** [comment]
Hi!
We are still working on ability to execute version3 from another schema, there is a Pull Request #152 for that. It also contains all necessary grants and synonyms as a script in client_source folder.

Could you try it?

**Comment by NickStrange** [comment]
I don't see any new scripts in the client source folder

**Comment by jgebal** [comment]
The changes are not yet in v3 branch. They wait for a review and approval before they get merged.
You can see the changes here:
https://github.com/utPLSQL/utPLSQL/pull/152
This should go into the v3 really soon.

**Comment by jgebal** [comment]
Hi @NickStrange 
The installation with availiability for other schemes is now resolved.
Framework objects were adjusted and scripts added so that you can:
- grant utplsql to a user (and create private synonyms)
- grant utplsql to public (and create public synonyms)

The uninstall for utplsql v3 now tries to remove any private and public synonyms that are pointing to utplsql v3 objects.

**Comment by NickStrange** [comment]
Looking a lot better - just installed the latest code. My user can now run most of the tests.
I do get:
ORA-06550: line 2, column 17:
PLS-00201: identifier 'UT_LOGICAL_SUITE' must be declared
ORA-06550: line 2, column 17:
PL/SQL: Item ignored
ORA-06550: line 3, column 17:
PLS-00201: identifier 'UT_EVENT_LISTENER' must be declared
ORA-06550: line 3, column 17:

for a couple of tests

I chose the create public synonyms option - running on a 12.1 database

**Comment by jgebal** [comment]
Looks like a bug - missing synonyms

**Comment by jgebal** [comment]
Hmm... after having a closer look it doesn't look like a bug.
Both types are `internal` and not exposed as an API.
When running internal tests of the framework you should probably run them from the user/schema owning the code.
Have you encountered those issues when running the framework unit test scripts or when running the examples (from example directory).
For examples, you could see this error, when trying to create the `ut_custom_reporter` type in schema different then the owner of utplsql v3 I think.
