### ISSUE TITLE
need counter argument for "missing" feature / feature request

### ISSUE THREAD

**Issue by Shoelace** [utPLSQL/utPLSQL#16]
OK,

so the team here at my new office what to start implementing unit test (yay!)
the main guy who is pushing it want to go with the unit testing from SQLDEVELOPER (which i havent used before) , where as i was suggesting utPLSQL (which i have used)

He's just shown me a demo i dont seem to have a counter argument for one of its features namely:
* you dont have to have the tool installed on each database. only the underlying packages.

if you are not aware.. it basically work as follows.. you have a package with tests installed on the desired database.  separately you have a unit-test repository installed on an instance and the input,output and validation of each function/procedure is configured (via a gui) and stored in the repo . when the tests run it grab the metadata from the repo, executes the package against the desired instance and then validates the results against the metadata and stores results back into repo.

so.. my questions are
* what is the counter argument for this feature? as it does seem pretty usefull
and
* is this something we want to add for v3 (or is it just a different/incompatible design philosophy )

i guess i should point out.. that part of his goal for this is to use 'unit testing' as a way to monitor the database for anomalies. odd object grants, duplicate/missing data in core tables, etc..

**Comment by jgebal** [comment]
I saw SQL Developer unit testing and here are my counter-arguments.

* UT's will be bound to vendor-specific IDE.
* UT's are to be build for developers and by developers. This involves coding. SQL Developer is a UI-based framework.
* UT's should coexist with code in version control system and be versioned together with code, so you can always revert to a specific version of code along with tests. This is important in scenario when DEV is in version 5.9 in progress, QA env is testing version 5.8, PROD is still in version 5.7 and you have a prod issue that needs fixing. You then revert on DEV to 5.7 version (code+ tests), write a fix for prod code and tests to prove that fix is working, merge changes into 5.7.1 hotfix release, into 5.8 and into 5.9.

* flexibility - despite all nice features of SQL Developer UT's, it is a UI framework and as such will have it's own limitations on top of PLSQL/SQL. This will lead into developers doing workarounds/hacks in some tests as the framework may not allow to do some things. In programming-language based unit tests your only limitation is the language itself and your skills.

For me both SQL Developer and utPLSQL have a weakness of testing from inside of the database, so you really cannot test things like privileges, VPD or cross session interactions without coding outside of framework. This and few more reasons pushed me away from those solution into ruby-plsql-spec some years back.

Times change and now I'm interested in getting more of utPLSQL.

**Comment by rlove** [comment]
We considered SQL Developer.   However we have multiple people all using different ways to connect to Oracle.   SQL Plus, SQL Developer, TOAD, SQL Workbench, etc...   It made us have to install and open a different tool if we wanted unit tests and we wanted something that supported the wider tool base we have installed.

Migrating and storing test scripts from one database to another was easier with utPLSQL and that is common thing we need to do.

**Comment by jgebal** [comment]
I believe we can close this discussion.
@Shoelace , @rlove, what do you think?
