### ISSUE TITLE
Update definition of `name` field for matchers after matchers were renamed

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#160]
The names should be in a human readable form (without the `UT_` prefix and without underscore).

So that object name `ut_be_null` is reported as `be null` in reporter.
Example:
```
  expected (actual value): NULL(varchar2)
  to ut_be_like 'a text'
```
Should be reported as:
```
  expected (actual value): NULL(varchar2)
  to be like 'a text'
```

**Comment by jgebal** [comment]
We could go a step further and say that report should contain:
```
  expected this: NULL(varchar2)
  to be like 'a text'
```

The reporter seems a bit noisy at the moment (too much text that is irrelevant).

**Comment by Pazus** [comment]
looks nice
