### ISSUE TITLE
Add accessible by with conditional compilation for 12c

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#165]
To improve framework security we should include the `accessible by`
https://oracle-base.com/articles/12c/plsql-white-lists-using-the-accessible-by-clause-12cr1
This way we can limit the access to internal code.

**Comment by Pazus** [comment]
we have to test on 12c also then

**Comment by Shoelace** [comment]
if we do that we still should to support oracle 11g.

**Comment by rlove** [comment]
11g is still our base for CI.    Since we are having difficulty in getting 12 instances with travis.

I am still hoping that we can get Oracle to donate access to 12 in the cloud so we can test against the latest versions as well..

**Comment by jgebal** [comment]
I was thinking of using conditional compilation to use the feature.
In general we could use 12c features this way.
I agree that we need a 12c and 11g CI to to that

**Comment by jgebal** [comment]
Closing, as this feature doesn't bring any real value and will introduce complexity.
