### ISSUE TITLE
Version 3 - Unit Test Specification

### ISSUE THREAD

**Issue by rlove** [utPLSQL/utPLSQL#17]
I have drafted a [Version 3 Unit Test specification](https://github.com/utPLSQL/utPLSQL/wiki/Version-3-Unit-Test-Specification).   That allows your current version 2 tests to run in version 3 but also give many new features that are specific to version 3.     

Key Features
- Prefix is optional
- a test package can have _optional_ metatdata.
- Multiple `Setup`, `Teardown`, and `Test` procedures with any association
  - Example:
  -  `setup` and `teardown` can be associated with `test1` and `test2` but not with `test3` or `test4`
  -  `setup3` and `teardown3` can be associated with `test3`
  -   `setup` and `teardown3` can be associated with `test4`
- Auto test detection can be done at registration or test execution/run time.
- Test Suite Registration
  - Methods can be registered explicitly (by passing the detection algorithm)
  - Packages can be registered explicitly
  - Packages can be found by registering one or more prefixes.
  - Suites can can suites to allow for grouping of smaller test sets into a larger suite. 

Please review and let me know what you think.

**Comment by rlove** [comment]
Considering adding an optional parameter on `teardown` that will let you know if an assertion failed.

That way you can optionally clean up.    This was requested by a developer on my team who liked being about to have data left in the database when a test failed.

**Comment by Shoelace** [comment]
im not sure a parameter is the best way to go..  an option to the test execution seems a better way.. and yes it could either not run teardown or set a flag.. or yes i guess pass a parameter..

**Comment by jgebal** [comment]
I'd rather not introduce such feature as it's actually a workaround for another issue.
The issue described seems to point to the fact that tests created by developer were not able to provide information about 'why the test is failing'. This seems to be wither issue of the testing approach itself or the code that is tested being too big and therefore not testable or the testing framework not being able to provide the expected outcomes.
Without a working example it's really hard to say, but i would refrain from introducing such features that are a bit hacky.
