### ISSUE TITLE
New Project Administrator?

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#18]
It has become clear in recent weeks that there are other people with more time and energy to spend on this project than I do. I'm pleased to see a group of people working together to drive this project forward, but as things stand at the moment, there's more chance of me holding things up rather than adding much value.

With that in mind, if anyone would like to volunteer to take on running the project, I will be more than happy to take a back seat. Any such volunteer would of course have my full support and I will do what I can to help in the transition.

**Comment by jgebal** [comment]
Hi Paul, I think it would be best to discuss it on Slack.
A person holding things up is definitely needed, even if he/she doesn't bring much value to the project. Someone needs to step into Product Owner's shoes, so that v3 that is about to be born has a consistent design despite of number of contributors and ideas.
Though we're all professionals, a leader, person keeping the direction of the project is required.

**Comment by Shoelace** [comment]
I too would probably argue in favour of keeping you as lead admin but only if you're happy to. 
I agree with @jgebal  that having a single person drive/approve the direction of the projects can work quite well (eg Linux) even if it was just to make tie-break decisions between the "active developers".

thats also not to say you can't cede commiter/contributer access for the project to other individuals.

its probably not relevent for this dicsussion but i was wondering @PaulWalkerUK  how/why you managed to takeover the sourceforge project to begin with?

**Comment by PaulWalkerUK** [comment]
I got involved in utPLSQL in the summer of 2013. At the time, I'd been using utPLSQL a bit and had found a couple of small bugs. The project was going through a "dormant" phase - there were a variety of tickets (patches, bug reports, etc) that had been open for quite some time and there was generally very little activity happening on the project. I made contact with the people listed as administrators on the Sourceforge project page and after a number of emails, I agreed to pick up the project and try to make it active again. I never had great ambitions to take the project very far - my intention was really just to "keep the lights on", respond to tickets, merge contributions, slowly fix bugs/add features, etc.

Since then, my role at work has changed and I now get to write very little PLSQL, I never get the opportunity to use utPLSQL and I don't have much time to spend on it.

While I am happy to carry on in this role, if anyone else is wanting to get more involved, I am perfectly  happy to increase their permissions on the project. I don't mind whether we work together or if I take (even more!) of a back seat...

**Comment by TimNanos** [comment]
Hi, @PaulWalkerUK !
I have been using utPLSQL for quite a while and _do_ have enough time and enthusiasm to support the project. I would be very happy to get involved, and if you're still looking for a volunteer, please feel free to contact me via email: tim (at) timnanos.com
Thanks!

**Comment by PaulWalkerUK** [comment]
Hi @TimNanos - I'll send you an email....

**Comment by rlove** [comment]
@PaulWalkerUK  I am very willing to take it.   I don't know how I missed this thread for so long.

**Comment by rlove** [comment]
I now have project administrator access, I am closing this discussion.
