### ISSUE TITLE
Coverage reporters architecture 

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#181]
of framework.
Formatting of coverage results should be done by reporters.
Coverage gathering should not start if coverage reporter is used.
Coverage reporter should produce single output stream (like other reporters)
profiler tables should be global temp so we don't need to worry about excessive storage.

**Comment by Pazus** [comment]
Does the issue correspond to v3 or v3.1?

**Comment by jgebal** [comment]
The architecture of coverage gathering is stabilised now. The gathering of coverage is nicely separated from formatting.
