### ISSUE TITLE
Migrate website from Sourceforge

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#2]
The website for utPLSQL is currently hosted at: http://utplsql.sourceforge.net/. This should be moved away from Sourceforge.

- [x] Research how to run the website from GitHub

- [ ] Move files into GitHub

**Comment by rlove** [comment]
I am familiar with GitHub Sites and could do this if you want the help.

**Comment by PaulWalkerUK** [comment]
Hi, thanks for the offer :smile: 

Just to give you the background on how it currently works... All the source files for the website are in the main repository under `/documentation/source`. There's a script `/documentation/source/build.pl` that takes these source files, wraps some header/footer boiler plate etc and outputs the 'built' files to `/website/Doc`, ready to be uploaded. This was setup while there was just one SVN repository and had the advantage that the website files were version controlled in the same place as the code.

I'm thinking we'll want a organizational website. I can't see that we'd want multiple sites for different repositories.

What's the best of doing it on GitHub? Do we still maintain the source files in the main repository then basically just update the utPLSQL.github.io repository with the 'built' files from the script as part of doing a release?

**Comment by rlove** [comment]
You can maintain the site source in an external repository, and push the build.pl output to the utPLSQL.github.io site.     

There is only one potential problem I can see with that method.    Anyone can issue a pull request on that repository.    If those pull requests are accepted then your master copy in the code repository won't have those changes.    

I think this can be easily adverted with a readme or contributing file on the website repository directing changes to the correct location.  

Long term I think keeping the files with the code will make it easier.

**Comment by PaulWalkerUK** [comment]
OK, I'll have a go at getting that setup, thanks (I'll let you know if I get stuck :wink:)

**Comment by rlove** [comment]
After spending time on this, it was clear it was easier to keep the files in a separate repository.    With only the documentation moving over with the build.pl 

The basis of new site is up:  https://utplsql.github.io

Since I have other issues to finish up everything, I am going to consider this issue closed.
