### ISSUE TITLE
anomoly

### ISSUE THREAD

**Issue by NickStrange** [utPLSQL/utPLSQL#208]
I wrote the body of test_pkg - might be handy to add this to the doc on annotations
when run - I see: (notice setup seems to be called twice before test 4 - is that expected?)

globaltests
Name of suite
globalsetup
setup 
test1
Name of test1
teardown
setup 
setup_test1
test2
teardown_test1
Name of test2
teardown
setup 
setup 
test4
Name of test4
teardown
global_teardown
Finished in .017768 seconds
3 tests, 0 failures

create or replace package test_pkg is

  -- %suite(Name of suite)
  -- %suitepath(all.globaltests)

  -- %beforeall
  procedure globalsetup;

  -- %afterall
  procedure global_teardown;

  /* Such comments are allowed */

  -- %test
  -- %displayname(Name of test1)
  procedure test1;

  -- %test(Name of test2)
  -- %beforetest(setup_test1)
  -- %aftertest(teardown_test1)
  procedure test2;

  -- %test
  -- %displayname(Name of test3)
  -- %disable
  procedure test3;

  -- %test(Name of test4)
  -- %rollback(manual)
  procedure test4;

  procedure setup_test1;

  procedure teardown_test1;

  -- %beforeeach
  procedure setup;

  -- %aftereach
  procedure teardown;

end test_pkg;

create or replace package body test_pkg is

  -- %suite(Name of suite)
  -- %suitepath(all.globaltests)

  -- %beforeall
  procedure globalsetup is
  begin
      dbms_output.put_line('globalsetup');
  end;

  -- %afterall
  procedure global_teardown is
  begin
      dbms_output.put_line('global_teardown');
  end;

  /* Such comments are allowed */

  -- %test
  -- %displayname(Name of test1)
  procedure test1 is
  begin
      dbms_output.put_line('test1');
  end;

  -- %test(Name of test2)
  -- %beforetest(setup_test1)
  -- %aftertest(teardown_test1)
  procedure test2 is
  begin
      dbms_output.put_line('test2');
  end;

  -- %test
  -- %displayname(Name of test3)
  -- %disable
  procedure test3 is
  begin
      dbms_output.put_line('test3');
  end;

  -- %test(Name of test4)
  -- %rollback(manual)
  procedure test4 is
  begin
      dbms_output.put_line('test4');
  end;

  procedure setup_test1 is
  begin
      dbms_output.put_line('setup_test1');
  end;

  procedure teardown_test1 is
  begin
      dbms_output.put_line('teardown_test1');
  end;

  -- %beforeeach
  procedure setup is
  begin
      dbms_output.put_line('setup');
  end;

  -- %aftereach
  procedure teardown is
  begin
      dbms_output.put_line('teardown');
  end;

end test_pkg;

exec ut_runner.run(user||'.test_pkg');

**Comment by jgebal** [comment]
Hi @NickStrange ,
I've tried to your example and here are the outcomes on my local env (11g XE):
```sql
create or replace package test_pkg is

-- %suite(Name of suite)
-- %suitepath(all.globaltests)

-- %beforeall
procedure globalsetup;

-- %afterall
procedure global_teardown;

/* Such comments are allowed */

-- %test
-- %displayname(Name of test1)
procedure test1;

-- %test(Name of test2)
-- %beforetest(setup_test1)
-- %aftertest(teardown_test1)
procedure test2;

-- %test
-- %displayname(Name of test3)
-- %disable
procedure test3;

-- %test(Name of test4)
-- %rollback(manual)
procedure test4;

procedure setup_test1;

procedure teardown_test1;

-- %beforeeach
procedure setup;

-- %aftereach
procedure teardown;

end test_pkg;
/

create or replace package body test_pkg is

-- %suite(Name of suite)
-- %suitepath(all.globaltests)

-- %beforeall
procedure globalsetup is
begin
dbms_output.put_line('globalsetup');
end;

-- %afterall
procedure global_teardown is
begin
dbms_output.put_line('global_teardown');
end;

/* Such comments are allowed */

-- %test
-- %displayname(Name of test1)
procedure test1 is
begin
dbms_output.put_line('test1');
end;

-- %test(Name of test2)
-- %beforetest(setup_test1)
-- %aftertest(teardown_test1)
procedure test2 is
begin
dbms_output.put_line('test2');
end;

-- %test
-- %displayname(Name of test3)
-- %disable
procedure test3 is
begin
dbms_output.put_line('test3');
end;

-- %test(Name of test4)
-- %rollback(manual)
procedure test4 is
begin
dbms_output.put_line('test4');
end;

procedure setup_test1 is
begin
dbms_output.put_line('setup_test1');
end;

procedure teardown_test1 is
begin
dbms_output.put_line('teardown_test1');
end;

-- %beforeeach
procedure setup is
begin
dbms_output.put_line('setup');
end;

-- %aftereach
procedure teardown is
begin
dbms_output.put_line('teardown');
end;

end test_pkg;
/

begin
  ut_runner.run(user||'.test_pkg');
end;
/
```

outputs:
```

Package TEST_PKG compiled


Package body TEST_PKG compiled


PL/SQL procedure successfully completed.

globalsetup
setup
test1
teardown
setup
setup_test1
test2
teardown_test1
teardown
setup
test3
teardown
setup
test4
teardown
global_teardown
```
Not sure what's the issue.
I'll try again tomorrow (if I can), to see how it is on 12c.

**Comment by NickStrange** [comment]
If I rem out the call to the disabled test 3 - the problem disappears - is one setup for test 3?
I thought I was fairly up to date - but maybe not

**Comment by jgebal** [comment]
Hi Nick.
Can you try with the today's version?
We have just merger 2 pull requests.
One of them was about refactoring the beforeall and afterall.

**Comment by NickStrange** [comment]
I hope to find time tomorow

**Comment by NickStrange** [comment]
looks good now
