### ISSUE TITLE
Warn on savepoint not reachable

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#210]
Print warning when savepoint never established exception is raises.

**Comment by jgebal** [comment]
Is this done?

**Comment by Pazus** [comment]
Not yet

**Comment by jgebal** [comment]
@Pazus Can you add a feature to capture the exception on rollback to savepoint and print a warning on the test execution if savepoint was not reachable?
We could add information that the test or before/after block committed the transaction,
