### ISSUE TITLE
Compatibility with 11.2

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#23]
Hi all.

I've forked the version3 branch and unfortunately i've figured out that it is not compatible with 11.2 due to the use of record types in Native Dynamic SQL  statements with only appear to be included in 12c. It might slightly change the idea to store all types in ut_types package.

Do you think records with colelctions should be replaced with object types?

Also I think definition of _dbms_id_, _dbms_quoted_id_ types should be made with conditional compilation to support both 11g and 12c.

**Comment by Shoelace** [comment]
yes i agree about the conditional comp of dbms_id and dbms_quoted_id.  i had planned to do that i just hadnt gotten to it.

you seem to be rigth about teh execute immediate restriction.
compare
https://docs.oracle.com/cloud/latest/db112/LNPLS/dynamic.htm
to
https://docs.oracle.com/database/121/LNPLS/dynamic.htm

object types are nice as it allow you to add methods to the objects (such as validate() or toString() ) rather then using helper functions.  i dont think there are any licencing issues regarding them either and are valid back to at least 10g..  but i think we decided we were only going to support 11 and up anyway.

i'll try and dig out my 11.2 version and see if i can come up with another solution.

thanks for the heads up..

**Comment by Pazus** [comment]
If you are not against the object type approach I can prepare a pull request.

**Comment by Pazus** [comment]
The problem is that one can't use conditional compilation for object type properties, so untill 11g DB version is supported dbms_quoted_id is not usable.

**Comment by Shoelace** [comment]
well that was just a nicety.. there is no real reason to not use varchar2(32)  i just found dbms_id as i was rumaging and thought it would be cool.

**Comment by Pazus** [comment]
I have found out that the main idea of your approach through records and NDS doesn't fit 11g restrictions. As there is no straight forward way to pass record type variables to NDS it seems that object based design might be the only way to go. 
Also it has other benifits: we can define abstract reporter and one can enrich reporting solutions by inheriting abstract object type with custom implementation, this objects would be called without any dynamics by methods from the abstracct class. OOP Composite pattern, mentioned in #17, where suites can be grouped into larger suite will be difficult to implement through records.
All this encourage me to make a object type based implementation of the v3 according to all the restrictions and compatibilities discussed. I'll let you all know when I finish me draft but beforу that I would like to hear you opinion of such design because it has drowbacks like difficulties with altering types that form referencing other types in the future.

**Comment by Shoelace** [comment]
@pazus,  have you investigated if it can be done via dbms_SQL?  i dont have an 11g handy to check.

if not i dont have an issue.(i love objects myself) . it may only have a performance penalty.. but without testing thats only a guess anyway.

if you have the time go ahead and make the change.. it can then at least be discussed more fully

FYI if you havent already you may want to join teh slack discussion/chat thing.. (see  https://utplsql.github.io/contributing/

**Comment by jgebal** [comment]
I'm also ok with using objects. Despite performance issues. They make some implementations much easier. The alter syntax needs to be used on objects only if they are presided, otherwise the brut force drop/create can be used and the complexity of alerts goes away

**Comment by Shoelace** [comment]
i make use of object in my log4 implementation: [log4oracle](https://github.com/Shoelace/log4oracle)

i that i actually had a base abstract type (lob4_object) that everything inherited which allowed my to enforce a consistant 'tostring()' method (like java) and a map function 'compare()' which facilitated sorting. these were then just overridden as necessary

ie

```SQL
create or replace type log4_object 
AUTHID DEFINER
AS OBJECT
(
	zzz_dummy number,
	member function toString RETURN VARCHAR2,
	map member function Compare return varchar2 

)
not instantiable not final;
/
```

the zz_dummy was required as you need at least 1 attribute. but somethign more useful could be defined instead. (a GUID maybe?)

**Comment by Pazus** [comment]
@Shoelace with dbms_sql restrictions are the same.

Now I'm working on a object-based variant, I'll show you draft when it's ready.

**Comment by Shoelace** [comment]
on another 11.2 compatibility issue..
utl_call_stack is a 12c addition.. but is really quite useful/nice.

so useful in fact i have created a backport/copycat/polyfill type implentation for 11g. see
https://github.com/Shoelace/log4oracle/blob/master/src/Util/UTL_CALL_STACK.pks
https://github.com/Shoelace/log4oracle/blob/master/src/Util/UTL_CALL_STACK.pkb

its only 90% there at the moment.. and you dont get quite the same level of detail. but you do get to then code to a single api for exceptions.

**Comment by jgebal** [comment]
Sorry for off topic - @Shoelace the UTL_CALL_STACK looks really interesting and useful. Could prove a very valuable utility.
@Pazus I'm just looking through your forked code, lots of work getting done there.

**Comment by Pazus** [comment]
@Shoelace, @jgebal, I have my first draft done: [object-types-design branch](https://github.com/Pazus/utPLSQL/tree/object-types-design)

Mostly it is a complete rework of current v3 branch based on objects. 
I think now configuration looks much simplier than in record-based variant. 
Object model open opportunities for customization of reporting solutions by subclassing basic abstract and decorating it. Also one can create infinite level of test suite inheritance.

I have also modified examples made by @jgebal and add two new.

Please share with me what you think about this approach.

**Comment by Shoelace** [comment]
@pazus  
it didnt compile immediately. you appear to have lost the ut_types package which was referenced by ut_assert.  

but otherwise that loos pretty good.  i dont have any issue with moving to this.

having said that.. have we now just recreated [PLUTO - PL/SQL Unit Testing for Oracle](https://github.com/rlove/pluto-test-framework) ?  i dont think so. that seems to be using objects as tests as opposed to packages. where as this is supposed to be more objects as types primarily to support 11g.

**Comment by Pazus** [comment]
@Shoelace my bad, fixed that. ut_types was renamed to ut_utils package.

And yes, I don't think i've recreated PLUTO, testing targetis still a package, with all it's cons for testing coding, objects are used only for the framework and ease of configuration and also for compatibility issues.

Should I create a pull request with this draft?

**Comment by Shoelace** [comment]
i think if it works on 11g its demonstrably better then the current version.. is that the version you have been using?

so if you've fixed that then yes i would..   just reference this issue in the pull request with a #23 

i have a number of suggested improvments but i think thats a discussion for elsewhere.

**Comment by rlove** [comment]
Pull request accepted closing.
