### ISSUE TITLE
Specia expectetion for exception cheching

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#233]
Frequently you need to validate raised expected exception is correct. To do this you might user pattern:
```sql
exception when others then
ut.expect(SQLCODE).to_be_between(-20999, -20000);
ut.expect(upper(SQLERRM)).to_be_like(upper('%error text key words go here%'));
end;
```

I propose to implement specialized expectation, for example:
`ut.expect_exception(a_custom_flag[boolean], a_msg_like[varchar2], a_case_sensitive[boolean default false])`
`ut.expect_exception(a_error_code[number], a_msg_like[varchar2], a_case_sensitive[boolean default false])`

The message should be checked by like with `%` explicitly provided by user

**Comment by lwasylow** [comment]
How's that would work? Would still have to call expecations in exception block ? Whats the benefit over first approach ?

**Comment by jgebal** [comment]
The current solution is to use:
```sql
declare
  ex_named_exception exception;
  pragma exception_init(ex_named_exception, -20001);
begin
  foo();
  ut.fail('Describe why we shouldn't get here');
exception
  when ex_named_exception then
    ut.expect(sqlerrm).to_be_like('%error code here%');
end;
```
This way:
- if nothing is raised, the expectation fails,
- if wrong exception is raised, the code raises unhandled exception and test fails

Alternatively:
```sql
declare
  l_sqlcode integer;
begin
  begin
    foo();
  exception
    when others then
      l_sqlcode := sqlcode;
  end;
  ut.expect(sqlerrm).to_be_like('%error code here%');
end;
```
This way:
- if nothing is raised, the expectation fails,
- if wrong exception is raised, the expectation fails

**Comment by mathewbutler** [comment]
This is a good first step. The things I would check in these kinds of tests;

- sqlcode is expected value 
- sqlerrm includes some specific context
- sqlerrm has a specific message
- sqlcode is in some range

You've covered these. 

Tools like Junit use an annotation mechanism to avoid writing the boiler plate code. 

The equivalent would be to extend the -- Test annotation;

-- Test 

  -- %test(expected=e_no_data_found, description=Returns substring from start position to end position)

There are pros and cons to this in PLSQL. The main con is that these annotations are no close to the implementation. 

https://github.com/junit-team/junit4/wiki/exception-testing

Just some thought. 

Cheers (flawlessplan)

**Comment by jgebal** [comment]
This is related to #151

**Comment by jgebal** [comment]
Closing - duplicated with #490
