### ISSUE TITLE
Coverage privileges

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#239]
Currently, when installing on travis CI, the ut3 owner has to have `select any dictionary` or `select_catalog_role` granted. Without this, the `ut_coverage` fails to execute the select on `all_source`.
This should be further investigated and either fixed or documented as a requirement.

**Comment by Shoelace** [comment]
well then maybe `ut_metadata.get_source_definition_line` could be change like `ut_metadata.get_package_spec_source` to use `dbms_preprocessor.get_post_processed_source` and use that..

or maybe just call `dbms_preprocessor` directly when needed  ??

**Comment by Shoelace** [comment]
but that may not work if you have your test packages in a seperate schema from the packages being tested..  i havent looked at the code coverald code in a while.

**Comment by jgebal** [comment]
This is getting resolved by #271

**Comment by jgebal** [comment]
This seems to be resolved for now - closing.
