### ISSUE TITLE
Fix ut_run.sql to work with Oracle SQLCL.

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#240]
Currently the ut_run cannot be invoked from sqlcl due to fact that we use `-[p|c|o|s]=...` as parameters.
SQLCL does not like the `-` in command line.
What could be done actually is to have a separate script for SQLCL that would use the power of Java/JS.
We could leverage the multisession capability and consume each reporter in a separate thread.

**Comment by viniciusam** [comment]
If it's not a priority, I could take a look into it.

**Comment by jgebal** [comment]
There is other higher priority task for ut_run.sql script. You could take it if you want.
#241

**Comment by viniciusam** [comment]
No problem, I think I can do that one.

**Comment by jgebal** [comment]
Closing this one am we will focus on the `utplsql-cli` project
