### ISSUE TITLE
Add support for project sources path to ut_run.sql for coverge reporting

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#241]
The `ut_run.sql` should accept additional parameter to indicate project sources path.
The path parameter should be used with command line utility (dir-windows/ls-linux) to list all files in that path.
The files then should become part of the invocation of coverage reporter(s).

**Comment by jgebal** [comment]
we should have two parameters actually:
- `source_path=` - path to sources directory (relative to the project root)
- `test_path=` - path to unit tests directory (relative to the project root)
Those paths are required for sonar and coveralls reporting

**Comment by viniciusam** [comment]
I changed the behavior we talked abou on slack a bit, and created a platform specific wrapper file to call ut_run.sql.

Instead of calling:
`sqlplus /nolog @ut_run.sql params`

you should call:
`ut_run.bat params` or `ut_run.sh params`

and you can even have it on your path.

The wraper just passes the current dir and client dir to the ut_run.sql script. The tmp files will all be created on client dir.

problems I think we might have:
- paths with spaces
- too many files on path:
```
:l_file_list := q'[ut_varchar2_list(
ERROR at line 2:
ORA-06550: line 2, column 19:
PLS-00172: string literal too long
```

**ps: not finished yet**
https://github.com/viniciusam/utPLSQL/tree/project_path/client_source/sqlplus

what do you think?

**Comment by jgebal** [comment]
Few functional issues.
Command: 
`client_source\sqlplus\ut_run.bat ut3/ut3@orclpdb1 -f=ut_coverage_html_reporter -o=cov.html -source_path=examples` 
is spooling and displaying to screen 
Command:
`client_source\sqlplus\ut_run.bat ut3/ut3@orclpdb1 -f=ut_coverage_html_reporter -o=cov.html` is just spooling.
Seems like the -o= is not disabling the display to screen. I suspect the `-source_path` is causing the `-s` to get enabled.

The `ut_coverage_html_reporter` should also be able to use source_path.

The `file_list.bat/sh` should be universal and take parameters: 
client_path, project_path, scan_path, out_file_name, sql_file_list_param_name
This way you abstract from specific use case and script can have more generic function: 
"Scan given path and prepare out file that assigns the path to parameter"
Then you can call the script twice: once for sources once for tests.

The same goes for functions `parse_source_path_param`, `parse_test_path_param`.
We could have just one function with additional parameter: `a_path_type` or something like that.

The paths produced by `file_list.bat` include directory names like: `examples` or `examples\between_string`.
It would be best to include only files - that will reduce the amount of things to do.

To avoid the issue with exception
```
ERROR at line 2:
ORA-06550: line 2, column 19:
PLS-00172: string literal too long
```
We should go away from using:
```
var l_source_files   clob;
var l_test_files     clob;
```
and use:
```
var l_source_files   refcursor;
var l_test_files     refcursor;
```
Then we can generate our tmp.sql as:
```
begin
  open :l_source_files for select * from table(ut_varchar2_list(
...
));
end;
/
```
and then in our main script we would do the following:

```
if lower(l_reporter_name) in ('ut_coveralls_reporter', 'ut_coverage_sonar_reporter', 'ut_coverage_html_reporter') then
p('  v_reporter := '||l_reporter_name||'( a_file_paths => ut_varchar2_list(');
loop
  fetch :l_source_files  into l_file_path;
  exit when :l_source_files%notfound;
  p('''||l_file_path||''');
end loop;
...
```

**Comment by viniciusam** [comment]
Fixed issues you pointed, will do the improvements on file_list scripts and parse_paths function later.
