### ISSUE TITLE
Add support for multi-schema suitepath

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#243]
It would be great if we could have a multi-schema suitepath suppoer.
This way invocation of `ut.run(':com.my_company.my_project')` would invoke all tests within that suitepath regardless of schema they are in.
That would probably require a persistent annotations cache with invalidations mechanism.

**Comment by Pazus** [comment]
It breaks our base logic that schema is a topmost grouping criteria. One can still execute tests from multiple schemes providing multiple paths

**Comment by jgebal** [comment]
Abandoning this idea for now - we would need to scan entire database (all schemes) for suites!
This could take forever if a database is big enough.
