### ISSUE TITLE
Build a sample stand-alone project

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#245]
It would be great to create a sample/template stand-alone project that would do the following:
- build/install Oracle docker image using Travis
- pull and install latest version of utPLSQL from develop
- install sample project sources
- install sample project tests
- run utPLSQL sample tests

This could actually use the existing examples.
Adding this as a separate repository would be of a great value to others that want to build their own projects.
There is a large learning-curve currently involved for people that would like to run their own CI/CD for Oracle in open-source projects.

**Comment by proldan** [comment]
That's a great idea

**Comment by jgebal** [comment]
We already have an empty repo for it, if you are interested.

**Comment by jgebal** [comment]
And we could move some of our examples there.

**Comment by jgebal** [comment]
Created - https://github.com/utPLSQL/utPLSQL-demo-project
