### ISSUE TITLE
There is no way to associage tested code to the test code

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#253]
utplsql v2 was binding tested code with unit test by naming convention.
In utplsql there is no such convention/restriction and therefore it's impossible to link tested code with it's unit tests.
It makes it hard to know which unit test package(s) is (are) responsible for testing particular code.
We need to come up with a way to address that. It should be done either by naming convention or by annotations.

What I have in my head as possible options is:
- naming convention: prefix `u3_` for utplsql v3 test package names, when tests are existing in the same schema as tested code
- naming convention prefix `u3_` for utplsql v3 test schema names, when tests are existing in the same schema as tested code
- annotations:
   - `-- %for(package name)` or `-- %for_package(package name)` - on the suite level
   - `-- %for(procedure/function name)` or `-- %for_unit(procedure/function name)` - on the individual test level

**Comment by Pazus** [comment]
From practice I create a single test package per module, package or a procedure/function.

I prefer annotation approach as it more flexible, one can assign a test package to a whole package and target some  test procedures on specific procedures.

We may also include PL/Scope data and dependencies.

**Comment by Pazus** [comment]
How does java solves that? I think we should borrow ideas from our big brother.

**Comment by jgebal** [comment]
Java does not solve this, neither does Ruby.
It seems that I might be trying to solve the wrong issue. Testing frameworks do not associate tests with particular piece of tested code. This allows more flexibility as you may have many tests (packages) testing one tested code (package).
Also, tests often touch on other code (to do setup, get some reference date etc.). Associating test package with tested package may be therefore misleading.
