### ISSUE TITLE
Sonar-Scanner failing on fork builds

### ISSUE THREAD

**Issue by viniciusam** [utPLSQL/utPLSQL#255]
Builds are failing on my fork because of sonar-scanner command. I think this should be executed on main repo only.

https://travis-ci.org/viniciusam/utPLSQL/jobs/216310319
Look for "exited with 1".

> ERROR: Error during SonarQube Scanner execution
> ERROR: You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator.

A solution could be moving sonar-scanner call to after_success step (so the exit code won't afftect the build result), and check if it's on main repo.
```
if [ ! $TRAVIS_REPO_SLUG == "utPLSQL/utPLSQL" ]; then
    echo "Skipping sonar-scanner call..."
fi
```

Think this could be done for coveralls results also. If my thoughts are right, let me know so I can do a PR later.

**Comment by jgebal** [comment]
Great idea!
Make sonar Ron only on main repo

**Comment by viniciusam** [comment]
What about coveralls_uploader?
