### ISSUE TITLE
Annotations as declarative configuration of tests

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#26]
I'like to propose the way to configure tests and suites in a declarative way similar to modern OOP languages using "annotations". Let's say we have the test package like this:

```
create or replace package test_pkg is

  -- %suite(Name of suite)
  -- %suitepackage(all.globaltests)
  -- %suitetype(critical)

  -- %suitesetup
  procedure globalsetup;

  -- %suiteteardown
  procedure global_teardown;

  /* Such comments are allowed */

  -- %test(Name of test1)
  -- %testtype(smoke)
  procedure test1;

  -- %test(Name of test2)
  -- %testsetup(setup_test1)
  -- %testteardown(teardown_test1)
  procedure test2;

  -- %test(Name of test3)
  -- %testtype(smoke)
  procedure test3;

  procedure setup_test1;

  procedure teardown_test1;

  -- %setup
  procedure setup;

  -- %teardown
  procedure teardown;

end test_pkg;
```

Using annotation parsing engine Suite object with has to be constructed.
Annotations meaning:

| Annotation | Meaning |
| --- | --- |
| %suite | Marks package to be a suite with it procedures as tests. This way all testing packages might be found in the schema. Parameter of the annotation is the Suite name |
| %suitepackage | Similar to java package. The example suite should be put as an element of the "globaltests" suite which is an element of the "all" suite. This allows one to execute "glovaltests" suite which would recursively run all the child suites including this one. |
| %suitetype | The way for suite to have something like a type. One might collect suites based on the subject of tests (a system module for example). There might be critical tests to run every time and more covering but slow tests. This technique allows to configure something like "fast" testing. |
| %setup | Marks procedure as a default setup procedure for the suite. |
| %teardown | Marks procedure as a default teardown procedure for the suite. |
| %test | Marks procedure as a test. Parameter is a name of the test |
| %testtype | Another way to tag tests to filter afterwards |
| %testsetup | Marks that special setup procedure has to be run before the test instead of the default one |
| %testteardown | Marks that special teardown procedure has to be run before the test instead of the default one |
| %suitesetup | Procedure with executes once at the beginning of the suite and doesn't executes before each test |
| %suiteteardown | Procedure with executes once after the execution of the last test in the suite. |

Annotations allow us to configure test infrastructure in a declarative way without anything stored in tables or config files. Suite manager would scan the schema for all the suitable packages, automatically configure suites and execute them. This can be simplified to the situation when you just ran suite manager over a schema for the defined types of tests and reporters and everything goes automatically. This is going to be convinient to be executed from CI tools using standard reporting formats.

What do you think about such configuration approach?

**Comment by Pazus** [comment]
I suggest to add suitesetup and suiteteardown annotations for procedures to be run once before and after the whole suite opposite to setup/teardown annotations specifying the default procedures to be run before/after each test execution.

**Comment by Pazus** [comment]
I would like to note why I've chosen % sign for annotations.

In the future I assume multi line comments like /*...*/ could also contain annotations so if One uses @ sign to mark annotations sqlplus may treat it wrong trying to execute similarly named file. So as @ is a special character for sqlplus I've chosen %. Also % is used for the same markup purpose in plsqldoc.

**Comment by jgebal** [comment]
I really like the idea of allowing suite level setup and teardown.

**Comment by Pazus** [comment]
As suites can be nested with both tests and other suites we have to figure out what executes first nested suites or suite tests.

To get such situation one have to declare two suite packages with tests and set the second's suitepackage annotation to nest it in the first suite.

I believe nested suites go first, suite tests afterwards.

**Comment by jgebal** [comment]
I would make ordering of execution flexible (configurable) so that we can
have ordering by name, random, reverse order.
Not sure though if it's essential feature. It's more of a nice to have as
order of execution should have no impact on tests.

**Comment by Pazus** [comment]
Let's introduce ut_virtual_suite object type for suites not based on real packages as a logical modules. Such suites whould be used when constructing hierarchies based on the suitepackage annotation value

**Comment by Pazus** [comment]
As PR #36 is merged we have to test the developed approach and establish the next steps.

**Comment by jgebal** [comment]
I just came to think, since we allow nested suites than maybe we could use annotations called:
- before_all 
- after_all
for identifying code to be invoked before/after entire execution.

**Comment by jgebal** [comment]
Another note: don't we want to use CamelCase or snake_case for annotations?
Annotations might be hard to read without using one of those.
I'd go with snake__lower_case naming style or SNAKE_whatever_CASE

**Comment by jgebal** [comment]
One more thing that comes to my mind.
Do we need to have separate annotations `suitetype`, `testtype`?

Could we instead use one annotation named like? `test_tags`
If I want to tag a suite as 'customer_data' I can put it at suite level comment.
If i want to tag a test as 'slow' i can place it at the individual tests level.

Would that make things much more complicated and is it a good idea?

**Comment by Pazus** [comment]
> Another note: don't we want to use CamelCase or snake_case for annotations?
As PL/SQL is case insensitive I think we should follow it's style and make annotations snake_style case insensitive.

> Could we instead use one annotation named like? test_tags
I prefer simple `tags` annotion for that.

The reason why I've separated them is then `tags` annotation can contain any tag you define, it's more like a grouping attribute. If the item is marked with tag, the item and all it's subitems should be executed.

I thought suitetype should contain only predefined values to define suite type as regression, performance, smoke test or something like that. But maybe you are right and we can be fine with only `tags` annotation.

Lets just start with `tags` and find out do we need something else.

**Comment by Pazus** [comment]
No all listed annotations are supported yet. Current state:

Annotation | Describtion
------------ | -------------
%suite | Marks package to be a suite with it procedures as tests. This way all testing packages might be found in the schema. Parameter of the annotation is the Suite name. The describtion/name of the suite is provided in the argument like _%suite(Payment recognition)_. If no name parameter is provided package name is used.
%suitepackage | Similar to java package. The example suite should be put as an element of the "globaltests" suite which is an element of the "all" suite. This allows one to execute "glovaltests" suite which would recursively run all the child suites including this one. If the suite packate foo_pkg has annotation _%suitepackage(all.bar)_ then the fully qualified path of the suite package if _all.bar.foo_pkg_. This is how the suites hierarchy for the schema is formed. Executions results are also hierarhical as if any sub-suite has errors the upper suite also will be marked as failure and so on.
%test | Marks procedure as a test. Parameter is a name of the test like _%test(test engine starts)_ if no name provided procedure name is the name of the test.
%setup | Marks procedure as a default setup procedure for the tests in the suite. This procedure will be executed before each test and can be overriden. No arguments required.
%teardown | Marks procedure as a default teardown procedure for the tests in the suite. This procedure will be executed after each test and can be overriden. No arguments required.
%testsetup | Additional annotation for the procedure marked as _%test_. Specifies the setup procedure to be executed before annotated test. This value overrides the default _%setup_ procedure.
%testteardown | Additional annotation for the procedure marked as _%test_. Specifies the teardown procedure to be executed after annotated test. This value overrides the default _%teardown_ procedure.
%suitesetup | Suite setup procedure that executes at the beginning of the suite. before the first test setup.
%suiteteardown | Suite teardown procedure that executes after the suite execution after the last test teardown.

**Comment by Pazus** [comment]
Annotations support two ways to provide parameters:
%annotation(param1,param2)

or
%annotation(key1 = param1, key2 = param2)

All the commas and brackets in the parameters right now are treated like seporators and the end of the parameter list, No escaping is supported yet.

Also single procedure can have multiple annotations that all combine there logic like:

```
%test(foo-valued test)
%testsetup(foo_setup)
procedure foo;

procedure foo_setup;
```

**Comment by jgebal** [comment]
Great description @pazus.
@rlove This might be worth placing in documentation
Looking at the description of organizing suites and sub-suites I have a question.
Is it possible to have a suite setup for a grouping suite?
say we have a package like:
```
package foo_pkg ...
  --%suite(foo)
  --%suitepackage(all.bar)

  --%suitesetup
  procedure foo_setup;

  --%suitesetup(bar)
  procedure bar_setup;

  --... tests go here

end;
```
or packages like:
```
package foo_pkg ...
  --%suite(foo)
  --%suitepackage(all.bar)

  --%suitesetup
  procedure foo_setup;
  --... tests go here
end;

package bar_pkg 
  --%suite(bar)
  --%suitepackage(all)
  procedure bar_setup;
end;
```

Would the `suitesetup(bar)` be picked up as a setup for bar group suite in the first case?
I believe it would be in the second case
So the execution flow would be:
```
start
  global setup
    bar
      bar setup
        foo_pkg
          foo_pkg setup
          foo_pkg tests
...
```

**Comment by Pazus** [comment]
Yes @jgebal it would. The way you presented is exctly the way I planned it to be:

```
package foo_pkg ...
  --%suite(foo)
  --%suitepackage(all.bar)

  --%suitesetup
  procedure foo_setup;

  --... tests go here
end;

package bar_pkg 
  --%suite(bar)
  --%suitepackage(all)

  --%suitesetup
  procedure bar_setup;

  --tests can also go here
end;
```

**Comment by Pazus** [comment]
Oops! Correction! Package path is based on the package names as the `%suite` annotation contains human readable name with spaces. So it has to be
```
  --%suite(foo)
  --%suitepackage(all.bar_pkg)
```

**Comment by jgebal** [comment]
Can we clearly define what will happen in follwoing cases:
- when --% annotation is defined more than once, then the last VALID definition is taken into account, so that defining in two consecutive lines: `--%suite(foo)` and `--%suite(bar)` would result in a suite `bar`
- when a loop will occur in suite nesting like: %suite(foo.bar.foo) then the suite is reported as invalid and it is skipped

**Comment by jgebal** [comment]
can we make the `--%` syntax part of configuration, or at least extract it into a constant for now?

**Comment by Pazus** [comment]
1) agree. I'll make a PR for it
2) agree, but will take some time...
3) agree. Currently supported annotations should be presented as constants in `ut_annotations` package. I'll make a PR.

**Comment by jgebal** [comment]
If we change the name of `%suitepackage` to `suitepath` we could nest suites in single package.
As a rule we could say that test procedures defined under a suite in package are assigned to that suite.

```
package customers_pkg ...
  --%suite(customers)
  --%suitepath(all)

  --%suite(add_customer)
  --%suitepath(all.customers)

  --%test(Add customers fails on duplicate_key)
  procedure add_customer_fail;

  --%test(Add customers saves customer data to table)
  procedure add_customer_success;

  --%suite(get_customer)
  --%suitepath(all.customers)

  --%test(returns no data when customer not found)
  procedure get_customer_fail;

  --%test(returns no data when customer not found)
  procedure get_customer_success;

end;
```

One thing that I'm wondering about is:
Do we need to specify full suite path or just the parent suite?
```
  --%suite(add_customer)
  --%suitepath(all.customers)
```

or maybe just:
```
  --%suite(add_customer)
  --%suitepath(customers)
```
