### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by viniciusam** [utPLSQL/utPLSQL#269]
There is a broken link on coverage user guide.

> You may see a sample of code coverage for utPLSQL project here

Points to (404):
https://jgebal.github.io/utPLSQL-coverage-html/

**Comment by jgebal** [comment]
That should be repointed to be:
https://utplsql.github.io/utPLSQL-coverage-html/
We also should probably push the html results of coverage on every build from develop branch into that repo.

**Comment by jgebal** [comment]
resolved by #270
