### ISSUE TITLE
Improve file mapping API to make it easier to use by consumers

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#279]
We should redesigning API for reporters. Current solution, were we are passing parameters to reporter constructor (file mapping) makes API usage complex. Each reporter can have different constructor and this makes API hard to integrate.

I'm thinking of two options:
1. Make a set of abstract procedures `init` to initialize the file mappings/file lists in the `ut_reporter_base` class. This way that every reporter would need to implement it and the API for invoking reporters would become consistent by rule. The downside of this approach however is that many reporters would need to implement the `init` procedures with NULL implementation if the procedure is not relevant. Also, many reporters would end up having duplicated implementation for the `init` procedures (as it is currently with constructors).
2. Extend the `ut_runner.run` and `ut.run` to accept the file mappings/file lists. This sounds better solution as the parameters would become part of `ut_run` object and could be consumed by any reporter according to it's needs.

I lean towards solution number 2.
The `run` procedures in `ut` and `ut_runner` packages would be extended by 2 optional parameters: `a_source_file_mappings, a_test_file_mappings`
The mapper would be made available to API consumers so that we would still have three different ways to build file mappings:
1. by providing full mapping of file to db object
2. by building mapping using just file names and relying on default mapping rules
3. by building mapping using custom regex rules to parse filename/path and determine database object from it

We should perform the refactoring as soon as possible so we minimize the impact on the work getting cone on the utPLSQL-java-aip project.

**Comment by viniciusam** [comment]
Sounds good. But the mappings will be used on every run, independently of the reporter used?

**Comment by jgebal** [comment]
The mappings would be optional parameters to the `run` procedures.
If however we try to use one of reporters that requires file list/file mapping, we could do one of following:
- throw an exception
- provide error message as the output of reporter
- provide empty output from reporter (not really nice as user will have no clue why there was no output)

The message could be something like:
`No file list was provided for the run. ut_....reporter requires file list in order to provide outputs`
Not sure which option would be better. 
Should we fail early on bad configuration or run tests anyway, as there might be another reporter in use and the error therefore is not critical.

**Comment by jgebal** [comment]
To your question @viniciusam 
The mappings would be defined for a run (optionally)
The mappings would be held (or not held) by reporter individually (as a field in reporter object)
It would be up to reporter implementation what it will do with mappings when the `init` is called internally on the reporter by `ut_runner.run` procedure

**Comment by jgebal** [comment]
Just to add to the reasons behind all the idea.
I'd like to avoid situation, where API consumers hardcode conditions like:
if using `ut_sonar_coverage_reporter` then `use the file list`
if using `ut_documentation_reporter` then `use color console flag` 
etc.
If all of the run config is passed once (to the ut.run), API consumers don't have to differentiate between constructor parameters for reporters.

**Comment by viniciusam** [comment]
I think is better to let the user know it failed, before it runs (Exception).

> I'd like to avoid situation, where API consumers hardcode conditions like:
>if using ut_sonar_coverage_reporter then use the file list
>if using ut_documentation_reporter then use color console flag
>etc.

That makes sense!
