### ISSUE TITLE
Active autonomous transaction detected

### ISSUE THREAD

**Issue by viniciusam** [utPLSQL/utPLSQL#285]
When calling the ut_reporter_buffer.get_lines function from java, I get the following error:

`Failed tests:   getLinesFromOutputBuffer(io.github.utplsql.OutputBufferTest): ORA-06519: active autonomous transaction detected and rolled back(..)`

[https://travis-ci.org/utPLSQL/utPLSQL-java-api/builds/223761659](url)
line 1665

Maybe is the case of finishing the transaction after reading the buffer lines.

**Comment by jgebal** [comment]
Should be fixed by #286

**Comment by jgebal** [comment]
Can you switch to use utPLSQL@develop on the Java project for now?
I don't want to build new release with every bug fix.
