### ISSUE TITLE
Code Coverage do not collect data from other schemas

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#287]
Hi guys , I've been started to playing about with that version , however I cannot make a coverage work to collect data from other schema.

E.g. I have a test user called A and create a test package in that schema that calls the actuall tested package in schema B. Regarding of the priviliges I granted to user A (create any, execute any proc) the coverage still cannot collect data from schema B code.

**Comment by jgebal** [comment]
I guess you do have coverage, just cannot look into the source code in the HTML report.
Is that right?
Can you try to run sonar/coveralls coverage reporter and see if you get the coverage outputs?

We are currently using `all_source` to fetch the sources for `ut_coverage_html_reporter`. Therefore the user running the tests needs to see code in all_source.

I'll try to reproduce the issue you're facing and then introduce some solution for it.

**Comment by lwasylow** [comment]
Yes correct, I have checked profiler tables and all execute lines are captured just HTML do not show source.
I was guessing that issues was probably to using all_ views but is nice to confirm.
On other hand nice enhancment would be to add to drill into package on code coverage split into modules as a quick goto (procedure, function etc.) I have done something when using coverage for mine but with mine code had issues with coverage correctly recognizing a lines used when SELECT went over mutliple lines which with your version all seems to be working well.

**Comment by jgebal** [comment]
If you look at this example coverage:
https://utplsql.github.io/utPLSQL-coverage-html
You will see the search box that allows you to search by object name.
The enhancements to the coverage html report are nice to have but of a low priority at the moment as there is still quite few things to be done with the project core.

**Comment by jgebal** [comment]
The project is open source, so if you feel like you want to contribute to the reporter, feel free to do so.
The syntax highlighting is also poor at the moment, but we need someone with JS skills to handle this and it's also of a low priority at the moment.

**Comment by jgebal** [comment]
@lwasylow 
Seems like we mainly have a bug in documentation.
According to [Oracle doc for DBMS_PROFILER](https://docs.oracle.com/cd/E18283_01/appdev.112/e16760/d_profil.htm)

#Security Model

> **The profiler only gathers data for units for which a user has CREATE privilege**; you cannot use the package to profile units for which EXECUTE ONLY access has been granted. In general, if a user can debug a unit, the same user can profile it.

Having that knowledge. In order to gather coverage on packages not owner by user **executing** the tests, the user needs to have CREATE ANY PROCEDURE system privilege granted.

Currently (as just discovered) you also will need to have EXECUTE ANY PROCEDURE in order to be able to successfully make use of the CREATE ANY PROCEDURE privilege for coverage reporting.
There will be soon a fix for that, so that only the CREATE ANY PROCEDURE will be needed.

**Comment by lwasylow** [comment]
Hi Jacek
I believe issue is coming out of that line 
package : ut_coverage.get_coverage_data line : 278 l_schemas name.
When that schemas is passed to function get:
execute immediate get_sources_query() using l_schema_names, l_skipped_objects, g_include_list;

Because by default that schema list is a USER schema it filters out results  later on 
where s.owner in (select upper(t.column_value) from table(:l_schema_names) t)';

The grants are not really matter as data are collected but not presented in HTML

I have managed to do a workaround by calling with expicit list of schemas e.g.:
exec ut.run(ut_varchar2_list('UT_TEST','CBSSERVICES','CCSOWNER'),ut_coverage_html_reporter());

However it woudl be good if it would get a source coverage for all called code from main code.
I know it then present itself a challenge about SYS objects etc.

**Comment by SebGt** [comment]
What is the solution Jacek ?
Because without the workaround given by Iwasylow in above comment my coverage result is empty.
I am in the same context than described in this issue (I'm using V3.0).

Thanks

**Comment by lwasylow** [comment]
The latest dev version have a fix, you define a additional schemas in type
a_coverage_options.
