### ISSUE TITLE
The demo package from readme.md does not compile

### ISSUE THREAD

**Issue by scanbix** [utPLSQL/utPLSQL#289]
Compilation errors for PACKAGE BODY UT3.TEST_BETWEEN_STRING

```
Error: PLS-00103: Encountered the symbol ")" when expecting one of the following:
:= . ( % ;
       The symbol "(" was substituted for ")" to continue.
Line: 5
Text: ut.expect( betwnstr( '1234567', 2, 5 ) ).to_equal('2345') );
```

The error hapens in the package body at UT.EXPECT[...]
```
 procedure normal_case is
  begin
    ut.expect( betwnstr( '1234567', 2, 5 ) ).to_equal('2345') );
  end;
```

**Comment by scanbix** [comment]
And then after fixing the clause, I think the function "betwnstr" is missing.

**Comment by jgebal** [comment]
Good catch. 
The readme should point to [examples directory](https://github.com/utPLSQL/utPLSQL/tree/develop/examples/between_string) or to the [utPLSQL-demo-project](https://github.com/utPLSQL/utPLSQL-demo-project) that I have set up recently.
Needs to be fixed.
