### ISSUE TITLE
Executing ut.run(); results in ORA-24241: source text is in wrapped format

### ISSUE THREAD

**Issue by TomasPuk** [utPLSQL/utPLSQL#292]
Executing ut.run(); results in ORA-24241: source text is in wrapped format

**Comment by jgebal** [comment]
Please provide:
- full error stack trace
- database version
- exact options of execution
- information about spec/body of packages that are wrapped/obfuscated in your project

**Comment by TomasPuk** [comment]
**Error Stack Trace:**
ORA-06512: at "SYS.DBMS_PREPROCESSOR", line 84
ORA-06512: at "SYS.DBMS_PREPROCESSOR", line 195
ORA-06512: at "UT3.UT_METADATA", line 121
ORA-06512: at "UT3.UT_ANNOTATIONS", line 345
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 68
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 278
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 329
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 490
ORA-06512: at "UT3.UT_RUNNER", line 38

**Database Version:** 
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit

**Executed Script:**
```
begin
  ut.run();
	exception when others then
		dbms_output.put_line(dbms_utility.format_error_stack);
end;
```

I guess the issue is in following cursor present in ut3.ut_suite_manager. This cursor is taking wrapped packages into account as well. 
```
    for rec in (select t.owner
                      ,t.object_name
                  from all_objects t
                 where t.owner = a_owner_name
                   and t.status = 'VALID' -- scan only valid specifications
                   and t.object_type in ('PACKAGE')) loop
```

**Comment by TomasPuk** [comment]
And both - the package body and package specification are wrapped.

**Comment by jgebal** [comment]
The annotation suite manager or annotation parser or best both should skip scan if package spec is wrapped.
Thanks @TomasPuk , always something new to discover.

**Comment by jgebal** [comment]
@TomasPuk, can you try now with source code from develop branch?
A new release should come soon.

**Comment by TomasPuk** [comment]
Its working fine right now. Thanks :)
