### ISSUE TITLE
Update Sourceforge to refer people to GitHub

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#3]
The project needs to be left on Sourceforge for historical purposes (it might even be impossible to remove it anyway), but it needs updating so people know to come here for it now. It will also lend credibility to this being the new official home of the project if the old home refers to it.

**Comment by rlove** [comment]
sf.net Website and hosted documentation now have redirects to the current site.

http://utplsql.sourceforge.net/ -> https://utplsql.github.io/

utplsql.sourceforge.net/Doc/*.html -> https://utplsql.github.io/docs/index.html
