### ISSUE TITLE
UTAssert package not found on installation of  UTPLSQL Version 3.0.0.0-Alpha1 released

### ISSUE THREAD

**Issue by indumurali** [utPLSQL/utPLSQL#301]
I am beginner to UTPLSQL. Downloaded the UTPLSQL version 3.0.0.0-Alpha1, but utPLSQL, UTAssert packages needed are missing. Please someone help me with the correct version where the above stated packages are available for use.

Many thanks

**Comment by jgebal** [comment]
Hi @indumurali 
Why do you expect to see `utassert` and `utplsql` packages in utplsql v3?
Have a look at v3 documentation here: https://github.com/utPLSQL/utPLSQL/blob/v3.0.0-beta/docs/index.md

Also, better use beta than alpha.

**Comment by jgebal** [comment]
no response - closing
