### ISSUE TITLE
The source code zips on the releases pages are empty directories

### ISSUE THREAD

**Issue by paytonrules** [utPLSQL/utPLSQL#318]
The official releases appear to be the proper size, but the source code zip files are empty.

**Comment by jgebal** [comment]
This is because, the sources are not "tagged" with version number.
We would rather not have users install from sources as it will be difficult to support.
They will not be able to tell what version they have.
To use sources from repo use `git clone https://github.com/utPLSQL/utPLSQL.git`

**Comment by jgebal** [comment]
We should have next release shortly
