### ISSUE TITLE
running tests in a user containing '$'

### ISSUE THREAD

**Issue by ansgar-d** [utPLSQL/utPLSQL#331]
We have installed our database-users to use operating-system-identification. I guess using the '$' sign is a normal usage in realtion to this mechanism.

But when we start a test let's say ut.run('ops$bookkeeping') we get a format error. Is it not possible to use such user? 

Thanks for the great work of the new version!

**Comment by jgebal** [comment]
Please provide full stack trace f the error you get and database version

**Comment by ansgar-d** [comment]
Thanks for the quick answer!

Connected to Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 
Connected as ops$psb@PSB600.PSB
 
SQL> set serveroutput on
SQL> exec ut.run('ops$psb');
 
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 383
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 468
ORA-06512: at "UT3.UT_RUNNER", line 76

ORA-20202: Invalid path format: ops$psb

 
begin ut.run('ops$psb'); end;
 
ORA-20202: Invalid path format: ops$psb
ORA-06512: at "UT3.UT_RUNNER", line 87
ORA-06512: at "UT3.UT_RUNNER", line 111
ORA-06512: at "UT3.UT", line 292
ORA-06512: at "UT3.UT", line 320
ORA-06512: at line 2
 
SQL>

**Comment by jgebal** [comment]
Thanks for the details,
It will be fixed in version 3.0.1
