### ISSUE TITLE
Easier setup/cleanup with generated table API's for UT's

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#333]
The biggest pain of unit testing of database code is setup and cleanup of data fo tests.
That could be made easy if we use/recommend using  something like [table-api-generator](https://github.com/OraMUC/table-api-generator)

I've raised few requests on that project. Once accepted and implemented, we could start doing demos and recommending that library for common data setup/cleanup.

**Comment by lwasylow** [comment]
I think issue with data setup is they they are very unique to each business , database etc. 
I'm not entirely convinced that it can be generalised for every purpose.
Also In my opinion the big advantage of the utplsql3 is the simplicity of writing test and code. 
As soon as you write a complex code you will need to test for your test etc.
As long as this is separated and optional from test that would be fine and can prove usefull in certain scenarios, however I think that should remain optional.

**Comment by jgebal** [comment]
Closing at it is not directly related to the framework itself.
