### ISSUE TITLE
Redefine reporters hooks

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#35]
I'd like to propose to redefine reporters hooks a bit to:

1. before_execution (before the schema execution of all the suites in the schema)
2. before_suite_begin
3. after_suite_begin
4. before_test
5. before_asserts_process
6. on_assert
7. after_asserts_process
8. after_test
9. before_suite_end
10. after_suite_end
11. after_execution

The mote detailed hooks would be, the better reporting solutions can be built.

**Comment by jgebal** [comment]
Really good idea.

**Comment by Pazus** [comment]
I played around a bit with new hooks and figured out that we need to think a bit more about them. For example I realized that before_suite_end and after_suite_end are in fact the same as nothing happens in between. What do you think?

I've also added some new like on_suite_setup, on_suite_teardown

The current list is here: https://github.com/Pazus/utPLSQL/blob/reporter-hooks/source/types/ut_reporter.tps

**Comment by Pazus** [comment]
Naming style... I'm not sure I still like "before_suite" more then "begin_suite"...

**Comment by jgebal** [comment]
I honestly do not like the begin_suite/end_suite, and same as you @Pazus I prefere before/after.
The main reasoning behind it is that:
begin_aaaaa fits more to the label or comment in code to indicate where the aaaaa starts.
before_aaaaa is more appropriate. It says that the code that I'm implementing as a before_aaaaa method, will be executed just before the aaaaa. Therefore the naming before/after is more accurate.

**Comment by jgebal** [comment]
I looked at the proposed specification of reporter hooks.

Generally I think we should have hooks (that are optionally implementable) around any test building block.

before_all
after_all
before_suite 
after_suite 
before_setup (for: all/suite/test level)
after_setup (for: all/suite/test level)
before_teardown (for: all/suite/test level)
after_teardown (for: all/suite/test level)
before_test
after_test

I'm not sure about asserts though. Asserts seem to be internals of the tests.
If we want to be able to do timing on individual asserts or indicate/measure progress for some really slow test than maybe we should have before/after assert too.

The only concern I have is that we probably would need to call the hooks from each assertion, which makes them not so clean. Unless we go with approach of implementing assertions as objects too. I'm not sure if this is the right way to go right now.

I'd start without hooks on assertions, unless we have non-invasive approach on how to do it nicely.

**Comment by Pazus** [comment]
On asserts hooks mightbe implemented no on the assertion itself but rather on assertion result processing. I mena I run test, as a result I have a bunch of assert results in the package collection. Then I copy them to the test as it's items and iterate through them executiong reporter hook.
I also think we have to add before/after assertions processing (before copy assertion array from package variable to the items array of the test and after result of the test is calculated) hook to your list even if we don't implement on_assert_process hook.

**Comment by Pazus** [comment]
I propose to rename "all" to "run"

**Comment by Pazus** [comment]
@jgebal I realized I have problems with this hierarchy... what hook triggers before suite item is executed? The item might be test or suite. I think there has to be a hook for that: before_suite_item, after_suite_item triggered by suite_level passing suite and item index as parameters.

Here is what I come to:
For a suite
```
before_suite

  before_setup -- (if setup proc is provided)
  after_setup -- (if setup proc is provided)

  before_suite_item
  after_suite_item

  before_suite_teardown -- (if teardown proc is provided)
  after_suite_teardown -- (if teardown proc is provided)

after_suite
```

For a test:
```
before test

  before_test_setup
  after_test_setup

  before_test_execution
  after_test_execution

  before_test_teardown
  after_test_teardown

  before_test_processing
  after_test_processing

after_test
```

For a whole run:
```
before_run
after_run
```

**Comment by Pazus** [comment]
Here is the implementation: https://github.com/Pazus/utPLSQL/tree/reporter-hooks

**Comment by jgebal** [comment]
@pazus I like the proposed solution.
I would only suggest renaming of hooks:
```
  before_test_processing
  after_test_processing
```
to something like
```
  before_test_results_processing
  after_test_results_processing
```

**Comment by Pazus** [comment]
I've renamed it to 
```
before_asserts_process
on_assert_process
after_asserts_process
```
