### ISSUE TITLE
ut.run - ORA-22921

### ISSUE THREAD

**Issue by pocelka** [utPLSQL/utPLSQL#352]
Downloaded the latest version, however when running sample test, I'm getting ORA-22921. 
`c:\Downloads\X2\utPLSQLv3.0.0\examples\between_string>sqlplus user/pass@db@run_betwnstr_test.sql 

SQL*Plus: Release 11.2.0.3.0 Production on Wed Jun 14 17:20:54 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Data Mining and Real Application Testing options

Function created.

Package created.

Package body created.

ORA-06512: at "SYS.DBMS_LOB", line 1146
ORA-06512: at "UT3.UT_UTILS", line 327
O
ORA-22921: length of input buffer is smaller than amount requested

BEGIN ut.run(user||'.test_betwnstr'); END;

*
ERROR at line 1:
ORA-22921: length of input buffer is smaller than amount requested
ORA-06512: at "UT3.UT_RUNNER", line 87
ORA-06512: at "UT3.UT_RUNNER", line 111
ORA-06512: at "UT3.UT", line 292
ORA-06512: at "UT3.UT", line 320
ORA-06512: at line 1

Package dropped.

Function dropped.`

Seems like fix in #348 was only partiall and overload procedure append_to_clob was forgotten. Changing lenght to dbms_lob.getlength helped.

**Comment by jgebal** [comment]
If you are using the release v3.0.0, the fix is not there.
The fix is inly present in develop branch - not yet released.

**Comment by pocelka** [comment]
Ah OK. I downloaded the latest version. 

So this might be an issue.

**Comment by jgebal** [comment]
We are waiting for one more fix to be merged before releasing v3.0.1
