### ISSUE TITLE
Update Documentation - Annotation Section

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#357]
Annotation -- %suitepath cannot have a whitespace after it.

Please update documantation.

Also there seems to be incosistency as the whitespace is allowed on annotation of test etc.

**Comment by Pazus** [comment]
Hi, @lwasylow 

Could you provide and example of a broken annotation?

**Comment by lwasylow** [comment]
Hi Pazus
Generally I think issue is that approach is not consistent.When using a suitepath annotation it causes an error that tells about null index rather than highlight syntax issues.
On the other hand a displayname annotation when provided with whitespace results in no error just dont display a test name on result.

E.g.
%suitepath (alltests.test_setup)

In my opinion I think the approach should be a consistent so regexp should be modified to throw error when whitespace is found with Syntax error info.
