### ISSUE TITLE
For different schema names ut_coverage_html_reporter() not generating coverage data.

### ISSUE THREAD

**Issue by shrinathgurav** [utPLSQL/utPLSQL#358]
As suggested in documentation code coverage information is not getting generated 
_exec ut.run('ut3_utplsql.test_award_bonus', ut_coverage_html_reporter(), a_coverage_schemes=>ut_varchar2_list('ut_demo'));_

Both users have dba role and all object level privileges granted.

only default information is there no code coverage information generated.
[coverage.txt](https://github.com/utPLSQL/utPLSQL/files/1083266/coverage.txt)

**Comment by jgebal** [comment]
Hi @shrinathgurav,
This was already fixed in #326 
The fix is part of release [v3.0.1](https://github.com/utPLSQL/utPLSQL/releases/tag/v3.0.1)
Please use utPLSQL v3.0.1 and the feature will work as expected.

**Comment by jgebal** [comment]
@shrinathgurav 
Can you validate and close the issue?

**Comment by shrinathgurav** [comment]
@jgebal : Apologies for delayed reply.
  I have validated it. It is working as expected.
Thank you.
