### ISSUE TITLE
windows download script -enhancement

### ISSUE THREAD

**Issue by pocelka** [utPLSQL/utPLSQL#360]
I have tried like two days to understand how git works. Got the basics, then wanted to install git on my work PC and something went wrong. Then read contribution guide about branching and got totally lost. 

I'm sorry but it is easier just to post it here.

I wanted to the the following change in "install.md":

For Windows systems with Powershell installed (i.e. Windows 10) the following snippet can be used to download latest version of utPLSQL:
```
$archiveName = 'utPLSQL.zip'
$latestRepo = Invoke-WebRequest https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest
$repo = $latestRepo.Content | Convertfrom-Json

$urlList = $repo.assets.browser_download_url

foreach ($i in $urlList) {

   $fileName = $i.substring($i.LastIndexOf("/") + 1)

   if ( $fileName.substring($fileName.LastIndexOf(".") + 1) -eq 'zip' ) {
      Invoke-WebRequest $i -OutFile $archiveName
      unzip -q $archiveName
   }
}
```

**Comment by jgebal** [comment]
Hi @pocelka 
Nice script.
I'll test it on Windows 7 (after [installing PowerShell 3.0](https://blogs.technet.microsoft.com/heyscriptingguy/2013/06/02/weekend-scripter-install-powershell-3-0-on-windows-7/)) and will let you know how it goes.

**Comment by pocelka** [comment]
Sure give it a try. I don't have exactly Windows 7 laying around to test it on all machines. Just tested it on home and work PCs with W10 which has default version 5.0.

Win7 has I think default PS version 2.0, while "invoke-webrequest" was added in 3.0. Anyway, powershell was open sourced few months back and now can be installed also on Linux.

**Comment by jgebal** [comment]
OK.
We can put this into the doc with two comments on prerequisites:
1. You need `PowerShell 3.0` or above installed
2. You need to have `unzip` installed on your windows
Otherwise, you need to adopt the script according to what you have installed on your system.

**Comment by pocelka** [comment]
@jgebal 
Can you try this version? Dependecny on PS version is the same but unzip does not have to be installed. However you will have to have .NET 4.5 framework instead.

```
$archiveName = 'utPLSQL.zip'
$latestRepo = Invoke-WebRequest https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest
$repo = $latestRepo.Content | Convertfrom-Json

$urlList = $repo.assets.browser_download_url

Add-Type -assembly "system.io.compression.filesystem"

foreach ($i in $urlList) {

   $fileName = $i.substring($i.LastIndexOf("/") + 1)

   if ( $fileName.substring($fileName.LastIndexOf(".") + 1) -eq 'zip' ) {
      Invoke-WebRequest $i -OutFile $archiveName
      $fileLocation = Get-ChildItem
      [io.compression.zipfile]::ExtractToDirectory($($fileLocation.FullName),$($fileLocation.DirectoryName))
   }
}
```

**Comment by jgebal** [comment]
got the following error (sorry for polish text - using Widows 7 PL x64)
It says:
`File path, file name or both are too long. Fully qualified name must be less than 260 chars and dir name 248 chars.`
```
Exception calling "ExtractToDirectory" with "2" argument(s): "Określona ścieżka, nazwa pliku albo oba te parametry są
za długie. Długość w pełni kwalifikowanej nazwy pliku musi być mniejsza niż 260 znaków, a nazwy katalogu mniejsza niż
248 znaków."
At line:6 char:80
+       [io.compression.zipfile]::ExtractToDirectory($($fileLocation.FullName),$($ ...
+                                                                                ~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
```

**Comment by pocelka** [comment]
Can you post directory from which you executed script? I will try to simulate it on my end. Might be an issue with with special characters.

Did you change anythin in the script? i.e. $archiveName variable?

**Comment by jgebal** [comment]
I didn't change anything in the script. Executed it directly from PowerShell.
Script executed from: `C:\Users\Jacek`
Can you add some echo/debug messages to the script?

**Comment by jgebal** [comment]
Odd. It worked well from: `C:\Users\Jacek\aa`

**Comment by jgebal** [comment]
Seems like executing from my home directory causes the script to fail.

**Comment by pocelka** [comment]
Should be correct now. 

I did not realize that get-childitem (or ls) actually returns whole folder content including directories.

```
$archiveName = 'utPLSQL.zip'
$latestRepo = Invoke-WebRequest https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest
$repo = $latestRepo.Content | Convertfrom-Json

$urlList = $repo.assets.browser_download_url

Add-Type -assembly "system.io.compression.filesystem"

foreach ($i in $urlList) {

   $fileName = $i.substring($i.LastIndexOf("/") + 1)

   if ( $fileName.substring($fileName.LastIndexOf(".") + 1) -eq 'zip' ) {
      Invoke-WebRequest $i -OutFile $archiveName
      $fileLocation = Get-ChildItem | where {$_.Name -eq $archiveName}

      if ($fileLocation) {
         [io.compression.zipfile]::ExtractToDirectory($($fileLocation.FullName),$($fileLocation.DirectoryName))   
      }
   }
}
```

**Comment by jgebal** [comment]
Nice work,
Thanks @pocelka

**Comment by Shoelace** [comment]
you can use `Get-ChildItem -File` to only get files (and not directories)
