### ISSUE TITLE
Install script gives SP2-0317

### ISSUE THREAD

**Issue by safokkens** [utPLSQL/utPLSQL#365]
I'm using the headless installer, but I think the problem is alse reproducable by running install.sql

When running the script I receive an error SP2-0317, this is caused by "SET DEFINE &". When I replace this line with "SET DEFINE '&' ", the script runs fine.

**Comment by jgebal** [comment]
I've noticed the same recently.
It is fixed and waiting for approval with few other improvements to install scripts in #362.
Should be part of  v3.0.2

**Comment by jgebal** [comment]
Resolved by #362
