### ISSUE TITLE
anotation %disabled vs docs description

### ISSUE THREAD

**Issue by pocelka** [utPLSQL/utPLSQL#374]
For %disabled anotation document says:
```
%disabled	Package/procedure	Used to disable a suite or a test. Disabled suites/tests do not get executed, they are however marked and reported as disabled in a test run
```

When this notation is placed on the suite level package is not reported as disabled.

Settings:
```
   -- %suite
   -- %displayname(Asset Area Test Cases)
   -- %rollback(manual)
   -- %disabled
```

Output:
```
Asset Area Test Cases

Finished in .001963 seconds
0 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)
```

Per documentation description, I would expect for the suite level same output as for disabled individual test cases (or something similar):
```
Asset Area Test Cases
  Hard Suspend - Check duration period in CDM table (IGNORED)
  Hard Suspend - Check reasons in CDM table (IGNORED)

Finished in .002464 seconds
2 tests, 0 failed, 0 errored, 2 disabled, 0 warning(s)
```

Maybe docs are not exact for the suite level?

**Comment by jgebal** [comment]
Looks like a bug.
We should report all the tests and all of them should be disabled.
Good catch @pocelka 

You already have a test case to reproduce the issue, would you be willing and able to provide a bugfix?

**Comment by pocelka** [comment]
Willing yes, but be able probably not. 

The thing is that:
- I'm still trying to understand basics for utPLSQL. I haven't look on the code yet, but there is quite a lot code to cover to understand what is doing what and where it could be fixed. There are also several type objects; area which I used in my professional carreer only causally - not a lot of experience in this are.
- Our project is going live in less than 2 weeks and then it will be quite stressful time.
