### ISSUE TITLE
order of testsuites

### ISSUE THREAD

**Issue by dsnz** [utPLSQL/utPLSQL#419]
Hello,

what's the order of running the testsuites ?
my guess is that it's alphabetic and not by create time
can I control it with code/options ?

**Comment by Pazus** [comment]
Hi @dsnz!

Currently tests are executed in the order they are defined in the test package. Suites are executed alphabetically + heirarchically by suite path.

**Comment by Pazus** [comment]
Feel free to ask any questions or advices using our Slack chat: https://utplsql.slack.com

**Comment by dsnz** [comment]
yes, this is what I found about suite order, so I guess it cannot be managed by some way currently

**Comment by Pazus** [comment]
The idea is that you shouldn't otherwise your tests become bot isolated enough. The results shouldn't on the order of suite/tests execution. 
All the setup/cleanup is done by the framework and everything needed is prepared before the test invokation.
