### ISSUE TITLE
Add optional  statspack report generation to deployment

### ISSUE THREAD

**Issue by mathewbutler** [utPLSQL/utPLSQL#423]
Installation times differ greatly depending on target DB version. Diagnosing this is difficult without additional data. For licensing reasons the project uses SE Oracle which precludes using AWR. An alternative is to use statspack which is the previous incarnation of AWR and I may be used on all DB editions. 

- optional install of statspack from @?/rdbms/admin/secretary (?) into a separate user
- possible changes to statspack settings
- take a snap() before utPLSQL install
- another snap() after install 
- report on these two snaps
- output to log for analysis

**Comment by Shoelace** [comment]
is this just for utplsql development purposes ? or something that would be installed at client sites?

**Comment by jgebal** [comment]
I assumed that it would be dev-only.
We already  used mystats package with old tests.
With new tests we can only use session trace.
We also run profiler so that could help a bit.

**Comment by mathewbutler** [comment]
It was for dev only. At the time there were problems with deployment and little means to diagnose and this was one thing that could have helped. In the end we used session trace. 

I think this could be closed. Agree?

**Comment by jgebal** [comment]
Agreed - closing.
