### ISSUE TITLE
Finish ut.run without active transaction

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#441]
When tests are executed on the first savepoint creation transaction is initiated. After rollback to that savepoint issued the transaction remains active even though it contains no changes and IDEs offer to rollback/commit changes. 

I propose to check if no transaction is active at the start of execution and rollback (complete rollback) at the end of the run.

**Comment by jgebal** [comment]
Good idea!

**Comment by jgebal** [comment]
I wondr how IDE's like SQL Developer detect an open and uncommitted transaction.
I guess they use `dbms_transaction`

**Comment by mathewbutler** [comment]
This is the supported means to identify this. 

Tweet thatjeffsmith if you want a definitive answer. That or 10046 trace your SQLDeveloper session 😀
