### ISSUE TITLE
Generate technical documentation from plsql-code 

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#444]
We should start using `https://github.com/OraOpenSource/plsql-md-doc`
Generating cods into markdown allows for easy conversion into various flavours of html.
We can then publish the tech doc along with project doc.

Here is an example of generated documentation:
http://oos-utils.readthedocs.io/en/latest/README/

**Comment by lwasylow** [comment]
Can this be run on serve

**Comment by pocelka** [comment]
Might be worth looking also on:
[https://github.com/ogobrecht/ploc](url)

**Comment by jgebal** [comment]
We will drop the idea of java-doc style code documentation.
It's massive effort, hard to maintain, even harder to make it meaningful and useful.
