### ISSUE TITLE
Add ability to report only the rows that are different

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#454]
## Ability to report only the rows that are different
---------------------
Currently we simply display first N rows form both cursors if the data is not matching.

This is not very useful for developers, specially when dealing with more than few columns and few rows of data.

`ut_data_value_refcursor` should implement some kind of diff report, that would:
- only report on rows that are actually different
- display mismatching rows side by side or one under another so we can see one expected row, one actual etc.

As an idea, when running the `compare_implementation` method, we could save the results (or data-keys) of both compared cursors into separate diff table so that we can then simply query diff table joined with cursor data table (twice) to get differences and the diff data.

It would be worth doing a bit of research on was to do Diff.
There is a nice open-source algorithm for text-based diff:
https://neil.fraser.name/software/diff_match_patch/svn/trunk/demos/demo_diff.html
https://github.com/curran/google-diff-match-patch

RSpec and git command line have a line by line diff implementation too, that could be more suitable here.

**Comment by mikechip1980** [comment]
as far as I understand, the comparison now is implemented by transformation Cursor to XML.
In case of difference we can see only first several rows of the source XML which useless for subsequent analisys. I absolutely agree that this feature should be changed and the output with the difference (like in other Expectations API) would be much more useful.
As variant, XMLDIFF oracle function could be used
https://docs.oracle.com/cd/B28359_01/server.111/b28286/functions229.htm#SQLRF20025
It has 2 XMLs as input parameters for comparison and output XML with detail difference information.

**Comment by jgebal** [comment]
Xmldiff would be a good starting point.
The outcomes of diff are however ... well ... ugly.
We would need to transform that into something human-readable.
It's simple enough if compared cursors are flat rows and we could simply display rows that differ. It gets tricky when you have a complex structure like cursor returning object type, collection or nested cursor.
Perhaps that should be handled one by one.
First figure how to display diff for a flat row, then for object, then for collection/nested cursor

**Comment by mikechip1980** [comment]
here is useful link about XML comparison, several variants and some analysis 
https://www.google.ru/amp/s/ellebaek.wordpress.com/2011/02/01/comparing-xml-in-oracle/amp/

**Comment by mathewbutler** [comment]
We should stick with current XML and tools approach but also test for large comparisons - millions of rows to verify performance.
