### ISSUE TITLE
Add ability to run tests by part of a name.

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#470]
Currently you need to specify a full name to execute test procedure / suite / package
Example:
```sql
exec ut.run('owner.test_package');
--or
exec ut.run('owner.test_package.test_procedure');
```
We could add ability to use '*' at the end of the package name to run all tests/suites by part of the name.
So I could call:
```sql
exec ut.run('owner.test_p*');
--or
exec ut.run('owner.test_package.test_pr*');
```

Adding the '*' at the end of the name should be most easy and most beneficial.

Allowing '*' in any place of name would be more natural, but there is very little value in it and implementation of such feature would be a bigger effort.

**Comment by Pazus** [comment]
Idea. Introduce ability to specify patterns in regex format. For example:
`ut.run('{test_suite_number\d+}.main_test');`

**Comment by alesana-san** [comment]
I guess this is solved by putting `--%context` annotation or using tags.

**Comment by pesse** [comment]
Yes, I think especially tags are a good substitute.
Should we close it, @jgebal ?

**Comment by jgebal** [comment]
I would keep it open. It's still a good idea.
Someone might pick it up at some point.
