### ISSUE TITLE
WaffleBot breaking changes

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#474]
While I was the admin for this project, I setup a [waffle.io](https://waffle.io/utPLSQL/utPLSQL) board to help improve visibility of issues and workflow. I've received the following email from them today - I guess I'm still listed as the contact. I don't know whether you use the board, want to update it, want to close it down, etc? Please let me know if there's anything you'd like me to do to follow up on this. Thanks

> Subject: WaffleBot breaking changes 👀 🔥
>
> Hi there, 👋
> 
> We noticed that you have an outdated version of WaffleBot. Due to changes in GitHub permissions, WaffleBot needs to be reinstalled in order to update your board correctly.
> 
> WaffleBot automatically moves your work across your Waffle board. If you don't upgrade, WaffleBot won't be able to act on your behalf. 😕 
> 
> To uninstall:
> 
>     Click the lightning icon in the gray sidebar from your Waffle.io board
>     Click the "Install WaffleBot" button and then click "Configure"
>     Select the Organization or account name 
>     Scroll down and click the "Uninstall" button
> 
> After the above steps have been completed, repeat steps 1 through 3 to reinstall, and make sure to select "All repositories" in GitHub. 
> 
> Please note, you'll need to be an administrator of the organization in order to make these changes. If you're not an admin, feel free to forward this message or let us know who we should talk to.
> 
> If you have any questions, just hit reply. We're happy to help!
> 
> Thanks!
> Kelli

**Comment by jgebal** [comment]
Thanks @PaulWalkerUK for the info.
I'll see how to change the mail on `waffle.io`
I've follwed the steps provided in the mail and everything seems to be working nicely.
