### ISSUE TITLE
Re-think approach on not-updating version in develop branch

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#477]
Currently we do not keep version nuber in develop branch in source code.
We also do not update version number (build number).

We block users from dowloading from develop branch as version number in source code is `X.X.X.X`

Maybe we should allow for downloads and update source code versions for all files (build number) after every merge to develop?

The only question would be: what should be the develop version of the project?

I propose to use one of below for develop branch use: 
- last released version number + growing build no,
- next version (last release + 1 on bugfix part)

We would still be able to decide on the actual version number, when we prepare the release.

**Comment by mathewbutler** [comment]
We could take the same approach as used in build tools like maven. Give the develop Branch the next version identifier. E.g. 3.0.4-SNAPSHOT or similar tag. The tag should reflect the lifecycle stage of the develop branch.

**Comment by jgebal** [comment]
We could use `maven` approach I agree. It's well-known and common one.
I wonder if anyone has experience with other versioning approaches.
I don't know if there is any established and usable approach for Oracle open-source projects. I feel like we're pioneers here, but I might be wrong and just not well-informed.

**Comment by mathewbutler** [comment]
Current project uses maven to build PLSQL artefacts. 

We should focus on our requirement and then look for approaches in build tools if these apply. 

We could do our own thing or we could move to using a build tool. The risk is we pick something that adds to the knowledge needed to contribute. This may slow contributors down.
