### ISSUE TITLE
Improve/modify debug logging

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#480]
Currently to debug-log the framewor we need to compile it for debug, also the debug-logging is incomlete.

We could add logging levels of 1-5 where 1 is info 5 is with variables.

We could maybe use some of existing logging frameworks to save logs.

Any thoughts?

**Comment by mathewbutler** [comment]
OraOpenSource/logger on GitHub maybe?

I've heard good things but never used. I believe it's a robust implementation similar to Connor MacDonalds debug package from his PLSQL book.

**Comment by Shoelace** [comment]
can I suggest the log4 style [Shoelace/log4oracle](https://github.com/Shoelace/log4oracle)
it is quite "heavy" to but has drop-in singleobject/lite  implementation that can be customised as need by

FYI. its one i have written.  and I'm still trying to finish the update to log4 v2 but I just haven't had much time lately  (for that or utplsql :(  )

**Comment by jgebal** [comment]
I think we first should address #488 
In general I don't use the current debug logging at all - it's of no value to me currently so maybe we should think of logging user-level warnings only?
