### ISSUE TITLE
Runner takes a long time to execute

### ISSUE THREAD

**Issue by safokkens** [utPLSQL/utPLSQL#483]
I'm trying to implement utPLSQL on an Oracle EBS environment. We want to use it for our customizations software. Those packages are installed in schema APPS, just like the Oracle EBS packages. This is as recommended by Oracle. The test package is also placed in this schema.

There are a _lot_ of packages in this schema, approximately 43000. I think that's the reason for the slow performance of the utPLSQL runner. When I start the utPLSQL runner from another schema, it executes very quick. I also tried running with the schema and package name of the testpackage specified, but that didn't improve the performance.

Is there some sort of scanning of packages when I invoke ut.run()? And can you tweak the scanning when the testpackage is specified in the arguments? Or is there another option to speed things up?

Thanks in advance for your reaction

**Comment by jgebal** [comment]
Related to #458

**Comment by jgebal** [comment]
The only solution for now is to place the it packages in separate schema.
I know it's not a perfect solution. We're thinking of addressing this issue however.

**Comment by jgebal** [comment]
Can you check on your DB how long it takes for this query to execute in EBS schema?
```sql
select t.owner, t.object_name 
  from all_objects t 
 where t.owner = :a_owner_name 
   and t.status = 'VALID' and t.object_type in ('PACKAGE')
   and t.object_name IN (
     select name from all_source 
      where owner = :a_owner_name and lower(text) like '%suite%'
  )
```
and same on dba_views
```sql
select t.owner, t.object_name 
  from dba_objects t 
 where t.owner = :a_owner_name 
   and t.status = 'VALID' and t.object_type in ('PACKAGE')
   and t.object_name IN (
     select name from dba_source 
      where owner = :a_owner_name and lower(text) like '%suite%'
  )
```
That could give us a clue on possible hotfix.

**Comment by jgebal** [comment]
I'll move the discussion to #458
