### ISSUE TITLE
Receiving unique constraint (UT3.UT_CURSOR_DATA_PK) violated

### ISSUE THREAD

**Issue by xendren** [utPLSQL/utPLSQL#484]
We have 5 or 6 different unit test packages that are running fine.  We are working on a new package that is structured the same as our other tests, but we are consistently receiving the following error on every execution:

```
Failures:
1) history_columns
ORA-00001: unique constraint (UT3.UT_CURSOR_DATA_PK) violated
ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 105
ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 21
ORA-06512: at "UT3.UT", line 79
ORA-06512: at "DISA_OWNER.PST_DISA_SORT_CODE_PUB", line 73
ORA-06512: at line 6
```

We've tried removing all tests and setup logic, but we still receive the error.  The only change in behavior that I can see is if we delete all data from the table being tested.  When it has any rows at all, it will cause the error.  I can't see any difference in this table versus other tables we have tested against.  
Looking into the UT packages, it looks like the PK for UT_CURSOR_DATA is the GUID and ROWNUM.  I don't see how we would not be getting unique values for this cursor, so I am at a loss here.

Here is the simple test that we are trying to perform:
```
   PROCEDURE not_empty
   IS
      l_empty_cur   SYS_REFCURSOR;
   BEGIN
      ut.set_nls ();                  -- Needed because we are comparing dates
      OPEN l_empty_cur FOR SELECT AUDIT_LOG_ID FROM disa_sort_code_rules_pub;

       ut.expect (l_empty_cur).not_to_be_empty ();
       ut.reset_nls ();                  -- Needed because we are compare dates
   END not_empty;
```

**Comment by pesse** [comment]
Hi xendren,

on which version of utPLSQL are you? We fixed an issue in that area with v3.0.3.

**Comment by xendren** [comment]
Hello.  We are using Version v3.0.2.938

I'll see if we can download 3.0.3 and give it another try.

**Comment by jgebal** [comment]
It's resolved.l in 3.0.3 see issue #445

**Comment by xendren** [comment]
Thanks all!  Upgrading to v3.0.3 did solve the problem.
