### ISSUE TITLE
Add --%throws annotation

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#490]
That way we can write code:
```sql
begin
   a_failing_procedure();
   ut.fail(-20000);
exception
  when other then
    ut.expect(sqlcode).to_equal(-20000);
end;
```
If the `a_failing_procedure();` call returns without exception, the `ut.fail(-20000)` would report this.
The tests when it's called would report:
`Expected exception ORA-20000, but nothing was raised`

Currently, we need to code around it a bit. The way I do it is:
```sql
begin
   a_failing_procedure();
   ut.fail('Expected exception ORA-20000 but nothing was raised');
exception
  when other then
    ut.expect(sqlcode).to_equal(-20000);
end;
```

**Comment by jgebal** [comment]
The more I think about it the less I like it.
It seems a nice "shortcut" solution, but it's not very flexible and has a narrow usage.

If I need to check for specific error message the solution above will bring nothing new to the table.
Also, the syntax: `ut.fail(-20000);` is not clear and understandable when someone not knowing the framework will read the code. It might suggest that the test will fail with ORA-20000 exception.

So we need to figure a different approach.
This issue is related to #233

**Comment by AlexisGaldamez** [comment]
I was thinking something like this:

--%test(Reports an exception when cursor is closed)
--%throws(-20145)
procedure exception_when_closed_cursor;

**Comment by jgebal** [comment]
Given a tested code:
```sql
  procedure do_stuff_with_cursor( a_cursor sys_refcursor ) is
  begin
    if not a_cursor%isopen then
      raise_application_error(-20145, 'Cursor is not open');
    end if;
    --do stuff here
  end;
```
The spec of the test would be:
```sql
create or replace package test_stuff is
  --%suite
  
  --%test(Raises an exception on closed cursor)
  --%throws(-20145)
  exception_when_closed_cursor;
end;
```
and the body of a test would be something like:
```sql
create or replace package body test_stuff is
  procedure exception_when_closed_cursor is
    l_cursor sys_refcursor;
  begin
    open l_cursor for select * from dual;
    close l_cursor;
    do_stuff_with_cursor( l_cursor );
  end;
end;
```

I like this approach. It is much nicer than the one we have now (without the annotation),
Where you have to do the following:
```sql
create or replace package body test_stuff is
  procedure exception_when_closed_cursor is
    l_cursor sys_refcursor;
  begin
    open l_cursor for select * from dual;
    close l_cursor;
    do_stuff_with_cursor( l_cursor );
    ut.fail('Expected exception but nothing was raised');
  exception
    when others then
      ut.expect(sqlcode).to_equal(-20145);
  end;
end;
```

**Comment by jgebal** [comment]
So to summarize.
I would propose to have 2 flavors of that:
1. `--%throws( the_number )` 
Gives success, when exception with `sqlcode` equal `the_number` was raised.
Gives failure when different exception was raised.
Gives failure when no exception was raised.
The failure message for no exception should say: `Expected exception with number 'the_number' but nothing was raised`.
The failure message when different exception was raised should say: `Expected exception with number 'the_number',  got 'ORA-actual_sqlcode: actual_sqlerrm'`

2. `--%throws( 'text%part%' )`
Gives success, when exception with `sqlerrm` like `text%part%` was raised.
Gives failure when different exception was raised. 
Gives failure when no exception was raised.
The failure message for no exception should say: `Expected exception with text like 'text%part%' but nothing was raised`. 
The failure message when different exception was raised should say: `Expected exception with with text like 'text%part%',  got 'ORA-actual_sqlcode: actual_sqlerrm'`

**Comment by AlexisGaldamez** [comment]
I agree with this approach
