### ISSUE TITLE
Is there a equivalent utassert.eqtable (Available in utplsql version 2.X) in utplsql version 3.3?

### ISSUE THREAD

**Issue by jlprasath** [utPLSQL/utPLSQL#493]
After going through the documentations of Utplsql 3.0.2 , I couldn't find any references the assertion api as available in the older versions. Please let me know whether is there a equivalent assertion like utassert.eqtable available in newer versions. I a unable to find the equivalent documentation of the various functions available in this link http://utplsql.org/docs/utassert.html. Are these functions available  in newer versions also. ?

**Comment by jgebal** [comment]
In utPLSQL v2 you had to use 'quoted text to compare tables / queries.
utPLSQL v3 allows you to compare table data using native refcursors without usage of dynamic SQL.

In v2 you would use syntax like:

```sql
procedure test_tables_v2 is
begin
  utassert.eqtable(
    'Delete rows', 
    'EMPLOYEES',
    'ut_DEL1', 
    q'[hire_date > date '2017-08-01']',q'[hire_date > date '2017-08-01']'
  );
end;
/
```

In v3 you will use syntax:

```sql
procedure test_tables_v3 is
  l_expected sys_refcursor;
  l_actual   sys_refcursor;
begin
  open l_actual   for select * from employees where hire_date > date '2017-08-01' order by employee_id;
  open l_expected for select * from ut_del1  where hire_date > date '2017-08-01' order by employee_id;
  ut.expect(l_actual).to_equal(l_expected);
end;
```

Additionally v3 allows you to filter columns of cursors so you can decide which columns should not be compared.
```sql
procedure test_tables_v3 is
  l_expected sys_refcursor;
  l_actual   sys_refcursor;
begin
  open l_actual   for select first_name,last_name, hire_date from employees order by first_name;
  open l_expected for select first_name,last_name from employess order by first_name;
  ut.expect(l_actual).to_equal(l_expected, a_exclude=>'HIRE_DATE' );
end;
```
utPLSQL v3 `ut.expect() ` with cursors also allows for columns containing clob/blob/nested cursors/nested collections and object types in select statements.
Additionally you can filter columns (elements) of comparison.
The main difference is that in v3 order matters - the data is compared in a sorted manner.
This feature actually makes the comparison even more powerful as you can check if data is properly ordered in the result-set. This is of particular use when validating cursor data returned by procedure or function.

Hope that this answers your question.

**Comment by jlprasath** [comment]
Thank you very much for the quick reply.
