### ISSUE TITLE
Existing state of packages was discarder

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#504]
If `utPLSQL` encounters `ORA-04068` or `ORA-04061`, it will immediately abort test execution and re-raise the exception.

This mechanism is implemented deliberately as supressing this exceptions makes the session unable to re-validate the invalid package state.
If `ut_executable` would suppress those exceptions, consecutive calls to `ut.run()` would still end with invalid package state.

When running a suite of more than one test package, the side effect is that not all tests get executed and the results are partly presented on the outputs as the execution is aborted.

As an alternative the framework could `flag` such exceptions when they occur, so it can continue with execution for the remaining of unit test packages. 
If the exception was `flagged`, the framework would throw an exception after the execution.
That way we allow the session to recover from invalid package state and still run a full suite.

**Comment by Shoelace** [comment]
so to clarify,  it essentially  just becomes another failure reason ?

**Comment by jgebal** [comment]
Almost, except that we have to throw the right type of exception.  It still needs validation. I'm not sure if it will work properly when you manually throw such exception post execution.
