### ISSUE TITLE
Auto-rollback statements from the beforeall triggers does not work

### ISSUE THREAD

**Issue by MickeVr** [utPLSQL/utPLSQL#506]
In version 3.0.3 I set up my test cases in a beforeall trigger in tables. I am not using any commit statement, however, the data in the beforeall is not removed after execution:

I created the following testcase:

```
create table testinserts (ts timestamp, col1 varchar2(1000));

CREATE OR REPLACE PACKAGE ut_TEST2 IS
   -- %suite(Test commits)
   -- %suitepath(commit_tests)

   --%beforeall
   PROCEDURE beforeall;

   --%afterall
   PROCEDURE afterall;

   --%beforeeach
   PROCEDURE beforeeach;

   --%aftereach
   PROCEDURE aftereach;

   -- %test(Functionality)
   PROCEDURE ut_TABLE_TYPE;
END ut_TEST2;
/

CREATE OR REPLACE PACKAGE BODY ut_TEST2 IS
   PROCEDURE beforeall IS
   BEGIN
      INSERT INTO testinserts VALUES (SYSTIMESTAMP, 'beforeall');
   END;

   PROCEDURE aftereach IS
   BEGIN
      INSERT INTO testinserts VALUES (SYSTIMESTAMP, 'aftereach');
   END;

   PROCEDURE afterall IS
   BEGIN
      INSERT INTO testinserts VALUES (SYSTIMESTAMP, 'afterall');
   END;

   PROCEDURE beforeeach IS
   BEGIN
      INSERT INTO testinserts VALUES (SYSTIMESTAMP, 'beforeeach');
   END;


   PROCEDURE ut_TABLE_TYPE IS
   BEGIN
      INSERT INTO testinserts VALUES (SYSTIMESTAMP, 'unit test run');
      ut.expect('X', a_message => 'String X').to_equal('X');
   END;
END ut_TEST2;
/


exec ut.run(USER||':commit_tests.'||'ut_TEST2');
commit;
```

If I query select * from testinserts, I expect nothing, but I get a record with
ts: 27-10-17 09:39:42,863000000 and col1: beforeall

**Comment by MickeVr** [comment]
I found the cause of this issue: the savepoint names are using 'ut_' plus the systimestamp converted to a string. The beforeall statements are taking almost no time, so the systimestamp of the savepoint of the beforeeach gets the same name. As the PL/SQL documentation says: "The savepoint moves from its old position to the current point in the transaction."

I think this can be prevented easily by using different prefixes for suite savepoints and test savepoints. I adjusted this in my local copy of utplsql and now my automatic UTs are behaving as I expected.

**Comment by jgebal** [comment]
The issue you're reporting seems suspicious.
I don't think you will get 2 identical timestamps in two consecutive PLSQL calls.

Can you execute those blocks and provide outcomes you get?
```sql
begin
   dbms_output.put_line(to_char(systimestamp,'yymmdd_hh24mmssff'));
   dbms_output.put_line(to_char(systimestamp,'yymmdd_hh24mmssff'));
end;
/

begin
   dbms_output.put_line(to_char(systimestamp,'yymmdd_hh24mmssff9'));
   dbms_output.put_line(to_char(systimestamp,'yymmdd_hh24mmssff9'));
end;
/
```
I think the issue might be `ff` in format without specified precision.

**Comment by jgebal** [comment]
Anyway the format is wrong as we skip the minutes part and use month twice :)
Instead of: 
`'ut_'||to_char(systimestamp,'yymmddhh24mmssff');`
We should use:
`'ut_'||to_char(systimestamp,'yymmddhh24missff9');`

**Comment by MickeVr** [comment]
Hi @jgebal, the output is displayed below
```
171027_131057083000000
171027_131057083000000
171027_131057114000000
171027_131057114000000
```

The oracle database is running on Windows, so that is the reason I have only miliseconds present in the string. I observed the collision of savepoint names in my tests, and changing the used savepoints names fixed the problems I had (data that was inserted in the beforeall method was not rolled back)

**Comment by jgebal** [comment]
Can you check if consecutive calls to `sys_guid();` return different values?
```sql
begin
   dbms_output.put_line(DBMS_OBFUSCATION_TOOLKIT.MD5(input_string=>sys_guid()));
   dbms_output.put_line(DBMS_OBFUSCATION_TOOLKIT.MD5(input_string=>sys_guid()));
end;
/
```

We can create a Quoted save point name using MD5 Hash value:
```sql
declare
  l_savepoint varcahr2(30);
begin
   l_savepoint  := DBMS_OBFUSCATION_TOOLKIT.MD5( input_string=>sys_guid() );
   execute immediate 'savepoint "'||l_savepoint||'";'
   rollback;
end;
/
```

**Comment by MickeVr** [comment]
Consecutive calls to sys_guid indeed return different values, so I think it can be the base of the savepoint name. Using the MD5 algorithm however might result in a possible set of bits representing the double quote character, which can not be used in the savepoint name between double quotes.

Isn't it a better option to base64 encode the guid? This should result in a string that is small enough (less than 30 characters), and this string can't contain double quotes. I tried out the following script which works OK.

```
set serveroutput on; 
DECLARE
   l_savepoint   VARCHAR2(30);
   l_guid RAW(16);
BEGIN
   l_guid := SYS_GUID();
   DBMS_OUTPUT.put_line('First guid:' ||l_guid);
   l_savepoint := utl_raw.cast_to_varchar2(utl_encode.base64_encode(l_guid));
   DBMS_OUTPUT.put_line('First savepoint:' ||l_savepoint);

   EXECUTE IMMEDIATE 'savepoint "' || l_savepoint || '"';
   
   l_guid := SYS_GUID();
   DBMS_OUTPUT.put_line('Second guid:' ||l_guid);
   l_savepoint := utl_raw.cast_to_varchar2(utl_encode.base64_encode(l_guid));
   DBMS_OUTPUT.put_line('Second savepoint:' ||l_savepoint);

   EXECUTE IMMEDIATE 'savepoint "' || l_savepoint || '"';

   ROLLBACK;
END;
/
```

**Comment by jgebal** [comment]
We can either follow your suggestion or double-quote any quote :)
```sql
declare
  l_savepoint varcahr2(30);
begin
   l_savepoint  := replace(DBMS_OBFUSCATION_TOOLKIT.MD5( input_string=>sys_guid() ),'"','""');
   execute immediate 'savepoint "'||l_savepoint||'";'
   rollback;
end;
/
```
I must admit though, that I like the `base64_encode` approach more :)

@MickeVr 
Would you like to contribute that change or will you wait for someone from the team to do it?

**Comment by MickeVr** [comment]
Thanks Jacek!
