### ISSUE TITLE
More system privileges needed

### ISSUE THREAD

**Issue by mheumann** [utPLSQL/utPLSQL#507]
Hey,
I'm working for a bigger company and I'm not able to create my own users or give the users sytem privileges, so like it's written in the documentation, I ordered a new User with the privileges:
- CREATE SESSION
- CREATE PROCEDURE
- CREATE TYPE
- CREATE TABLE
- CREATE VIEW
- CREATE SYNONYM
- ALTER SESSION

Now I ran into the problem when installing the component UT_MESSAGE_ID_SEQ, that I don't have the priviledge "CREATE SEQUENCE". So two questions: Most important one: What other priviledges than those in the documentation are needed, so can order those. And second: Please fix it on the website :)

**Comment by jgebal** [comment]
Hi @mheumann 
It would be best if you could follow the install instructions. What I usually recommend is to either have DBA user and perform the headless install or ask my DBA to do it for me.

You're right, documentation could be improved and distinguish between:
- user performing the installation
- user owning utPLSQL framework

The user that is used to install the framework needs elevated privileges. Once installed, utPLSQL does not require privileges to create objects.
We will need to review the documentation to make sure it is reflecting that.

Hope this helps.

**Comment by jgebal** [comment]
@mheumann 
CREATE SEQUENCE is only privilege missing in doc.
That will is resolved by #515
