### ISSUE TITLE
No coverage data, when running with a_include_objects from different schema

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#511]
When I execute the tests as below:
```
alter session set current_schema=other_schema;

select *
  from table(
    ut.run(
      user, 
      ut_coverage_html_reporter(),
      a_include_objects => ut_varchar2_list( user||'.betwnstr')
    )
  );
```
The coverage report is empty.
I need to explicitly specify `a_coverage_schemes=>ut_varchar2_list( user )` as a parameter, even though the owner of the object is included as part of the `a_include_objects` parameter.

The behavior should be:

 a_include_objects | a_coverage_schemes | a_source_file_mappings | coverage filtering |
-|-|-|-|
 null | null | null | all objects (except tests) in current_schema|
 specified | null | null | all objects (except tests) from the list specified (as per schemes on the object list) |
 null | specified | null | all objects in schemes specified (except unit tests)  |
 null | null | specified | all objects (except tests) from the file mapping list (as per schemes on the list) |

It doesn't really make sense to support combinations of those 3 parameters.
Those parameters should be mutually exclusive.
So users should only provide one of parameters not a combination of those.

**Current implementation sets value of `a_coverage_schemes` to be CURRENT_SCHEMA, if not value was provided. This makes the `a_include_objects` filter useless without specifying schema names.**

**Comment by pesse** [comment]
I guess to solve this you'll change the public API of ut_runner, won't you? I think any change has also be included in Java-API and CLI

**Comment by jgebal** [comment]
I will start by fixing the functionality.
Are you OK with this change?

**Comment by pesse** [comment]
Yes of course, finally got myself into both, API and CLI so I'm ready to update them if there are any changes to public API. Will also create an issue in Java-API-Project
