### ISSUE TITLE
install utplsql 2.3.1

### ISSUE THREAD

**Issue by Srinivasaprabhu2018** [utPLSQL/utPLSQL#531]
HI i am  not able to install the utplsql version 2.3.1 . My requirement s i have to install v 2.3.1. Could you please let me know the instructions.

**Comment by jgebal** [comment]
Here is documentation for 2.3.1
http://utplsql.org/utPLSQL/v2.3.1/
Why do you want to install an unsupported version?

**Comment by nrkmca** [comment]
Hi jgebal,
Thanks for helping us. I installed the UTPLSQL 3.0.3 version and it works fine but test releated information is not pupulated into PLSQL_PROFILER_DATA, PLSQL_PROFILER_RUNS, PLSQL_PROFILER_UNITS in built tables. CAn you please help me how to populate these tables?
