### ISSUE TITLE
Replace ut3_latest_release package with actual in test/ut_matchers

### ISSUE THREAD

**Issue by hellstonik** [utPLSQL/utPLSQL#532]
Little bug in test/ut_matchers: inside package body you should replace addressing to package "ut3_latest_release" with actual one.
How to repeat:
1. Run "install_headless.sql"
2. Run "install_tests.sql". There will be an error on compiling "ut_matchers" package.

**Comment by jgebal** [comment]
Hi @hellstonik 
Did you follow our [contributing.md](https://github.com/utPLSQL/utPLSQL/blob/develop/CONTRIBUTING.md) for deployment and execution of tests locally?

I believe all tests are working fine on our CI/CD server. For development you need to have 2 (two) installations of utPLSQL v3:
- develop version in `ut3` schema
- latest release in `ut3_latest_release`

**Comment by jgebal** [comment]
I must admit though, that the test is not very intuitive.

**Comment by hellstonik** [comment]
Thanks for your time, @jgebal .  I just downloaded an actual master branch and didn't expect those tricks with schemas. My fault :)

**Comment by hellstonik** [comment]
As in #533
