### ISSUE TITLE
Trimmed error message on ut.expect() procedure extended on several strings

### ISSUE THREAD

**Issue by hellstonik** [utPLSQL/utPLSQL#536]
Hello, I have a problem on error message output when using ut.expect() extended on several strings. For example:
1.  Case with two input parameters on different strings (standard situation when you use some kind of beautifier):
```
...
ut.expect(v_activity_bank
             ,'Super check').to_equal(1);
...
```
**Correct error output :**
```
...
"Super check"
Actual: 2 (number) was expected to equal: 1 (number) 
at "UT3.TEST_PACKAGE_BANK", line 8 ut.expect(v_activity_bank,'Super check').to_equal(1);
```
**Actual error output :**
```
...
Failures:
 "Super check"
Actual: 2 (number) was expected to equal: 1 (number) 
at "UT3.TEST_PACKAGE_BANK", line 12 ut.expect(v_activity_bank
```
2. Case with long "a_message" parameter (two or more strings length)
```
...
ut.expect(v_activity_bank
             ,'Super 
               check').to_equal(1);
...
```

Actual and correct output is the same as in first case. 

Test package will be in the next message.

**Comment by hellstonik** [comment]
```
CREATE OR REPLACE PACKAGE test_package_bank IS

  --%suite(Bank checking)
  --%suitepath(BANKS)

  --%test(First check)
  PROCEDURE check_bank1;

END;
/
CREATE OR REPLACE PACKAGE BODY test_package_bank IS

  PROCEDURE check_bank1 IS
    v_activity_bank NUMBER;
  BEGIN
    v_activity_bank := 2;
    -- Correct output
    ut.expect(v_activity_bank,'Super check').to_equal(1);
    
    -- Incorrect output
    -- Case with two input variables on different strings
    ut.expect(v_activity_bank
             ,'Super check').to_equal(1);
    -- Case with comment on two or more strings
    ut.expect(v_activity_bank
             ,'Super 
               check').to_equal(1);
  END check_bank1;

END;
/
```

**Comment by jgebal** [comment]
Can you tell me how you execute the suite?
Do you ice command line client (which one) or do you execute from tool like toad/sqlplus/SQLDeveloper?

**Comment by hellstonik** [comment]
I use PL/SQL Developer

**Comment by jgebal** [comment]
Can you be more specific?
You run it as a script or as execute command? 
I suspect that PLSQL developer is trimming output. 
It is a matter of your IDE settings.

**Comment by hellstonik** [comment]
By execute in SQL/Test Window:
```
BEGIN
  ut.run('ut3.test_package_bank');
END;
/
```

Output:

```
banks
  Bank checking
    First check [.008 sec] (FAILED - 1)
 
Failures:
 
  1) check_bank1
      "Super check"
      Actual: 2 (number) was expected to equal: 1 (number) 
      at "UT3.TEST_PACKAGE_BANK", line 8 ut.expect(v_activity_bank,'Super check').to_equal(1);
      
       
      "Super check"
      Actual: 2 (number) was expected to equal: 1 (number) 
      at "UT3.TEST_PACKAGE_BANK", line 12 ut.expect(v_activity_bank
      
       
      "Super 
                     check"
      Actual: 2 (number) was expected to equal: 1 (number) 
      at "UT3.TEST_PACKAGE_BANK", line 15 ut.expect(v_activity_bank
      
       
Finished in .011059 seconds
1 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)
```


PS: This issue repeats in SQL Developer too

**Comment by jgebal** [comment]
Try:
Select * from table(ut.run(...));
Both ways works well for me.

**Comment by hellstonik** [comment]
Maybe we misunderstood each other: i mean that in second and third calling "ut.expect"  i don't see ending of string in output:

at "UT3.TEST_PACKAGE_BANK", line 8 ut.expect(v_activity_bank **,'Super check').to_equal(1);**

(marked bold)

So as when executing :
```
Select * from table(ut.run(...));
```
(i see the same picture with trimming string and several forward empty strings)

**Comment by jgebal** [comment]
What version of utPLSQL you use and what is DB version?

**Comment by jgebal** [comment]
Ah... Sorry. Now I get it

**Comment by jgebal** [comment]
utplsql is not capable of parsing package body. It is just reporting the line no and line content based on stack trace.
Trying to parse multiple lines would be too much of work and benefits are minimal. 

You are still able to identify the failed line in your rest with current output by the line no.

**Comment by hellstonik** [comment]
I fully agree with you, just wanted to point on this feature and wanted to understand the scale. Thanks.
