### ISSUE TITLE
Not able to populate data into utPLSQL in-built tables

### ISSUE THREAD

**Issue by nrkmca** [utPLSQL/utPLSQL#537]
Hi jgebal,
Thanks for helping us. I installed the utPLSQL 3.0.3 version and it works fine but test related information is not pupulated into PLSQL_PROFILER_DATA, PLSQL_PROFILER_RUNS, PLSQL_PROFILER_UNITS in built tables. Can you please help me how to populate these tables?

**Comment by Shoelace** [comment]
those tables are only populate with code coverage data.
so you'll need to run something like `exec ut.run(ut_coverage_html_reporter());`

but even then i believe the results are removed shortly afterwards and are then only available in the output of the reporter..

**Comment by nrkmca** [comment]
Thank you so much for your prompt help/reply.
