### ISSUE TITLE
New ability to get brief reports

### ISSUE THREAD

**Issue by kenbaev** [utPLSQL/utPLSQL#538]
While using ut_documentation_reporter() i've got massive reports with thousands of lines (many checks, many info from stdout). I need a way to get brief report, that shows only errors and optionally warnings.

I see two ways to add this feature:
1. Add new reporter - ut_brief_doc_reporter()
2. Add params to exsiting reporting constructor ut_documentation_reporter(print_stdout => false, print_successfull => false, print_warnings => false, ...) or something similar.

What option is more preferable?

**Comment by jgebal** [comment]
New reporter is preferred as reporters should not have constructor parameters.
If it makes sense, you can build it on top of (under)  documentation reporter and reuse some of existing functionality to avoid code duplication.

**Comment by jgebal** [comment]
@kenbaev - will you be willing to contribute that reporter to the project?

**Comment by lwasylow** [comment]
I understand that we cannot apply parameters to CLI. wouldnt then make a sense to report on error and warning as well ?

**Comment by pesse** [comment]
I don't understand your case, @lwasylow 
With cli 3.1.0 we can target any reporter, not only the ones provided by core. You can easily create a new ut_brief_doc_reporter and call it via cli like this:
`utplsql run user/pass@connstr -f=ut_brief_doc_reporter`

IMO it's more simple than supporting parameters and also much more powerful. I also think it encourages people to create simple interfaces for their reporters, also a plus from my point of view.

**Comment by lwasylow** [comment]
@pesse no case here:) Just summarise above where there was proposal to provide parameters to display diffrent type of warning. Remember you mention that before way back when I was thinking of parameter. And agree with you that new reporter is fairly easy to do and its a better way than to remember multiple params. We just need to iron out what to show inside (errors only plus summary or more etc.)

**Comment by pesse** [comment]
Ah, you're on the track then :D
Can you give an example of what's the difference between error and warning?

**Comment by pesse** [comment]
would be great to get some feedback from @kenbaev about what exactly his expectation/request was.

**Comment by jgebal** [comment]
In rspec there is a brief reporter.
It reports a dot `.` for every passing test and an `F` for failure.
Sou you gert something like:
`.......FF.......`
and a summary+failyres/exceptions/warnings

**Comment by jgebal** [comment]
@kenbaev 
What is it exactly that the output should exclude/include when running with brief reporter?
