### ISSUE TITLE
Issue In XUnit Reporter GetPath

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#547]
I believe there is an issue in getpath expression in ut_xunit_reporter.
It uses a substring which can result in negative positive.
E.g. Package is named "ut_gen_pk_id_api" and annotation for suitepath is alltests 

CREATE OR REPLACE PACKAGE ut_test.ut_generate_pk_id_api IS

   --%suitepath(alltests)
   --%suite(generate_primary_key)
   --%displayname(Generate PK Function Suite)

   --%test(ut_generate_pk_id)
   --%displayname(Generate PK Function Test)
   PROCEDURE ut_generate_pk_id;

END ut_generate_pk_id_apii;
/

When running that it reports a classname in xunit as : 'alltest' rather than 'alltests.ut_gen_pk_id_api'

Would not be better to replace

return substr(a_path_with_name, 1, instr(a_path_with_name, '.' || a_name) - 1);
with
substr(a_path_with_name, 1, regexp_instr(a_path_with_name, '.' || a_name||'$') - 1)

**Comment by jgebal** [comment]
You are referring to a use-case where test package name is like '%test procedure name%'

I think your regex pattern was is missing `\` before the dot.
```sql
select a_path_with_name,
        regexp_substr(a_path_with_name, '(.*)\.' ||a_name||'$',1,1,'',1),
        substr(a_path_with_name, 1, regexp_instr(a_path_with_name, '\.' || a_name||'$') - 1),
        substr(a_path_with_name, 1, instr(a_path_with_name, '.' || a_name) - 1)
  from (select 'alltests.ut_generate_pk_id_api.ut_generate_pk_id' a_path_with_name, 'ut_generate_pk_id' a_name from dual);
```

Maybe we can just use:
`return regexp_substr(a_path_with_name, '(.*)\.' ||a_name||'$',subexpression=>1)`

It is a bug indeed.

Can you fix it and create a PR for it?
