### ISSUE TITLE
Behavior of ut.expect(closed_cursor)

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#548]
Currently, when `ut.expect` is executed with a cursor that was closed, no exception is thrown.

I think we should change that behavior as such cursor is invalid and cannot be processed.

I would prefer the call to `ut.expect(closed_cursor) to raise exception.
We do not hide exceptions raised while fetching from cursor (like divisor_equal_to_zero) so I suppose we should not hide that we cannot execute expectation on a closed cursor.

Any thoughts on this? Should we change that behavior?

**Comment by pesse** [comment]
I strongly agree with changing the behaviour. The current behaviour will probably lead to non-working tests without notifying - in my opinion worst case scenario cause it creates false confidence.

**Comment by Pazus** [comment]
I agree, @jgebal

**Comment by AlexisGaldamez** [comment]
I'll make the change, when a cursor already closed is passed, It must throws a exception *invalid refcursor*, This message is okay?

**Comment by jgebal** [comment]
How about: `cursor is not open`
