### ISSUE TITLE
Behavior of expectations when anydata is null

### ISSUE THREAD

**Issue by AlexisGaldamez** [utPLSQL/utPLSQL#553]
When a null anydata argument is passed to the expectations, it must throw a exception, ANYDATA argument can not be null

**Comment by jgebal** [comment]
To be precise, expectation should throw the exception when anydata variable itself is NULL (uninitialized):
```sql
...
  l_actual anydata;
begin
  ut.expect(l_actual).to_( ... );
  ut.expect(l_actual).not_to( ... );
end;
```

In normal use-case, when value passed to anydata is null, it should work without raising exception.
```sql
...
  l_actual my_object;
begin
  ut.expect( anydata.convertObject( l_actual ) ).to_( ... );
  ut.expect( anydata.convertObject( l_actual ) ).not_to( ... );
end;
```

**Comment by jgebal** [comment]
This feature was discarded.
