### ISSUE TITLE
Null attribute is reported differently on 11gR2 and 12c (r1/r2)

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#560]
When reporting a mismatch on data between objects in 11g, null elements are missing (not shown at all).
On 12c however they are showing as `<attribute_name/>` - that is empty XML tag.
If we figure out how to resolve this, we should make it consistent across db versions.
Example:
```sql
create or replace type test_dummy_object as object (
  id number,
  "name"  varchar2(30),
  "Value" varchar2(30)
)
/
```

```sql
select xmltype.createXml( test_dummy_object(null, null, null) ) from dual ;
```
On 11g
```
<TEST_DUMMY_OBJECT/>
```

On 12c
```
<TEST_DUMMY_OBJECT><ID/>
<name/>
<Value/>
</TEST_DUMMY_OBJECT>
```

**Comment by jgebal** [comment]
Submitted a question: https://asktom.oracle.com/pls/apex/f?p=100:11:::::P11_QUESTION_ID:9537375900346527796

**Comment by Shoelace** [comment]
if you were using `dbms_xmlgen` then it has a `setNullHandling` method that controls that. but that doesnt seem to apply to the base xmltype..  nor does there appear to be a "default context" you can set either (like you can with Dbms_Metadata)

**Comment by jgebal** [comment]
Got reply from askTom. We cannot control it.

**Comment by Shoelace** [comment]
this is almost there..

```sql
DECLARE
  QUERYSTRING VARCHAR2(200);
  v_ctx NUMBER;
BEGIN
  QUERYSTRING := 'select test_dummy_object(1, null, 2) test_dummy_object  from dual';

  v_ctx := SYS.DBMS_XMLGEN.NEWCONTEXT(
    QUERYSTRING => QUERYSTRING
  );
    DBMS_XMLGEN.setRowTag(v_ctx, '');

  DBMS_XMLGEN.setRowSetTag(v_ctx, '');
  DBMS_XMLGEN.setNullHandling(v_ctx,2);

DBMS_OUTPUT.PUT_LINE(dbms_xmlgen.getXML(v_ctx));

END;
/
```

gives

    <?xml version="1.0"?>
     <TEST_DUMMY_OBJECT>
      <ID>1</ID>
      <name/>
      <Value>2</Value>
     </TEST_DUMMY_OBJECT>

**Comment by jgebal** [comment]
Thanks @shoelace
Looks nice.
Definitely something with including
