### ISSUE TITLE
Previous coverage report displayed after all objects dropped.

### ISSUE THREAD

**Issue by OsBlaineOra** [utPLSQL/utPLSQL#562]
Database: Cloud database 12c.
utPLSQL: v3.0.4

Starting with a new schema.

1. Create one or more objects (func, proc or package)
2. `exec ut.run(ut_coveralls_reporter());`
3. A coverage report is generated.
4. Drop all non-test objects.
5. `exec ut.run(ut_coveralls_reporter());`

The report from step 3 is returned even though the covered objects have all been dropped.

Side note:  I don't think it's related but, I do have one test package that tests a function in a different schema.  It's not related to the objects above and doesn't seem to affect the report.

**Comment by jgebal** [comment]
We need to add call to `ut_coverage.helper.cleanup_tmp_table` in `ut_runner.finish_run`
