### ISSUE TITLE
Sonar Test Reporter, wrong root element

### ISSUE THREAD

**Issue by alberto-hernandez** [utPLSQL/utPLSQL#566]
utPLSQL: v3.0.4.develop

Reporter of Sonar Test has the wrong root xml element. 

Actually it has configured on _ut_sonar_test_reporter.tpb_ the root element as **testExecutions** but the documentation of the sonar-generic-coverage ([link](https://github.com/SonarQubeCommunity/sonar-generic-coverage)) states that the root element should be "**unitTest**".

**Comment by jgebal** [comment]
The element is correct, as sonar changed the root element.
The link you provided states in readme file.
```
Deprecated since SonarQube 6.2 because the functionality was absorbed into SonarQube core.
```

utPLSQL v3 was released way after sonar 6.2
We decided to support new version instead of the legacy one.
