### ISSUE TITLE
ORA-00001: unique constraint (UTP3.UT_COVERAGE_SOURCES_TMP_PK) violated

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#568]
The issue occures when there is more than one file mapping to the same database object.
To get that resolved, we need to fix the file mapping mechanism to either raise a proper exception or deduplicate and pick the first file from the duplicates.
Maywe we should give warning on duplicated and de-duplicate, so we do not stop the tests from getting executed.

**Comment by Shoelace** [comment]
warning and continues seems like a good idea. 

however you could argue that the lastly defined mapping should be the one to use though and not the first.

do you also want to warn if teh mapping is defined twice as the same thing? or only if defined differently?
