### ISSUE TITLE
Skipping and failing tests manually

### ISSUE THREAD

**Issue by Ferosio** [utPLSQL/utPLSQL#581]
I did not found anything about failing tests explicitly or skipping tests. Is it documented somewhere? Is it actually implemented?

**Comment by pesse** [comment]
You can skip tests with the `-- %disabled` annotation (see the [docs](http://utplsql.org/utPLSQL/v3.0.4/userguide/annotations.html))

You can explicitly fail tests with adding an explecitly false expectation, for example:

```
procedure mytest as
begin
  ut.expect(1).to_(equal(0));
end;
```

**Comment by jgebal** [comment]
Or use `ut.fail('explicitly fails a test');`

**Comment by pesse** [comment]
Haha, sry @jgebal, I edited my comment afterwards :)
