### ISSUE TITLE
Please provide an example if avaiable where utPLSQL can check the output variable from procedures and functions.

### ISSUE THREAD

**Issue by sunil-choubey** [utPLSQL/utPLSQL#582]

**Comment by jgebal** [comment]
There you go:
http://utplsql.org/utPLSQL/v3.0.4/userguide/expectations.html

**Comment by pesse** [comment]
```sql
create or replace package ut_simple as
  --%suite

  --%test
  procedure test_simple;
end;

create or replace package body ut_simple as

  procedure test_simple
  as
    v_functionReturnValue varchar2(100);
    v_procedureOutputValue varchar2(100);
  begin
    v_functionReturnValue := some_function();
    ut.expect( v_functionReturnValue ).to_( equal('function return value') );

    some_procedure( v_procedureOutputValue );
    ut.expect( v_procedureOutputValue ).to_( equal('procedure return value') );
  end;
end;
```

Written from mind, but should make usage clear...

**Comment by jgebal** [comment]
And one more doc:
http://utplsql.org/utPLSQL/v3.0.4/userguide/getting-started.html

**Comment by sunil-choubey** [comment]
ThankYou Jgebal and Pesse for such a fast reply :) ..

I got it .. Actually was confusing it with the way ut.expect handles the result of a function.

Regarding the example of Pesse ... What I am trying to say is that lets suppose you want to test the below procedure.

procedure p_test ( p_input1  number ,  
                               p_output1 out number ) 
is 
    p_output1  := p_input1;
end ;
/

where I was confused is how the ut.expect will check p_output1 and I tried few alternatives in my test package 

example procedure 

    procecure test_p_test 
      check1 number;
    is 
       ut.expect ( p_test ( 1 , check1 )).to_output(1 );
   end;

i tried various other ways but to no avail 

then i tried before i saw your comments 
 procecure test_p_test 
      check1 number;
    is 
 p_test ( 1, check1  );
   ut.expect ( check1 ) .to_equal ( 1 );
end;


and it worked. 

Thanks anyway .. But seems like this functionality can be developed in the ut.expect with some extra parameter to signinfy what are you running a function or procedure ...

But anyway that might be difficult as well 

It was great to have a response from your end .. You did great job and the annotations are just magical :)

Many Thanks
Sunil

**Comment by sunil-choubey** [comment]
I think

**Comment by pesse** [comment]
I don't think it should be included in getting-started. That tutorial contains all basic aspects and shouldn't be increased in size because that will lead to even lesse people to read it :)
Why don't you create an example of functionality and test in https://github.com/utPLSQL/utPLSQL-demo-project - we want to increase the examples there anyway.

**Comment by jgebal** [comment]
I don't think it requires an example at all.
It would be example of: how you do PLSQL programming.
utPLSQL is no magic. It falls under limitations of PLSQL language.

In PLSQL, if you want check for value of OUT parameter of a procedure, you need to assign it to a variable and check the variable.
No magic at all - pure PLSQL.

**Comment by sunil-choubey** [comment]
Ok Thanks , Then in that case , I will close the Issue .. As it was not an issue but rather an issue with me :) .. Many Thanks and It was great to have inputs from both of you .. Thanks again!!
