### ISSUE TITLE
Comparing collections

### ISSUE THREAD

**Issue by sunil-choubey** [utPLSQL/utPLSQL#583]
Hi Jacek and Pesse ,

   Sorry to bug you again!

   one more request , If you can assist.

   I want to compare two collections ( simple Associated arrays of varchar2 ) .. 
    I have few methods by which I can do that 
1) compare the count -- working o 
2)  compare each element ( if ordered correctly ) -- working ok 

   I see that in one of your examples you are using the anydata.convertcollection , it is somehow not working for me and giving me the below error.

incorrect usage of method ORA-22370: incorrect usage of method ConvertCollection

Please suggest.

**Comment by pesse** [comment]
Please provide a full example

**Comment by jgebal** [comment]
Hi @sunil-choubey 
If your arrays are defined as PLSQL types not as schema level types, you need to use cursor to compare them.
`ANYDATA` accepts only objects and collections defined at schema-level.
https://github.com/utPLSQL/utPLSQL/blob/v3.0.4/docs/userguide/expectations.md#using-cursors-to-compare-plsql-records-on-oracle-12c

**Comment by sunil-choubey** [comment]
Thank you very much Jacek  it helped and Sorry Pesse I will start giving full examples !!
