### ISSUE TITLE
Space between % and annotation name cause annotation to not work.

### ISSUE THREAD

**Issue by sunil-choubey** [utPLSQL/utPLSQL#584]
Hi Team, 

     I see that if somehow there is a space between % and annotation name for example

    eg: suite ...  % suite    .. then that annotation does not work .. I know annotations are already magical but just thought should bring to your attention.

Thanks
Sunil

**Comment by jgebal** [comment]
As per documentation, annotation *is* `%suite`. If it is `% suite` it is not annotation anymore.
Making it more relaxed doesn't bring value but brings huge complexity and can cause confusion.

**Comment by sunil-choubey** [comment]
ok Jgebal. Agreed!
