### ISSUE TITLE
Utassert packages  of v2 not working in v3

### ISSUE THREAD

**Issue by jlprasath** [utPLSQL/utPLSQL#595]
utassert packages like 
**utAssert.this | utAssert.isnull utAssert.isnotnull |  utAssert.eq |  utAssert.eqtable |  utAssert.eqtabcount | utAssert.eqquery |  utAssert.eqqueryvalue |**  not working in version 3.0.1

**Comment by jgebal** [comment]
Hi @jlprasath
Of course they are not.
utPLSQL v3 is not the same thing as utPLSQL v3
Please refresh details in  documentation as well as readme on github.
