### ISSUE TITLE
connecting to jenkins 

### ISSUE THREAD

**Issue by jlprasath** [utPLSQL/utPLSQL#597]
Hi I took the ut_xunit_reporter with tests. But i am not aware how to use that with jenkins . Say If i have the xunit plugin in the jenkins, How to link the  utplsql  to xunit in the jenkins . Is there any documentation for the same .Please help me in it. Where to connect the utplsql in jenkin s?

**Comment by jgebal** [comment]
Use [utPLSQL-cli](https://github.com/utPLSQL/utPLSQL-cli/) to run your tests on Jenkins.
Example command line would be like below:
![jenkins](https://user-images.githubusercontent.com/1398171/36874688-c12d8e7c-1da4-11e8-899d-b5e9338df9d5.png)

- first command downloads specified version of utPLSQL-cli into jenkins workspace (that is optional). You will need to provide `ojdbc8.jar` yourself - see readme on utPLSQL-cli. You may also store the client in some common space on jenkins or have it included as part of the project you're building
- second command invokes utPLSQL on specific database and saves data from mutiple reports into separate files

Once this is done, all you need to do is just give the output file from `ut_xunit_reporter` to the Jenskins plugin.
![jenkins-publish](https://user-images.githubusercontent.com/1398171/36874816-4149cc4c-1da5-11e8-9a75-ad2a10b56e78.png)

Hope this helps.

**Comment by jlprasath** [comment]
Hi Thanks for the reply. Isn't it possible to use jenkins with utplsql alone without installing utplsql cli. I not able to install cli in the existing environment?

**Comment by jgebal** [comment]
How do you run your project on Jenkins?
Do you checkout your project from version control like GIT?
If so, you could just download the client and put it in your projects version control system directly.

There will be maven plugin coming soon so that will be another possibility.

**Comment by jgebal** [comment]
This looks like an infrastructure / configuration issue.
We provide you with tools to get the job done.
If you got sqlplus (oracle client) installed on Jenkins it is possible that you can get someone to put utPLSQL-cli there too.

**Comment by lwasylow** [comment]
As for jenkins use I suggest that you use cli mainly for being independent from sqlplus installation on server. I have run in such configuration from jenkins and from tfs with no problem. Also for jenkins with new release you will be use a cobertura code coverage to publish results apart from normal html publisher, which allow you to gate builds
