### ISSUE TITLE
using objects and collections

### ISSUE THREAD

**Issue by psqc** [utPLSQL/utPLSQL#599]
In the utplsql 3 version, I saw using equal on objects
**ut.ex­pect( anydat­a.c­onv­ert­Obj­ect­(l_­exp­ected) ).to_(
  equal( anydat­a.c­onv­ert­Obj­ect­(l_­actual) ) );**
equal on collec­tions
**ut.ex­pect( anydat­a.c­onv­ert­Col­lec­tio­n(l­_ex­pected) ).to_(
  equal( anydat­a.c­onv­ert­Col­lec­tio­n(l­_ac­tual) ) );**

But i was not able to check with a use case. Can anyone help with the use case.  Is anydata.convertObject a predefined function that exists ..or should be process ..
And For the object comparison , will it check the syntax or what will it really do..Please help me with the implementations of objects and collections.

**Comment by jgebal** [comment]
Hi @psqc
ANYDATA is part of oracle DB:
https://www.google.ie/search?q=oracle+anydata
As for how it works - documentation should give you an idea. Best to write a simple failing test and see for yourself.

**Comment by psqc** [comment]
I tried using it in a example.. I ended up in a error. 

```
 procedure collection_compare is 
TYPE list_of_names_t IS TABLE OF VARCHAR2 (100);
 happyfamily   list_of_names_t := list_of_names_t ();
 TYPE list_of_names_b IS TABLE OF VARCHAR2 (100);
 happyfamily1   list_of_names_t := list_of_names_t ();
 BEGIN
 happyfamily.EXTEND (4);
      happyfamily(1) := 'Veva';
      happyfamily(2) := 'Chris';
      happyfamily(3) := 'Eli';
      happyfamily(4) := 'Steven';
      
 happyfamily1.EXTEND (4);
      happyfamily1(1) := 'Veva';
      happyfamily1(2) := 'Chris';
      happyfamily1(3) := 'Eli';
      happyfamily1(4) := 'Steven';
      
      ut.expect( anydata.convertCollectin(happyfamily) ).to_(
  equal( anydata.convertCollection(happyfamily1) ) );
            END ;
```
can anyone help in correcting me ..?

**Comment by jgebal** [comment]
This only works for schema level collections. If you want to compare package-level collections you need to use cursor:
https://github.com/utPLSQL/utPLSQL/blob/v3.0.4/docs/userguide/expectations.md#using-cursors-to-compare-plsql-records-on-oracle-12c

**Comment by jgebal** [comment]
If you try examples from documentation you will see how it works (with schema level types created)
