### ISSUE TITLE
Implement jUnit XML formatted report

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#60]
Implement jUnit XML report by creating new reporter class.

Reporter should be able to print it's content to serveroutput, or return as clob/xmltype variable. Most likely the reporter would be configured and processed by a CI using SQlplus so spooling might be a way it can workout.

**Comment by Pazus** [comment]
Schema http://windyroad.com.au/dl/Open%20Source/JUnit.xsd

**Comment by mathewbutler** [comment]
Would be nice to have XML wrapped in a pipelined function that can be used in a query. Same approach as dbms_xplan.

**Comment by rlove** [comment]
@mathewbutler pipelining has a side effect that the xml would never be valid until the last node of the document was received.      What current software has support for the this streaming of the JUnit XML file?    

How we implement JUnit XML support is critical as you can't implement via [DBMS_XMLDOM](https://docs.oracle.com/cd/B28359_01/appdev.111/b28419/d_xmldom.htm) and have support for the pipelined function if there is a true need. 

I have envisioned the reporter having a variable called  XML that was a XML_TYPE that could be then be used in variety of different ways including from a select statement.

**Comment by Pazus** [comment]
Currently I plan to use `dbms_xmldom` so no real time reporting. Even more as for Teamcity CI doesn't support partly XML parsing. There are two ways to achieve realtime reporting: messages (#62) and realtime publishing of XML-report file, this means one have to save current report as XML (valid but containing only a piece of results), then notify the CI to grab the report and process it, then replace old XML with new one containing more data, notify again an so on. 
Another problem that raises with such approach is that tests have to be executed in another session (via job for example) and pipe or somehow transfer the results to the session reporting to the CI. Sounds complicated.

Let's stay with offline reporting with jUnit format for this issue and maybe think about switching to xunit as jUnit doesn't support suite hierarchies.

**Comment by mathewbutler** [comment]
@rlove since sqlplus supports XMLType this is a poorly thought through request. So no true need. 

Thanks.

**Comment by jgebal** [comment]
I've created a JUnit reporter based on the xsd found on the web:
http://stackoverflow.com/questions/4922867/junit-xml-format-specification-that-hudson-supports
http://stackoverflow.com/questions/8079071/xml-format-specification-dtd-xsd-for-unit-test-reports
https://gist.github.com/kuzuha/232902acab1344d6b578
Tested on my local Jenkins - looking really nice.
This task should get resolved by #146 

The JUnit 4 xsd supports nested suites, and so the reporter is producing such data.
