### ISSUE TITLE
 ORA-02055 from ut_runner when having a non-manual rollback test on a DB Link

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL#601]
Setting: 
We have a view available via DB link and a test which selects from it. The test-suite is rollback-automatic, not manual.

Problem:
Wenn calling `ut_runner.run` we get ORA-02055 after **all** tests are run (not immediately after the DB-link test).
If we switch the DB link test to rollback-manual it's not an issue (as long as we rollback properly)
ut.run doesn't have that problem because of an additional rollback.

We should maybe catch that situation more specifically and add a test

**Comment by jgebal** [comment]
Or maybe we should move the `pragma autonomous_transaction` and rollback from `ut.run` to `ut_runner.run`?
Looks like a quick win.
Let me see if I can create a test to reproduce that issue and then do a fix for it.
