### ISSUE TITLE
table comparison results .

### ISSUE THREAD

**Issue by jlprasath** [utPLSQL/utPLSQL#612]
In the documentation, U said thAT results would be like 

test_cursor_compare
  do_test [.052 sec] (FAILED - 1)
 
Failures:
 
  1) do_test
      Actual: refcursor [ count = 4 ] was expected to equal: refcursor [ count = 3 ]
      Diff:
      Columns:
        Column <ID> is misplaced. Expected position: 1, actual position: 4.
        Column <SALARY> data-type is invalid. Expected: NUMBER, actual: VARCHAR2.
        Column <GENDER> [position: 1, data-type: CHAR] is not expected in results.
      Rows: [ 4 differences ]
        Row No. 1 - Actual:   <SALARY>25000</SALARY>
        Row No. 1 - Expected: <SALARY>10000</SALARY>
        Row No. 2 - Actual:   <FIRST_NAME>TONY</FIRST_NAME><LAST_NAME>STARK</LAST_NAME><ID>3</ID><SALARY>100000</SALARY>
        Row No. 2 - Expected: <ID>2</ID><FIRST_NAME>LUKE</FIRST_NAME><LAST_NAME>SKYWALKER</LAST_NAME><SALARY>1000</SALARY>
        Row No. 3 - Actual:   <FIRST_NAME>JESSICA</FIRST_NAME><LAST_NAME>JONES</LAST_NAME><ID>4</ID><SALARY>2345</SALARY>
        Row No. 3 - Expected: <ID>3</ID><FIRST_NAME>TONY</FIRST_NAME><LAST_NAME>STARK</LAST_NAME><SALARY>100000</SALARY>
        Row No. 4 - Extra:    <GENDER>M</GENDER><FIRST_NAME>LUKE</FIRST_NAME><LAST_NAME>SKYWALKER</LAST_NAME><ID>2</ID><SALARY>1000</SALARY>
      at "UT3.TEST_CURSOR_COMPARE", line 22 ut.expect(l_actual).to_equal(l_expected);
      
       
Finished in .053553 seconds
1 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)

--------------------------

But while running we are not getting  theses details 

Columns:
        Column <ID> is misplaced. Expected position: 1, actual position: 4.
        Column <SALARY> data-type is invalid. Expected: NUMBER, actual: VARCHAR2.
        Column <GENDER> [position: 1, data-type: CHAR] is not expected in results.

Instaed of the above result, 
We are getting as just 

anonymous block completed
test_cursor_compare
  do_test [.016 sec] (FAILED - 1)
 
Failures:
 
  1) do_test
      Actual: 
          <ROW><GENDER>M</GENDER><FIRST_NAME>JACK</FIRST_NAME><LAST_NAME>SPARROW</LAST_NAME><ID>1</ID><SALARY>25000</SALARY></ROW>
          <ROW><GENDER>M</GENDER><FIRST_NAME>TONY</FIRST_NAME><LAST_NAME>STARK</LAST_NAME><ID>3</ID><SALARY>100000</SALARY></ROW>
          <ROW><GENDER>F</GENDER><FIRST_NAME>JESSICA</FIRST_NAME><LAST_NAME>JONES</LAST_NAME><ID>4</ID><SALARY>2345</SALARY></ROW>
          <ROW><GENDER>M</GENDER><FIRST_NAME>LUKE</FIRST_NAME><LAST_NAME>SKYWALKER</LAST_NAME><ID>2</ID><SALARY>1000</SALARY></ROW>
       (refcursor) 
      was expected to equal: 
          <ROW><ID>1</ID><FIRST_NAME>JACK</FIRST_NAME><LAST_NAME>SPARROW</LAST_NAME><SALARY>10000</SALARY></ROW>
          <ROW><ID>2</ID><FIRST_NAME>LUKE</FIRST_NAME><LAST_NAME>SKYWALKER</LAST_NAME><SALARY>1000</SALARY></ROW>
          <ROW><ID>3</ID><FIRST_NAME>TONY</FIRST_NAME><LAST_NAME>STARK</LAST_NAME><SALARY>100000</SALARY></ROW>
       (refcursor) 
      at "UT31.TEST_CURSOR_COMPARE", line 22 ut.expect(l_actual).to_equal(l_expected);
      
       
Finished in .031 seconds
1 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)
 .. is there any specific setting needs to  be modified ?

**Comment by jgebal** [comment]
This is because you're looking at documentation of develop branch.
This functionality will become available soon with next release.
See http://utplsql.org/utPLSQL/ for documentation of released versions.
