### ISSUE TITLE
Rollback type propagation from parent to child

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#618]
Since we set transaction isolation at parent level and allow visibility of parent suite setup to child suites, rollback type set at parent should propagate to child suite.

Currently, only rollback type within package is propagated..
That is, if you set `--%rollback(manual)` at suite level it will propagate to tests within suite, not to child suite packages.

**Comment by Pazus** [comment]
Is it possible to override parents setup by a child?
Is it possible to construct 
`Manual-auto-manual` for a suite of three levels? I suppose it should be possible to do so.

**Comment by jgebal** [comment]
It will be, as long as you set it explicitly on all 3 levels
