### ISSUE TITLE
Realtime reporting using dbms_pipe

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#62]
Implement execution of the tests run in separate session. 
Implement reporter that pushes messages to the dbms_pipe and never fail.
Implement pipelined function which produces results as they appear in the pipe. Selecting from thee function will allow to have realtime report results in the CI.

As a first approach Teamcity realtime reporting can be used.

**Comment by jgebal** [comment]
Seems like this is similar to #65
