### ISSUE TITLE
Add Code coverage gathering and reporting

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#63]
We need to add a reporter that will run a code coverage analysis using plsql profiler.
The reporter should provide few different ways to generate reports into format of XML for consumption by other tools (CI/Sonar) and/or HTML for viewing the coverage report.
The different output formats could be achieved by the decorator class.

**Comment by Pazus** [comment]
New 12.2 feature is made for this. We should look at it when 12.2 is available.

**Comment by jgebal** [comment]
Done
