### ISSUE TITLE
ut_xunit_reporter doesn't show procedure names

### ISSUE THREAD

**Issue by GolezTrol** [utPLSQL/utPLSQL#633]
`<testcase classname` contains just the name of the package.

This surprises me, as the package name is already included in the parent `testsuite` element, so I wonder if this is by design or not, and if this can be changed.

Context: I'm trying to create a testrunner that allows you to (visually) select tests, and having the procedure name in there would be a requirement to make that work. 
Having the schema as well would be a nice added benefit, but that's something that can be worked around.

**Comment by jgebal** [comment]
Hi
In java you will get classname not a methodname.
Similarly in PLSQL it will show package (program unit) name not the procedure.

**Comment by jgebal** [comment]
@GolezTrol, does that answer your question?
Looking at how Jenkins reads and displays the data from reporter it seems to be perfectly fine.

**Comment by pesse** [comment]
@GolezTrol utPLSQL 3.1.0 will make it much easier to include custom reporters. Don't hestitate to get in touch with us via [slack](https://utplsql.slack.com/messages). Maybe we can help :)
