### ISSUE TITLE
How to handle outputs from several reporters?

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#65]
With sqlplus and any other sql consoles it's really hard to spool data from several different streams into several output files.
We need a nice solution that would allow us to save reporters outcomes into different files on client side.

**Comment by Pazus** [comment]
Currently I think that reporter class contains both output stream and report logic. Except dbms_output reporter all other reporters I think wil gather the data inside and process it at the end of the whole run. jUnit, Rspec and others go that way. Very few reporters will use other output streams like pipe or file. 

And I don't have nice design how this "output switching abstraction" can be implemented. At first I'd leave everything to the reporter.

**Comment by Pazus** [comment]
Maybe I have one :) "Streaming reporter" wich has method `stream`. By streaming reporter I mean the one that streams right away and doen't need to process to the end before it can form the report. So the argument of `stream` is varchar2 and that allows to build and abstraction common for different implementations.
