### ISSUE TITLE
Download of Cheat-sheet not possible

### ISSUE THREAD

**Issue by walter-weinmann** [utPLSQL/utPLSQL#656]
The pdf download points to https://www.cheatography.com/#

**Comment by jgebal** [comment]
That is a general issue on cheatography.com
No PDF download is available there at the moment

**Comment by walter-weinmann** [comment]
The issue would easily be solved if the pdf would be available here.

**Comment by jgebal** [comment]
We made a decision not to do so to avoid discrepancy between two locations.
Fair point though.

**Comment by jgebal** [comment]
PDF's are back.
