### ISSUE TITLE
A warning when installing v3.1.1

### ISSUE THREAD

**Issue by Mikhail5544** [utPLSQL/utPLSQL#657]
Hello,

There is one warning when we installing utPLSQL v 3.1.1. Could you fix it please? 

Greate thanks.

[14:06:18][Step 2/2] --------------------------------------------------------------
[14:06:18][Step 2/2] Installing component UT_COMPOUND_DATA_HELPER
[14:06:18][Step 2/2] 
[14:06:18][Step 2/2] Предупреждение: Пакет создан с ошибками компиляции. (Warning: The package was created with compilation errors)

**Comment by jgebal** [comment]
Please provide the following:
- steps you took to do the installation
- database version
- actual errors that show in package body after compilation

**Comment by Pazus** [comment]
@Mikhail5544 Could you please check `execute` is granted on `sys.dbms_crypto` to the utPLSQL schema

**Comment by Mikhail5544** [comment]
@jgebal Hello!

Oracle Database 11g Release 11.2.0.4.0 - 64bit Production
We lanched "install_headless.sql" script with default parameters.

1. Grants on sys.dbms_crypto is OK
2. Screenshot with Compilation errors for PACKAGE UT3.UT_COMPOUND_DATA_HELPER is attached.
It's  something with UT_DATA_VALUE_REFCURSOR

![warning screenshot](https://user-images.githubusercontent.com/12762651/39629179-f581238c-4fb3-11e8-9404-04843b94c3ad.jpg)

Compilation errors for PACKAGE UT3.UT_COMPOUND_DATA_HELPER

Error: PLS-00201: идентификатор 'UT_DATA_VALUE_REFCURSOR' должен быть объявлен
Line: 60

**Comment by pocelka** [comment]
No issues on 11.2.0.3

Do you have UT_DATA_VALUE_REFCURSOR type compiled?

**Comment by Mikhail5544** [comment]
As far as I understand the problem is:
Specification of UT_COMPOUND_DATA_HELPER installs earlier than ut_data_value_refcursor.tps and it uses that type.
![pic2](https://user-images.githubusercontent.com/12762651/39631833-fd5ab8ea-4fbb-11e8-9faf-de8a4012694b.jpg)
