### ISSUE TITLE
non-sysdba installation

### ISSUE THREAD

**Issue by pocelka** [utPLSQL/utPLSQL#658]
Currently utPLSQL requires that most of the installation is done by DBA. Some companies have however strict split of responsibilities i.e.:
- DBA manage datase, i.e. creates users
- Developer manages his own schema, and installs all required files.

With the current documentation / installation files, it is not possible to properly execute ./source/create_synonyms_and_grants_for_user.sql since  file contains grants (should be executed from utplsql schema) and also synonyms for user schema.

The file should be split to two to solve this issue.

PS: if required I could help with this easy change however, I've still hard time to understand git / branches concept, so maybe I will have some stupid questions (i.e. on slack).

**Comment by jgebal** [comment]
You're more than welcome to do the change.
If help is needed, just ask on Slack
