### ISSUE TITLE
utPLSQL option disabled in SQL Developer

### ISSUE THREAD

**Issue by itguyforautomation** [utPLSQL/utPLSQL#663]
utPLSQL version: v3.0.0
utPLSQL-SQLDeveloper plugin Version: 0.2.1
Database Version: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit

Problem:
“Run utPLSQL test” option went disabled

Troubleshooting:
1. Uninstall, and install the utplsql plugin, and restart SQL Developer tool.
2. Uninstall, and install the SQL Developer tool & utplsql plugin, and restart SQL Developer tool.

But the problem still persists. Can you help us with necessary steps to fix the issue?

![image](https://user-images.githubusercontent.com/39102994/39782282-b8480e20-52df-11e8-9f2f-e9a35a129517.png)
# #

**Comment by jgebal** [comment]
Can you put this issue under:
https://github.com/utPLSQL/utPLSQL-SQLDeveloper/issues
Thanks

**Comment by jgebal** [comment]
@itguyforautomation, can you provide exact version of utPLSQL by executing:
`select ut.version() from dual`

**Comment by itguyforautomation** [comment]
v3.0.4.1372

**Comment by itguyforautomation** [comment]
It works great after using the latest version 0.3.0 snapshot

**Comment by jgebal** [comment]
Great!
