### ISSUE TITLE
automcompile not available in v3

### ISSUE THREAD

**Issue by jlp-work** [utPLSQL/utPLSQL#664]
Hi,

I would like to know whether is  utConfig.autocompile(bool);  available in latest version of utplsql (Version 3)

**Comment by jgebal** [comment]
utPLSQL v3 is a rewrite of unit testing framework. It doesn't use DB server filesystem anymore.
Have a look at readme and documentation to find out more details.
There are also webinars on ODTUG and Prohuddle.

**Comment by Shoelace** [comment]
as an aside i can only think of two possible options for implementing this..
1. require the scripts be available on the server via a directory object
2. a client side feature

**Comment by jgebal** [comment]
That's the thing. Should this be function of utPLSQL? I think this a preliminary step before running tests.
You can safely do all 3 from SQLPLus with right privileges.

**Comment by jgebal** [comment]
Actually if it's just about recompile - that should be pretty easy to do, as long as **user executing the tests** has proper privileges

**Comment by jgebal** [comment]
@lwasylow 
Isn't this something you have fixed as part of current develop branch?
@jlp-work are you referring ony to the funcyionality of being able to recompile and rin a package that was invalid due to dependency recompliation?

**Comment by lwasylow** [comment]
If we referring to option of recompile test that was invalidated via dependency as part of test execution than, yes. Utplsql will attempt to call test package and autocompile via call if possible

**Comment by jgebal** [comment]
@lwasylow - can you point to a test that validates this? I can't find it.

One outstanding thing would be to parce package spec if it is invalidated (status =invalid) but has no errors ( no data for package in dba_errors)

**Comment by lwasylow** [comment]
@jgebal  apologies, its only when package that being tested, not utplsql test itself. test in ut_run.
