### ISSUE TITLE
uninstall sql script not comprehensive

### ISSUE THREAD

**Issue by SpotMeFive** [utPLSQL/utPLSQL#673]
We are using TeamCity to install and uninstall utPLSQL each testing cycle in the application owner schema. 

As part of our database build, we are checking for modified objects and I noticed we are incurring leftover objects from the framework after the uninstall script is executed.

Can you please advise if this is a bug or intended behavior? I have attached my modified copy of the uninstall.sql which seems to deal with it.

Additionally: We are on version 3.0.4 of the framework but I couldn't find any bug addressed in the versions since. There also seem to be types leftover when actually executing tests (not captured in the recreation steps below).

After uninstall:
SQL> SELECT OBJECT_TYPE,COUNT(*) FROM USER_OBJECTS
  2  GROUP BY OBJECT_TYPE;
SEQUENCE                         1
TABLE                            3
INDEX                            3

To recreate: 

1. Run user creation script in /source
2. install using install.sql
3. uninstall using uninstall.sql
4. run statement:
SQL> SELECT OBJECT_TYPE,COUNT(*) FROM USER_OBJECTS
  2  GROUP BY OBJECT_TYPE;

[orig.uninstall.log](https://github.com/utPLSQL/utPLSQL/files/2009487/orig.uninstall.log)
[uninstall.log](https://github.com/utPLSQL/utPLSQL/files/2009488/uninstall.log)
[install.log](https://github.com/utPLSQL/utPLSQL/files/2009489/install.log)
[uninstall.sql.txt](https://github.com/utPLSQL/utPLSQL/files/2009493/uninstall.sql.txt)

**Comment by lwasylow** [comment]
Can you check against 3.1.1 pls? There was a fix that related to some synonyms and type not dropped.

**Comment by jgebal** [comment]
Sequence, tables and inexres are left for PLSQL profiler. They should do no harm if they stay and also the installation scrip handles their existence.

**Comment by SpotMeFive** [comment]
Thanks for the quick response:

@lwasylow, I'll give that a shot.

@jgebal, I agree there is no harm. But they are installed as part of the framework. If I uninstall the framework, should they remain? If so, to what end? Is this to avoid damaging analysis that potentially already exists in those tables unrelated to utPLSQL? Should we be directing this to a separate store somehow? I imagine this is one of the reasons the documentation suggests installing to a separate schema. How about mentioning that in the documentation if we prefer not modifying the uninstall?

Also, I wanted to thank you, @jgebal,  and the community for the v3 re-write (we just upgraded from v2). Head and shoulders above the last version; no offense to @stevenfeuerstein.

**Comment by lwasylow** [comment]
@SpotMeFive  one thing that jumps to my mind. There is a big diffrence in terms of 3.0.4 and 3.1.1 some types etc are removed. Did you do install on clean (empty schema ) or did you do upgrade from existing ?

**Comment by jgebal** [comment]
@SpotMeFive - thanks for the kudos on the work we did.
Also, thanks for spotting and reporting the issue.

**ACTION NOTE**
> - We need to assure that `uninstall` removes all objects that it should
> - We need to add this as a test to our CI/CD pipeline so we don't fall into regression.
> - We need to add option to remove all sources, including `dbms_profiler` tables.

**Comment by pocelka** [comment]
@jgebal:
I think that the best would be to create create a procedure to remove objects in the correct order. This way we could ensure that when new object is added it would be removed even if somebody would it normally forget to add it to the uninstall script. At the end of the uninstall this procedure / package would be dropped as a last step. What are your thoughs?

Was there some historical reason why there is each object named in the uninstall.sql script?

**Comment by jgebal** [comment]
I think the best way to protect against a missing element in the `uninstall` script is by adding the `uninstall` as part of deployment pipeline and validating that all items were removed.
