### ISSUE TITLE
Implement way to validate xml reports against xsd

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#684]
As part of test or build would be beneficial to validate produced xml reports against there xsd schemas where exists. Example would be junit. This could be achieved by either using Dbms packages to validate schema or after reports produced at then end against xml validator api.

**Comment by lwasylow** [comment]
I don't see any rest api available online to do validation. However simple jar inside build should do the trick. Second option is to write oracle test with registered xsd inside database

**Comment by jgebal** [comment]
I would go with jar as we don't need this indide utPLSQL but unly on build server to perform post-run validations.

**Comment by lwasylow** [comment]
Fixed
