### ISSUE TITLE
Object remain after uninstall

### ISSUE THREAD

**Issue by j-sieben** [utPLSQL/utPLSQL#693]
Hi,
the following object seem to be missing in the uninstall script:
-- Types
UT_COMPOUND_DATA_VALUE, UT_HAVE_COUNT

-- Packages
UT_COMPOUND_DATA_HELPER, UT_COVERAGE_BLOCK, UT_COVERAGE_HELPER_BLOCK, UT_COVERAGE_HELPER_PROFILER, UT_COVERAGE_PROFILER

-- Tables
DBMSPCC_BLOCKS, DBMSPCC_RUNS, DBMSPCC_UNITS

It would be nice if the install script would check for execute grants on DBMS_CRYPTO and DBMS_LOCK upfront to avoid having to uninstall, grant the privs and reinstall again.

Thanks for the outstanding work though!

Best regards,

Jürgen

**Comment by jgebal** [comment]
Hi
Good idea with the check - definitely worth adding.

**Comment by jgebal** [comment]
I've just fixed the uninstall to remove all objects and its now in develop branch. 
What version you were using?

**Comment by j-sieben** [comment]
Hi jgebal,

thanks for the ultimately fast fix! I just downloaded the latest version some minutes ago and found this issue when trying to install in different users. I first installed into a user but then decided to create a new user for utPLSQL and grant access to the initial user, so this when these issues popped up.

**Comment by jgebal** [comment]
You probably wouldn't encounter issues if you would use provided create user script.
https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/install.md#manual-installation-procedure

**Comment by j-sieben** [comment]
Yes, I saw that later on. But I first wanted to install utPLSQL in an already existing user, which I later found to be a bad idea. Basically, you're right.

**Comment by jgebal** [comment]
One issue with checking grants.
Install can be ran as SYSDBA user or as _any_ user (when not using headless install).
Depending on who is running we need to check different data dictionary tables `DBA_TAB_PRIVS` or `USER_TAB_PRIVS`.
The reason is that user performing the install doesn't really have to have access to DBA views.

**Comment by j-sieben** [comment]
Hi,
and how about all_tab_privs? This view is accessible by everyone and gives the mecessary information. 

Beste Grüße,

J. Sieben

ConDeS Gmbh & Co. KG
Mühlenstraße 229
41236 Mönchengladbach

Fon: +49-2166-12 44 33
Fax: +49-2166-12 44 34

**Comment by jgebal** [comment]
Actually it should be:
- `ALL_TAB_PRIVS` when installing into current (connected) user schema
- `DBA_TAB_PRIVS` when installing as SYSDBA into another user schema
