### ISSUE TITLE
Test case class name is empty in X/Junit output

### ISSUE THREAD

**Issue by matcruse** [utPLSQL/utPLSQL#696]
In v3.1.1 the test case class name in the output for ut_junit_reporter is empty:
Output is as follows, i.e.:
`<testsuites ..><testsuite ..><testcase classname="" .. >`

Test is run via SQL console with `ut.run(':suite.testpackage', ut_junit_reporter());`

In comparison to v.3.0.4 this seems not to work as expected anymore, or is something missing in the "run" configuration?

**Comment by lwasylow** [comment]
Hi can you look at #659 and see if that the same issue? If so is fixed in next patch. If not can you please supply a full test case?

**Comment by matcruse** [comment]
Hi, regarding to issue #659 I tested with all procedure names in lower case and it worked, the testcase is contained in the output of `ut_junit_reporter`. Thank you for the swift reply.

**Comment by lwasylow** [comment]
That's great. Proper fix will be soon in new release. Cheers
