### ISSUE TITLE
How to do a collaberative document(s) for v3 design?

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#7]
There's been some talk in recent months about working on a new major version of utPLSQL. This is likely to include dropping support for older versions of Oracle and giving the code base a thorough spring clean.

What's the best way for multiple people to work on a v3 design document? This will be very iterative and (hopefully!) have contributions from multiple people.

I'm far from an expert on GitHub, so I'm not sure of the best way to do this... :confused: Any suggestions gratefully received...

**Comment by PaulWalkerUK** [comment]
@rlove: it sounds like you're a bit more experienced with GitHub than me - do you have any thoughts on this?

**Comment by rlove** [comment]
A couple of options I can see

1. Create a "feature/ver3" branch and store the design document there.    
Pro: Collaborative edited through pull  requests which can be commented on.   
Pro: Can be edited offline
Pro: The ultimate document the becomes part of the documentation.
Con: Not as visible as option 2.

2.  Use the Wiki feature (which is just another git repository)
Pro: Has a easy to use editor online.
Pro: Anyone can edit (if you set that permission)
Pro/Con: Comments would have to be in the actual documentation and not offline like a pull request would have.
Con: Only you can edit (If you don't set that permission)
Con: Wiki's can be spammed.

I suspect there is small enough group that would work on version 3 that option 2 would be easy enough to do, and is as easy as turning it on.

**Comment by jgebal** [comment]
I like the idea of mixing both options.
- Have new code for v3 release version in a separate feature branch
- Have wiki to document the changes of v3
You can always keep wiki divided into versions, so the current version doc would not be impacted by version under development.

**Comment by rlove** [comment]
I am currently working on some prototype code to demonstrate some potential v3 features and design.     I will share it when I am finished,  either as an issue here, or in any area setup.

**Comment by jgebal** [comment]
Here is an example of a website hosted on github.
https://github.com/impactmapping/www.impactmapping.org
And the website itself:
https://www.impactmapping.org/

**Comment by rlove** [comment]
@PaulWalkerUK can we try [enabling the wiki](https://help.github.com/articles/changing-access-permissions-for-wikis/), so we can edit it.    

I believe it's a good place to start building a roadmap of features we want for version 3 and what features we should take from both @DDieterich and my proposals.

**Comment by PaulWalkerUK** [comment]
Done. Let me know if it doesn't work...

**Comment by Shoelace** [comment]
i seem to have editiing abilities now..   i edited a page with stuff as proof.
