### ISSUE TITLE
Travis-CI automation of release

### ISSUE THREAD

**Issue by rlove** [utPLSQL/utPLSQL#70]
This will enable automation of the release.   This is only for the version 3 code base.
1. Run Build/Tests and make sure everything is ok.
   - This includes building of documentation.
2. Create ZIP file : 
   - Generated Documentation - \docs\ directory
   - Lib\Any_data directory
   - source\ Directory
   - Root blank for now, but will most likely include a release readme of some type in the future.
3.  Updates gh-pages with new "Release Specific" version documentation.    Which is documentation published on a push, which is addressed in Issue #59 
4.  Creates release with Zip File.

Notable documenation to help:
- https://docs.travis-ci.com/user/deployment/releases/
- https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A
- https://gist.github.com/vinceallenvince/a7611b10f84e61eebdcc

**Comment by Pazus** [comment]
just to remind that lib\any_data is not needed any more

**Comment by rlove** [comment]
To start this off I submitted pull #166
