### ISSUE TITLE
Not All sources were successfully Installed after install.sql

### ISSUE THREAD

**Issue by magarcia05** [utPLSQL/utPLSQL#700]
Hello Guys, 

I am trying to install utPLSQL on a schema that I had created for my projects. After running the installation I get errors that are preventing me to use the framework. I am attaching an image with the errors that I am facing. Note: My Oracle db version is 12C

Please let me know if you need additional information.

![img](https://user-images.githubusercontent.com/30537614/42352645-a418e05a-8070-11e8-8f70-91e37ac54086.PNG)

![img2](https://user-images.githubusercontent.com/30537614/42352670-c7135fe0-8070-11e8-95f6-93f6a6ad9ff5.PNG)

**Comment by pocelka** [comment]
Which version are you trying to install? Did you use install script?

**Comment by jgebal** [comment]
There was a bug in documentation for 3.1.0 and 3.1.1
You will need to have grant execute on `dbms_crypto` to use utPLSQL 3.1 and above.
See updated doc in develop branch: https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/install.md#recommended-schema

**Comment by magarcia05** [comment]
Hi pocelka, I was indeed using the install script and I was trying to install the latest utPLSQL version

**Comment by magarcia05** [comment]
Hello jgebal, I believe I do not have grant execute on dbms_crypto. I will try to grant the access and will let you know if there are any issues. Thanks for your help!!

**Comment by jgebal** [comment]
Thanks for closing the issue @magarcia05
I assume all work well for you now?
