### ISSUE TITLE
Update sonar configuration to use branches

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#708]
sonarcloud.io supports multi-branch projects as well as PR notifications for quite some time now.
It would be great to update our project configuration to take benefit from new features of sonar.

If someone wants to take action on this, I can grant access to sonarcloud.io project for utPLSQL.

**Comment by lwasylow** [comment]
Do we want to run sonar on every branch created like feature etc, or only in PR into develop?

**Comment by jgebal** [comment]
It shouldn't cost anything.
We already run coveralls on every feature branch and it giver pretty cool overview :)
https://coveralls.io/github/utPLSQL/utPLSQL

**Comment by lwasylow** [comment]
You got my interest, I will have a read about these features, can be handy to know anyway.

**Comment by jgebal** [comment]
Here is the read:
https://sonarcloud.io/documentation/branches/index
https://docs.travis-ci.com/user/sonarcloud/

**Comment by lwasylow** [comment]
Sounds like all is coming to update when to run analysis and tokenize a sonar properties to allow for dynamic branch/pr key.
Should be fairly simple to do.
