### ISSUE TITLE
Coverage - pck files are not included

### ISSUE THREAD

**Issue by Kh3pra** [utPLSQL/utPLSQL#715]
.pck (Combined package specification plus body) files are not being included in the coverage reports given that they are not is the pair list: ut_file_mapper.default_file_to_obj_type_map

**Comment by jgebal** [comment]
Hi @Kh3pra 

From Oracle database perspective, package spec and body are separate objects.

When running code coverage it is impossible to map DB object to file properly unless it's a 1:1 mapping of file-to-object.

Line numbers reported by coverage are line numbers of compiled PLSQL source code. If we will map coverage to a file containing more than just package body, the line numbers will not match.

**We cannot support single-file spec & body as the line numbers of your source code in file must match line numbers of compiled source code.**

The same goes for storing triggers together with table definition in single script.
We will not be able to report code coverage on a trigger that is part of create table script.


*Side note*
>Keeping spec & body in single file can cause some issues with automated deployments as you will always redeploy spec and body together, even when you change body only. That can lead to invalidation of multiple dependencies, create multiple objects in invalid state. Those will require recompilation, slow down your deployment process and will make it harder to validate that nothing is broken after install.

**Comment by Kh3pra** [comment]
Hi @jgebal,

Ok, understand your point. I was having offset on the sonarqube coverage reports due to the spec being in the same file as the body.
I still have an issue but it is on our side, even when splitting the spec and body I still have an issue with offset but that is due to two commented lines at the start of the file (which are needed for our current deploy process).

Thanks for the feedback.
