### ISSUE TITLE
Documentation: additional context naming is done via --%displayname annotation but in docu it shows --%description

### ISSUE THREAD

**Issue by nrogachev** [utPLSQL/utPLSQL#726]
Hi guys, first of all thanks a lot for the new version!

There is a minor issue with the docu - new feature to provide additional context description is working via --%displayname annotation, but in docu example it says:
```
  --%context(remove_rooms_by_name)
  --%description(Remove rooms by name)
```
Of course after that you get a warning that --%description annotation is not supported.

Also in the "Supported annotations" section of the docu it would be nice to see some mentioning of this new possibility in --%displayname and --%context sections.

**Comment by jgebal** [comment]
Thanks for reporting that issue.
It's now resolved
