### ISSUE TITLE
How to get output from ut_runner.run ?

### ISSUE THREAD

**Issue by ezsimonizer** [utPLSQL/utPLSQL#746]
Hi,

I was able to use ut.run() successfully­.
Now I'm trying to user ut_runner.run().
Could not figure it out.
I'm working out of PLSQL Developer.

Documentation says

The concept is pretty simple.

1. in the main thread (session), define the reporters to be used. Each reporter has it’s output_id and so you need to extract and store those output_ids.
2. as a separate thread, start ut_runner.run and pass reporters with previously defined output_ids.
3. for each reporter start a separate thread and read outputs from the ut_output_buffer.get_lines table function by providing the output_id defined in the main thread.

Could you give an example of a script that would do that?

Thanks.

**Comment by lwasylow** [comment]
Hi what is exactly you trying to achieve?
have a look how it's done in one of tests
https://github.com/utPLSQL/utPLSQL/blob/develop/old_tests/RunAll.sql

**Comment by jgebal** [comment]
`ut_runner.run()` is not documented as it is not to be used to manually run the tests.
Is there anything particular that you want to do and you can't do it with ´ut.run´?
´ut_runner´ should probably be removed from documentation or moved to a different topic (integration).

**Comment by ezsimonizer** [comment]
Thanks for the answer. I'd like to get the results of the tests (output) and send it by email.
I thought I could do that with ut_output_buffer.get_lines.

**Comment by lwasylow** [comment]
Can you not sent email from DB ? Select bullk collect into clob and utl_mail ?

**Comment by jgebal** [comment]
Do you use any automation to run tests like Jenkins CI?
If so you can use utPLSQL-cli to run tests, save results to file and send them
From tools like TAD/SQLDeveloper/PLSQL Developer I would run an SQLPlus script to do the job.

**Comment by ezsimonizer** [comment]
email is not the problem. It's getting the output that is.

**Comment by ezsimonizer** [comment]
We are not using a CI server yet. We use PLSQL Developer. I can build an email and send it without any problem, but I need to get the output of the tests to build the body of my message. 
I thought I could do it with ut_output_buffer.get_lines.

**Comment by lwasylow** [comment]
Possible  run select * from table(ut.run()) bulk collect into table type; and then some custom code to generate a clob from that to attach to email ?

**Comment by ezsimonizer** [comment]
Ah!  select * from table(ut.run()) gives me the output of ut.run !!!!  
I can certainly build on that.
Thanks!
