### ISSUE TITLE
Wrong output when using the %context annotation and SonarQube reporter

### ISSUE THREAD

**Issue by felipebz** [utPLSQL/utPLSQL#749]
Hi!

I just noticed that the number of tests shown in our SonarQube instance is a bit less than the actual number of tests. Looking at the output generated by SonarQube reporter (ut_sonar_test_reporter) I found out that's being generated incorrectly when the test package uses the `%context` annotation.

Example:

**ut_demo.pks**
```
create or replace package ut_demo is

  -- %suite
  
  -- %test
  procedure test1;
  
  -- %context(first_context)
  
  -- %test
  procedure test2;
  
  -- %endcontext

end ut_demo;
```

**ut_demo.pkb**
```
create or replace package body ut_demo is
  procedure test1 is begin null; end;
  procedure test2 is begin null; end;
end ut_demo;
```

Then, run the tests using:

```
begin
  ut.run('ut_demo', ut_sonar_test_reporter());
end;
```

Currently, this is the output:

```
<?xml version="1.0"?>
<testExecutions version="1">
<file path="ut_demo.first context">
<testCase name="test2" duration="1" >
</testCase>
</file>
<file path="ut_demo">
<testCase name="test1" duration="1" >
</testCase>
</file>
</testExecutions>
```

Note that it have two `<file>` tags, one of them has the context name. SonarQube will only import the data inside the `<file path="ut_demo">` (which corresponds to a file on the disk). Since SonarQube requires a filename in the `<file>` tag, the output should be:

```
<?xml version="1.0"?>
<testExecutions version="1">
<file path="ut_demo">
<testCase name="test1" duration="1" >
</testCase>
<testCase name="test2" duration="1" >
</testCase>
</file>
</testExecutions>
```

I'm using utPLSQL 3.1.2.2134.

**Comment by jgebal** [comment]
Thanks for raising this issue for `context` and sonar reporter.

It's definitely a bug that we need to look into.

Even without context, the example you gave will not allow for sonar to import test results.
Sonar accepts exact filename (with path relative to project analysis root).
To use utPLSQL with sonar you need to use [utplsql-cli](https://github.com/utPLSQL/utPLSQL-cli/releases).
Maven plugin is on it's way.
You may see how we use it ourselves to run our unit tests 
- [in our own tests](https://github.com/utPLSQL/utPLSQL/blob/385450200ecfe2546f808539e00bf683e5e3023e/test/install_and_run_tests.sh#L22)
- [in our demo-project](https://github.com/utPLSQL/utPLSQL-demo-project/blob/e45bd261c79e3c15f7c533e726095e6517c0cbe5/test/run.sh#L9)

Sonar analysis is getting published [here](https://sonarcloud.io/dashboard?id=utPLSQL%3AutPLSQL-demo-project)

**Comment by jgebal** [comment]
The sonar test results is meant to be used with source file paths.
Without mapping to project files, sonar will not report on the tests properly anyway.

The issue seems to be that there is more than one XML block per file.
I've just checked our own test results for sonar and I see duplicated blocks for tests that have contexts:
```
    <file path="test\api\test_ut_run.pkb">
        <testCase name="run_proc_no_params" duration="456">
        </testCase>
        <testCase name="run_proc_specific_reporter" duration="42">
        </testCase>
        <testCase name="run_proc_cov_file_list" duration="49">
        </testCase>
        <testCase name="run_proc_pkg_name" duration="0">
            <skipped message="skipped"/>
        </testCase>
        <testCase name="run_proc_pkg_name_file_list" duration="28">
        </testCase>
        <testCase name="run_proc_path_list" duration="47">
        </testCase>
        <testCase name="run_proc_path_list_file_list" duration="40">
        </testCase>
        <testCase name="run_proc_null_reporter" duration="35">
        </testCase>
        <testCase name="run_proc_null_path" duration="35">
        </testCase>
        <testCase name="run_proc_null_path_list" duration="34">
        </testCase>
        <testCase name="run_proc_empty_path_list" duration="40">
        </testCase>
    </file>
    <file path="test\api\test_ut_run.pkb">
        <testCase name="run_func_no_params" duration="101">
        </testCase>
        <testCase name="run_func_specific_reporter" duration="96">
        </testCase>
        <testCase name="run_func_cov_file_list" duration="90">
        </testCase>
        <testCase name="run_func_pkg_name" duration="0">
            <skipped message="skipped"/>
        </testCase>
        <testCase name="run_func_pkg_name_file_list" duration="79">
        </testCase>
        <testCase name="run_func_path_list" duration="72">
        </testCase>
        <testCase name="run_func_path_list_file_list" duration="39">
        </testCase>
        <testCase name="run_func_null_reporter" duration="39">
        </testCase>
        <testCase name="run_func_null_path" duration="46">
        </testCase>
        <testCase name="run_func_null_path_list" duration="35">
        </testCase>
        <testCase name="run_func_empty_path_list" duration="35">
        </testCase>
        <testCase name="run_func_cov_file_lst_null_rep" duration="40">
        </testCase>
        <testCase name="run_func_empty_suite" duration="915">
        </testCase>
        <testCase name="raise_in_invalid_state" duration="1047">
        </testCase>
        <testCase name="run_in_invalid_state" duration="933">
        </testCase>
        <testCase name="run_and_revalidate_specs" duration="1081">
        </testCase>
    </file>
    <file path="test\api\test_ut_run.pkb">
        <testCase name="ut_version" duration="4">
        </testCase>
        <testCase name="ut_fail" duration="17">
        </testCase>
    </file>
```
So there is a bug after all.
When fixing, I will probably remove context-awareness from that reporter.

**Comment by felipebz** [comment]
Oh... Thanks for your analysis, @jgebal. There was a bug on our pipeline too...

Just for the context: we're already using utplsql-cli, but the mapping of test files wasn't quite right and the file paths were being "fixed" editing the XML (yeah, an ugly workaround)... So I fixed our process and now the utplsql-cli is mapping the files correctly. :-)

Even with the duplicated "file" tag, all tests are imported now and everything looks fine on SonarQube. It looks like this issue doesn't cause any real problem after all...

This can be verified looking at the [test_ut_run.pkb file on SonarQube](https://sonarcloud.io/code?id=utPLSQL&selected=utPLSQL%3Atest%2Fapi%2Ftest_ut_run.pkb): it shows 27 unit tests (the package has 29 tests, 2 of them are "skipped").

**Comment by jgebal** [comment]
Oh, interesting.
 Need yo talk to sonar. Looks like they have a bug and show the unit test measure not as total but as count of executed tests (they ignore skipped in count metric).
