### ISSUE TITLE
Test execution stops when annotated procedure has parameters

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#753]
When annotated procedure has parameters, the test execution stops and no more tests are executed.
This scenario literally breaks test execution.

**Comment by Shoelace** [comment]
i wonder if `ut_metadata.procedure_exists()` needs to be enhanced to check for arguments on the test procedure.  (which is actually  checking meth_exists.. it doesnt care procedure vs function)

or alternatively check in `ut_executable.is_invalid()` 

or maybe thats it.. check procedure exists to only look for procedures..  then have a new `ut_metadata` function to return the argument count. then call those in sucession during `ut_executable.is_invalid()` .

**Comment by jgebal** [comment]
Would be good to get this fixed in upcoming release to improve test-run resiliency.

**Comment by jgebal** [comment]
With the current develop version this is no longer a critical issue.
The test procedure is reported as not-found.
The test execution doesn't break, only the failure message is confusing.
```sql
create or replace package dummy_test_package_no10 as
  --%suite
  
  --%test
  procedure test_no1(a integer);
  --%test
  procedure test_no2;
end;
/

create or replace package body dummy_test_package_no10 as
  procedure test_no1(a integer) is
  begin
    ut.expect( 1 ).to_equal( 1 );
  end;
  procedure test_no2 is
  begin
    ut.expect( 1 ).to_equal( 1 );
  end;
end;
/

set serverout on
exec ut.run('dummy_test_package_no10');
```

```
dummy_test_package_no10
  test_no1 [.003 sec] (FAILED - 1)
  test_no2 [.004 sec]
  SUCCESS
    Actual: 1 (number) was expected to equal: 1 (number)
 
Failures:
 
  1) test_no1
      Call params for test are not valid: procedure UT3_DEMO.DUMMY_TEST_PACKAGE_NO10.TEST_NO1 does not exist.
Finished in .00927 seconds
2 tests, 0 failed, 1 errored, 0 disabled, 0 warning(s)
```

**Comment by jgebal** [comment]
I'm closing this issue as it's no longer a bug.
