### ISSUE TITLE
Update JUnit reporter description to reflect official JUnit doc

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#763]
The official JUnit 5 XML format doc is located here:
https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd

We re using an unofficial gist for JUnit4: https://gist.github.com/kuzuha/232902acab1344d6b578 as a reference in description for the reporter and probably when validating the reporter outputs on Travis.

**Comment by jgebal** [comment]
Comparing the two, looks like they are almost the same, except for one, quite important difference.
The format we use (unofficial), has:
```
    <xs:element name="testsuite">
        <xs:complexType>
            <xs:sequence>
...
                <xs:element ref="testsuite" minOccurs="0" maxOccurs="unbounded"/>
...
```
The official format for JUnit5 does not support nesting of testsuite inside testsuite.
I believe, we are currently nesting suites based on our hierarchy.
If we want to move to JUnit5 official format, we need to make the nested suites a flattened list.

**Comment by jgebal** [comment]
As part of thos issue we should also explore the possibility to get rid of suite nesting and impact it has on look&feel of test results report in Jenkins and Teamcity.

**Comment by lwasylow** [comment]
Are we going to keep both v4 and v5 or replace with v5 and if so if V5 is back compatible ?

**Comment by jgebal** [comment]
I would leave it as is. Junit5 format doesn't define suite nesting.

**Comment by lwasylow** [comment]
Agreed unless it's not reporting correctly in Jenkins wouldn't bother to change.

**Comment by jgebal** [comment]
Closing as we want to use nested suites.
Until it works with CI servers - not an issue.
