### ISSUE TITLE
Let pick a charset when generating code coverage html report

### ISSUE THREAD

**Issue by alesana-san** [utPLSQL/utPLSQL#775]
In version 3.1.2 there's a hardcoded value UTF8 for this kind of report. In case if you have some stuff in a different encoding (ex. Windows-1251), then all national symbols become unreadable

**Comment by jgebal** [comment]
@alesana-san 
Can you let me know what is your DB character set?

**Comment by alesana-san** [comment]
@jgebal 
Finally made a report using CLI and everything was OK. CLI put this line:
<meta http-equiv="content-type" content="text/html; charset=WINDOWS-1251" />
So I guess the issue can be closed.

**Comment by jgebal** [comment]
@pesse
Is cli replacing / adding charset to html report automatically? I thought it was to be provided from framework.

**Comment by pesse** [comment]
CLI is providing charset based on Java locale. Framework is not necessarily able to auto-detect the charset needed.

**Comment by jgebal** [comment]
Checked. Client encoding is already passed to HTML coverage report when client application provides encoding.

Will update documentation to mention character-set setting.
