### ISSUE TITLE
Add <, >, <=, >= matchers

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#78]
We need 4 additional matchers:
be_lt / be_less_than / "<"
be_gt / be_greater_than / ">"
be_le / be_less_equal / "<="
be_ge / be_greater_equal / ">="

Those matchers should operate on following data types:
number
date family
interval family

**Comment by Pazus** [comment]
I'd stay with the long variants and changed last two to "be_less_or_equal" to be more readable

**Comment by proldan** [comment]
I'm working on this issue.
