### ISSUE TITLE
Test using an existing table.

### ISSUE THREAD

**Issue by successshrestha** [utPLSQL/utPLSQL#794]
There's a table named summary_table which compares two tables and checks if those two table's columns, constraints and data are same or not. The table has columns like columns_status(checks if the columns of both tables are same or not), data_status(checks if the data in both tables are same or not) and constraints_status(checks if the constraints of both tables are same or not) which shows PASS or FAIL. There are multiple tables(1000+) in the summary_table. How can i test each of them?

This is how the summary_table looks like:

```
TABLE1     TABLE1     COLUMN_STATUS     DATA_STATUS   CONSTRAINTS_STATUS
-----------------------------------------------------------------------------------------     
CUST1      CUST1         PASS         PASS                         PASS
SUPP1      SUPP1         PASS         FAIL                         PASS
```

I tried using ref_cursor to hold the column_status and used loop to check each rows. This way i only got the report for the failed ones. i want report for the passed tests also.

**Comment by jgebal** [comment]
How do you populate that table?
Is there a framework that does the column/data/constraint comparison?
It seems like you don't really want to test anything but only generate a report
Is there avreason why you want to use utPLSQL as a reporting tool?

**Comment by successshrestha** [comment]
There's a package which populates the table. all the comparisons are done in that package. Actually you are right. The testing part has already been done by the package. I want to generate a report.
The organization that i work for has been using utPLSQL and i was told to use it for reporting.

**Comment by jgebal** [comment]
I would replace that package with a test generator, if all that it is doing is performing exactly the same thing for multiple tables.
The generator would create unit test package(or packages) and ececute them.
That way you will get much more robust feedback.
Information that something has failed is valuable but insufficient I think.
It still requires detailed investigation on:
- What is the difference
- Why there is difference

You could use utPLSQL to get detailed info on WHAT is different.

utPLSQL has build-in cursor comparison.
(Hope you are using latest version 3.1.+)

All that is left is to create cursors to compare data between:
- all_tab constraints 
- tables that are compared
- all_tab_columns (maybe it is not needed as utplsql cursor data comparator compares colums too(datatype/position))

utPLSQL is not a reporting tool and was never indended to be one :)

**Comment by successshrestha** [comment]
The package does the job of maintaining the logs as well. And also if i replace the package there will be more than 1000+ test procedures. I did try using the cursor comparison to compare multiple rows for each status columns using loop, but that way those multiple rows that has been compared will only be counted as a single test. Is writing multiple test procedures the only way?

**Comment by pesse** [comment]
What is the problem to have them all in one test?
I myself have multiple expectations per test when it makes sense. You can add a dynamic error message in the second parameter also:

`ut.expect(l_actual, 'This further describes the specific expectation dynamically').to_...`

I use this when I have several checks in a loop (which sounds a lot like your use-case)

**Comment by jgebal** [comment]
You don't need to write individual tests and suites.

You could have a piece of code to generate those.

Example:
```sql
declare
l_spec varchar2(32767);
l_body varchar2(32767);
begin

  for i in (select * from user_tables) loop
    l_spec := 'create or replace package ut_'||i.table_name||' as
        --%suite
        
        --%test
        procedure validate_constraints;
        --%test
        procedure validate_columns_and_data;
      end;';
    l_body := 'create or replace package body ut_'||i.table_name||' as

        procedure validate_constraints is
          l_expected sys_refcursor;
          l_actual   sys_refcursor;
        begin
          open l_expected for 
            select * from all_constraints 
             where table_name = '''||i.table_name||'''
               and table_owner = ''SOURCE'';
          open l_actual for 
            select * from all_constraints 
             where table_name = '''||i.table_name||'''
               and table_owner = '''||USER||''';
          ut.expect(l_actual).to_equal(l_expected);
        end;

        procedure validate_columns_and_data is
          l_expected sys_refcursor;
          l_actual   sys_refcursor;
        begin
          open l_expected for 
            select * from SOURCE.'||i.table_name||';
          open l_actual for 
            select * from '||user||'.'||i.table_name||';
          ut.expect(l_actual).to_equal(l_expected);
        end;
      end;';
      execute immediate l_spec;
      execute immediate l_body;
      
  end loop;
end;
```

This is of course a draft - doesn't work - doesn't do exactly what you need.
It should however give you an idea on how to generate unit tests for comparing 2 table data and their constraints.

Hope this helps.

**Comment by successshrestha** [comment]
@jgebal This did help. Thank you very much.
