### ISSUE TITLE
Is there a housekeeping job for the utPLSQL-tables ?

### ISSUE THREAD

**Issue by ThisGuenter** [utPLSQL/utPLSQL#802]
DBMSPCC_BLOCKS
DBMSPCC_RUNS
DBMSPCC_UNITS
PLSQL_PROFILER_DATA
PLSQL_PROFILER_RUNS
PLSQL_PROFILER_UNITS

**Comment by lwasylow** [comment]
Not at the moment but are are considering moving this into GTT so the housekeeping will not be required.
The deletion can be tricky if there are multi users and as well mutliple reports (html,sonar etc).
