### ISSUE TITLE
ORA-00923: FROM keyword not found where expected

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#810]
I am new to utplsql.  I am using ORACLE 10 G (XE)

I downloaded the source files (all .sql files).

1. I successfully created a schema by running the following command:

cd source
sqlplus sys/sys_password@database as sysdba @create_utPLSQL_owner.sql ut3 ut3 users  
It worked

2. I ran the following command:
cd source
sqlplus admin/admins_password@database @install.sql ut3  

I got the following error:

Connected to:
Oracle Database 10g Express Edition Release 10.2.0.1.0 - Beta

--------------------------------------------------------------
Installing utPLSQL v3 framework into ut3 schema
--------------------------------------------------------------
Switching current schema to ut3
--------------------------------------------------------------
declare
*
ERROR at line 1:
ORA-00923: FROM keyword not found where expected
ORA-06512: at line 23

What could be the mistake?

**Comment by jgebal** [comment]
utPLSQL v3 requires Oracle version 11.2 at minimum.

Your only option is to use utPLSQL v2.3.1

**Comment by gurubbc** [comment]
oh...is it?
Thank you so much for your help

-- Guru

**Comment by gurubbc** [comment]
Now, I installed ORACLE 11.2.0.2.0 (XE).
I am trying to install utplsql...I got the following error:

I:\utPLSQL\utPLSQL\source>sqlplus ut3/ut3@xe @install.sql ut3

SQL*Plus: Release 11.2.0.2.0 Production on Thu Jan 3 22:09:50 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

--------------------------------------------------------------
Installing utPLSQL v3 framework into ut3 schema
--------------------------------------------------------------
Switching current schema to ut3
--------------------------------------------------------------
declare
*
ERROR at line 1:
ORA-20000: The following object grants are missing for user "UT3" to install utPLSQL:
-  DBMS_CRYPTO
-  DBMS_LOCK
Please read the installation documentation at http://utplsql.org/utPLSQL/
ORA-06512: at line 33


Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

I manually granted permission to DBMS_LOCK and DBMS_CRYPTO using sysdba
Still I am getting the above mentioned errors.
Can you please help me?

**Comment by PhilippSalvisberg** [comment]
You should run `sqlplus sys/sys_pass@db as sysdba @install_headless.sql` as described in https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/install.md#headless-installation.

**Comment by gurubbc** [comment]
Thank you very much for your kind help.
Actually, I have SYS in owner column
When I  changed from 'SYSTEM' to 'SYS' (line no 30) in check_object_grants.sql, it worked!!!!!

Thanks anyways.

**Comment by jgebal** [comment]
Hmm... It's not good that you had to change the install scripts. Need to have a look at it

**Comment by jgebal** [comment]
@gurubbc 
I've checked sources in v3.1.2 and v.3.1.3.
https://github.com/utPLSQL/utPLSQL/blob/v3.1.3/source/check_object_grants.sql#L32
It is actually `SYS`, not sure why you had to change it from `SYSTEM` to `SYS`
