### ISSUE TITLE
In which schema, we should run the unit tests?

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#812]
Hi experts,

- I have successfully installed utplsql v3
- I ran the following script
I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba @install.sql ut3
- It installed all the packages successfully then, I got the SQL prompt
- Now, I wanted to try some basic package test
- So, I defined and executed the following package

create or replace package test_betwnstr as
  --%suite(Between string function)
end;
/
- I executed this test by invoking the following command:
begin ut.run(); end;
- It gave me the following output:
Between string function
 
Finished in .451423 seconds
0 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)

----------- This is perfect as per the documentation -------------
Now, the actual scenario:

1. I have created schema "ut3" and installed the utplsql in this schema "ut3"
2. So, I should be able to test my plsql code from this schema "ut3", right?
3. With this assumption, I logged in using ut3
I:\utPLSQL\utPLSQL\source> sqlplus ut3/ut3@xe

SQL> create or replace package test_betwnstr as
  2
  3    --%suite(Between string function)
  4
  5  end;
  6  /

Package created.

Now, I wanted to execute this and test:
SQL> begin ut.run(); end;
  2  /

PL/SQL procedure successfully completed.

?????? Why I am getting the output as above ?????
I should have got the output as follows:
Between string function
 
Finished in .451423 seconds
0 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)

Am I missing something here, any configuration, setting is missing?

Questions:

1. I should run the unit testing code inside ut3 user, right?
2. I should get the test result instead of "PL/SQL procedure successfully completed."

Please help me.

**Comment by lwasylow** [comment]
Can you paste full example pls step by step? Did you define a annotation - - %test? Hard to replicate issue from above.
Thanks

**Comment by gurubbc** [comment]
Step 1: create schema for installing utplsql
============================================
I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba
@create_utPLSQL_owner.sql ut3 ut3 users

I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba
@create_utPLSQL_owner.sql ut3 ut3 users

SQL*Plus: Release 11.2.0.2.0 Production on Fri Jan 4 12:25:28 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

Creating utPLSQL user ut3
Done
SQL>

Step 2: Install UTPLSQL:
========================

I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba
@install.sql ut3
...
...
...
--------------------------------------------------------------
Installing component HAVE_COUNT
No errors.
--------------------------------------------------------------
Installing component MATCH
No errors.
--------------------------------------------------------------
Validating installation
--------------------------------------------------------------
--------------------------------------------------------------
Installation completed successfully
--------------------------------------------------------------
SQL>

Step 3: Create package, compile and test (here, I am not changing the
user), I am continuing from the previous step
========================================================================================================================
SQL> create or replace package test_betwnstr as
  2
  3    --%suite(Between string function)
  4
  5  end;
  6  /
SQL> begin ut.run(); end;
  2  /
Between string function

Finished in .004 seconds
0 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)

SQL>

Now if I connect using ut3 user, see the output below:

I:\utPLSQL\utPLSQL\source>sqlplus ut3/ut3@xe
(ut3 is the username where the utplsql is installed using "system" user as
dba)

SQL*Plus: Release 11.2.0.2.0 Production on Fri Jan 4 12:34:06 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>
SQL> create or replace package test_betwnstr as
  2
  3    --%suite(Between string function)
  4
  5  end;
  6  /

Package created.

SQL> begin ut.run(); end;
  2  /

PL/SQL procedure successfully completed.

SQL>

Why I am getting output like this?  I should get the test results, right?
This is my question.

**Comment by gurubbc** [comment]
Step 1: create schema for installing utplsql
============================================
I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba @create_utPLSQL_owner.sql ut3 ut3 users

I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba @create_utPLSQL_owner.sql ut3 ut3 users

SQL*Plus: Release 11.2.0.2.0 Production on Fri Jan 4 12:25:28 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

Creating utPLSQL user ut3
Done
SQL>

Step 2: Install UTPLSQL:
========================

I:\utPLSQL\utPLSQL\source>sqlplus system/Password123@xe as sysdba @install.sql ut3
...
...
...
--------------------------------------------------------------
Installing component HAVE_COUNT
No errors.
--------------------------------------------------------------
Installing component MATCH
No errors.
--------------------------------------------------------------
Validating installation
--------------------------------------------------------------
--------------------------------------------------------------
Installation completed successfully
--------------------------------------------------------------
SQL>

Step 3: Create package, compile and test (here, I am not changing the user), I am continuing from the previous step
========================================================================================================================
SQL> create or replace package test_betwnstr as
  2
  3    --%suite(Between string function)
  4
  5  end;
  6  /
SQL> begin ut.run(); end;
  2  /
Between string function

Finished in .004 seconds
0 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)

SQL>

Now if I connect using ut3 user, see the output below:

I:\utPLSQL\utPLSQL\source>sqlplus ut3/ut3@xe
(ut3 is the username where the utplsql is installed using "system" user as dba)

SQL*Plus: Release 11.2.0.2.0 Production on Fri Jan 4 12:34:06 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>
SQL> create or replace package test_betwnstr as
  2
  3    --%suite(Between string function)
  4
  5  end;
  6  /

Package created.

SQL> begin ut.run(); end;
  2  /

PL/SQL procedure successfully completed.

SQL>

Why I am getting output like this?  I should get the test results, right?  This is my question.

**Comment by PhilippSalvisberg** [comment]
@gurubbc utPLSQL reports the result via serveroutput. Server output was enabled during the installation. Hence your test in the session after the installation as user `system` showed the output. 

Connect as the user owning the tests. And run the following:

```
set serveroutput on size unlimited
```

Then you may run the test as you have done with 

```
begin
  ut.run();
end;
/
```

and you get the test results via serveroutput.

**Comment by gurubbc** [comment]
Thank you so much,
After my mail I guessed I was missing something, but this serveroutput
didn't strike to me.
Thanks a lot.
------------------------------------------------------------------------------------------------------
Gurumurthy Ramamurthy
