### ISSUE TITLE
Add support for asserts on dbms_output

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#82]

**Comment by Shoelace** [comment]
[check_dbms_output.txt](https://github.com/utPLSQL/utPLSQL/files/666654/check_dbms_output.txt)
here is a simply script that retreives the content of dbms_output for comparison .

asserts that should probably be supported are 'equals' and 'like'.  i'd suggest 'linecount' also but not sure how well that fits in.

**Comment by Shoelace** [comment]
at the moment the most basic idea for how this would work would be something like
```sql
ut.start_dbms_output;
do_stuff();
ut.end_dbms_oupput;
ut_assert.are_equal('output matches expected', ut.get_captured_output(), 'expected ouptut of do_stuff();');
```

and the expect format to be like
```sql
ut.mark_dbms_output_start;
do_stuff();
--ut.mark_dbms_output_end; --optional
ut.expect('expected output of do_stuff','description of dbms_output test').to_equal_output();
```

**Comment by jgebal** [comment]
I'd suggest not to implement this. V2 contained such asserts, but they are not generic.
The assert on dbms_output is function-specific. Users can still implement tests on dbms_output if needed without dedicated expectation in v3.
If we go and implement `dbms_output` expectation we might as well implement for AQ/ PIPE/ UTL_HTTP and so on and so on.

I'd abandon this concept.
