### ISSUE TITLE
Add clear statemen on version check

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#822]
Mare sure that it's clearly documented on how to check version of utPLSQL

**Comment by Shoelace** [comment]
it could be potential  be included  as part of a verbose dbms_output reporter output.

- version
- cache update time
- basic db details (dbname , ut schema, current user, etc..)

**Comment by lwasylow** [comment]
Isn't it included in debug reporter now @jgebal? I thin run_info have this details?

**Comment by jgebal** [comment]
It is, but it's probably also worth mentioning explicitly in documentation.
I'm not sure if its mentioned and if it is in the right place.
