### ISSUE TITLE
ORA-20204: Suite package UT3.ut3_guru does not exist

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#823]
Hi all,

I am using UTPLSQL 3.0
When I am trying to create package with suite and test, it gets compiled successfully, but during run, it gives me the error.

  1  create or replace package ut3_guru
  2  as
  3      -- %suite(My Suite)
  4      -- %test(My Test)
  5      procedure test_one;
  6* end ut3_guru;
  7  /

Package created.

SQL> begin
  2  ut.run('ut3_guru');
  3  end;
  4  /
ORA-06512: at "UT3.UT_SUITE_MANAGER", line 665
ORA-06512: at "UT3.UT_RUNNER",
line 144

ORA-20204: Suite package UT3.ut3_guru does not exist

begin
*
ERROR at line 1:
ORA-20204: Suite package UT3.ut3_guru does not exist
ORA-06512: at "UT3.UT_RUNNER", line 157
ORA-06512: at "UT3.UT", line 126
ORA-06512: at "UT3.UT", line 427
ORA-06512: at "UT3.UT", line 538
ORA-06512: at line 2

SQL>

**Comment by PhilippSalvisberg** [comment]
Package level annotations need to be separated from procedure level annotations by at least one empty line. For example

```
create or replace package ut3_guru 
as
  -- %suite(My Suite)

  -- %test(My Test)
  procedure test_one;
end ut3_guru;
/
```

Then it should work. 

Furthermore we recommend not to store tests in the `UT3` schema to simplify future upgrades.

**Comment by gurubbc** [comment]
Thanks Phillip.

I understood.

It worked after leaving a blank line between suite and test
