### ISSUE TITLE
How to display utplsql version from SQL prompt?

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#824]
Hi,

We can use the following command to find out DB version
SQL> select * from v$version;

BANNER
--------------------------------------------------------------------------------
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
PL/SQL Release 11.2.0.2.0 - Production
CORE    11.2.0.2.0      Production
TNS for 64-bit Windows: Version 11.2.0.2.0 - Production
NLSRTL Version 11.2.0.2.0 - Production

Similarly, is there a command to find out utplsql version from SQL prompt?

**Comment by pesse** [comment]
`select ut.version() from dual`

**Comment by gurubbc** [comment]
Thanks a ton.

**Comment by pesse** [comment]
You're welcome. Sorry for brevity, was only on smartphone (and I hate typing on it :D)
