### ISSUE TITLE
Thumbs up!

### ISSUE THREAD

**Issue by KavliJalapeno** [utPLSQL/utPLSQL#825]
I have been looking for a test framework for Oracle for a while, it is not much out there. I have tried unit testing with SQLDeveloper and TOAD, but they simply dont't live up to our expectations. I have used utPLSQL for a couple of weeks now, and I just want to say that it saved my day. Not only it helped me write error free code, but also with design issues. Since I also have experience from the Java world, it suits me well. utPLSQL should have been native Oracle functionality.

Thank you! Keep up the good work!

**Comment by pesse** [comment]
Thank you so much @KavliJalapeno for the nice feedback!
Since this is a leisure-time only project, feedback like yours is one of the most important sources of motivation :)
