### ISSUE TITLE
why invalid annotation?

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#826]
create or replace package test_package as
      --%suite(Tests for a package)
	  --context(Check numbers)
	  
		--%test(Tests odd)
			  procedure checkOdd;
	        --%test(Tests even)
			  procedure checkEven;
			  
		--%endcontext
    end;
	/
	
create or replace package body test_package as
procedure checkOdd is
begin
	dbms_output.put_line('checking odd');
end;

procedure checkEven is
begin
    dbms_output.put_line('checking even');
end;
end;
/
package and package body are successfully created, but:

SQL> execute ut.run('test_package');
Tests for a package
Tests odd [.004 sec]
checking odd
Tests even [.003 sec]
checking even
Warnings:
1) test_package
Invalid annotation "--%endcontext". Cannot find preceding "--%context"
Annotation ignored.
at "UT3.TEST_PACKAGE", line 10
Finished in .011 seconds
2 tests, 0 failed, 0 errored, 0 disabled, 1 warning(s)

PL/SQL procedure successfully completed.

**Comment by jgebal** [comment]
Because there is no preceding `--%context` annotation.
Keep in ming that when you fix the  `--context` you need to separate pakage level annotations from procedure lwvel annotations.
A blank line between package and procedure annotations will do the trick.

**Comment by gurubbc** [comment]
Yes, I had two mistakes:

1.  I didn't have %--context, I had given --context
2. I didn't have blank line as you said

After I gave as below, this issue got fixed
Thanks a lot.

create or replace package test_package as
--%suite(Tests for a package)

--%context(Check numbers)

	--%test(Tests odd)
		  procedure checkOdd;
        --%test(Tests even)
		  procedure checkEven;
		  
	--%endcontext
end;
/
