### ISSUE TITLE
Randomly occuring error during comparing two cursors

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#827]
When running a test with comparing two cursors from time to time error occurs.
```sql
ORA-06553: PLS-306: wrong number or types of arguments in call to 'COMPARE'

ORA-06512: at "UT3.UT_COMPOUND_DATA_VALUE", line 172

ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 253

ORA-06512: at "UT3.UT_EQUAL", line 236

ORA-06512: at "UT3.UT_EXPECTATION", line 24

ORA-06512: at "UT3.UT_EXPECTATION", line 136

ORA-06512: at "SPD.UT_SPI_ENGINE_TRA", line 239

ORA-06512: at line 6
```

**Comment by lwasylow** [comment]
Its still showing randomly which is annoying. I think worth to put some braces around these lines to make sure that there is no empty nulls passing so we can handle this gracefully.

**Comment by jgebal** [comment]
Interesting why we would get nulls passed to COMPARE. As you say. This should never happer.
We will need better trapping and logging to be able to investigate it.
We can add some safety checks to prevent this error but this will not fix the problem I guess.

**Comment by lwasylow** [comment]
I think where possible we should not let to the situation where the system error occurs by invoking a sys code with invalid argument. I know it might be impossible task but if we limit at least these scenarios where we know about will be easier for user to understand error. This one above for example is very cryptic and doesn't tell you what happened there.

**Comment by lwasylow** [comment]
This is new code version can occurs only in SQL when comparing two columns extract from XML.
It happened here : https://travis-ci.org/utPLSQL/utPLSQL/jobs/503511721#L5982
We could try run nvl on that ```nvl(s.column_value.getclobval(),empty_clob())``` to make sure is always initialised
