### ISSUE TITLE
package doesn't exist

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#829]
Hi, 

the below code was working fine, but it now says "package doesn't exist".  Don't understand why?
SQL> create or replace package pkg1 as
  2  --% suite(suite8)
  3
  4  --% test(test8)
  5  procedure proc8;
  6  end;
  7  /

Package created.

SQL> create or replace package body pkg1 as
  2  procedure proc8 is
  3  begin
  4  ut.expect('guru').to_equal('guru');
  5  end;
  6  end;
  7  /

Package body created.

SQL> execute ut.run('pkg1');
BEGIN ut.run('pkg1'); END;

*
ERROR at line 1:
ORA-20204: Suite package UT3.pkg1 does not exist
ORA-06512: at "UT3.UT_RUNNER", line 157
ORA-06512: at "UT3.UT", line 126
ORA-06512: at "UT3.UT", line 427
ORA-06512: at "UT3.UT", line 538
ORA-06512: at line 1

SQL>

**Comment by jgebal** [comment]
In what schema was the package created?

**Comment by gurubbc** [comment]
ut3
I guess, there should not be space between % and suitename and testname

wrong: --% suite(suite8)
correct: --%suite(suite8)

wrong: --% test(test8)
correct: --%test(test8)

**Comment by jgebal** [comment]
That should be *explicitly* stated in documentation but isn't ;)
