### ISSUE TITLE
Add support for asserts on dbms_pipe

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#83]

**Comment by jgebal** [comment]
I'm not sure if assers is the right place to check dbms_pipe directly.
If we go that way, we might start building asserts for every thing there is in Oracle.
Asserts need to be generic not feature specific.
I believe it should be pretty easy to write test on dbms_pipe using existing asserts.

**Comment by Pazus** [comment]
Agree

**Comment by jgebal** [comment]
I'd suggest not to implement this. V2 contained such asserts, but they are not generic.
The assert on dbms_pipe is function-specific. Users can still implement tests on dbms_pipe if needed without dedicated expectation in v3.

I'd abandon this concept.
