### ISSUE TITLE
How to Use Non-Default Prefix (using other prefix than ut_) utplsql 3.1

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#831]
Generally, we use the prefix "ut" to run a test package
such as
execute ut.run('guru1');

How to change this default prefix to something else such as?
execute mytest.run('guru');

**Comment by lwasylow** [comment]
That's a part of framework. You can create your own synonyms but it's not recommended.

**Comment by jgebal** [comment]
You can name the tests however you want.
Why do you want to rename the framework?

**Comment by gurubbc** [comment]
Just to learn!!!

**Comment by pesse** [comment]
Hi @gurubbc 
we appreciate your willingness to learn and explore. However, your request hits a limit in what level of guidance we are willing and able to give. UtPLSQL is developed and maintained in our free time and we are wholeheartedly giving that time and enjoy helping new users without resent, but if we recommend a certain way of using the framework (such as using the `ut` synonym) and you decide to go explore other ways, that's a journey we won't go with you.
All of the source code is available and we encourage you to dive in and have fun, learn things and explore. But our support will stay with the recommended ways.

**Comment by gurubbc** [comment]
I understand, no worries.
Sorry for any trouble.
thanks for your great support.
