### ISSUE TITLE
Unit test with coverage

### ISSUE THREAD

**Issue by gurubbc** [utPLSQL/utPLSQL#832]
I have given the following command:

begin
  ut.run(ut_coverage_html_reporter());
end;
/

It produced the output in html format in the console.
But, how to see the generated .html file and open in the browser?

Could anybody help me?

**Comment by pesse** [comment]
Hi @gurubbc 
as much as we appreciate engagement from utPLSQL users, we expect them to use the existing documentation first, otherwise we will feel resentful to have given our time.
The usage of code coverage reporter is fully documented here:
http://utplsql.org/utPLSQL/latest/userguide/coverage.html

**Comment by jgebal** [comment]
Hi @gurubbc

We appreciate your question.
The question is however unrelated to the framework itself but relates to a more generic problem of:
*saving output from sql / plsql into a file* from within the tool that you are using.

I'm convinced it has been already asked and answered on different forums and sites.

I would encourage to perform research among existing answers, that is a really good way of learning. I practice it myself.

Raising an Issue on an open-source framework on the other hand is not the best way to look for help on a generic question that doesn't relate to the framework itself.

https://www.google.com/search?q=oracle+save+dbms+output+into+file

**Comment by jgebal** [comment]
@gurubbc
We're more than happy to help with framework issues.
I'm closing this one as it is not framework related.
