### ISSUE TITLE
Why the Installation needs access to DBMS_LOCK and DBMS_CRYPTO

### ISSUE THREAD

**Issue by pkrischaitu** [utPLSQL/utPLSQL#833]
I am a developer and my DBA is asking why the installation needs access to DBMS_LOCK and DBMS_CRYPTO. Can you please detail how it uses it?

**Comment by jgebal** [comment]
dbma_lock is needed for access to SLEEP procedure.
DBMS_CRYPTO for calculating hash of any data-set/data-type.
We can't use DBMS_UTILITY.GET_HASH_VALUE as it doesn't accept LOB.

**Comment by pkrischaitu** [comment]
Thank a lot!
