### ISSUE TITLE
On binary XML storage insignificant whitespaces are removed.

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#880]
On binary XML storage insignificant whitespaces are removed.
This is default way of storing XML data post 12.1 release and causing trimming of whitespaces.
Using CLOBS is inefficient.
e.g
`select * from table(ut_varchar2_list(' '))`

`select * from table(ut_varchar2_list(''))` 

are showing as equal.

**Comment by jgebal** [comment]
Documentation note on this can be found here:
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adxdb/choice-of-XMLType-storage-and-indexing.html#GUID-320807FC-DB58-4600-8F92-A1247A354AE5

**Comment by jgebal** [comment]
Raised it with ASKTom, as documentation is not mentioning data-infidelity.
I would expect XMLType to give full data-fidelity.

It smells like an Oracle bug. Not much we can do about it.
CLOB storage is absolutely not an option due to performance issues.

**Comment by jgebal** [comment]
LiveSQL demo of issue:
https://livesql.oracle.com/apex/livesql/s/h5zgtdvybyr9pbyazs8na56sb

**Comment by jgebal** [comment]
Aswer from ASKTom
https://asktom.oracle.com/pls/apex/asktom.search?tag=infidelity-when-storing-xmltype-data-elements-spaces

**Comment by lwasylow** [comment]
Follow up question on XMLTABLE reading these data.
https://livesql.oracle.com/apex/livesql/s/h6ahy0vlhykp7k7xu0ua0xmw4

**Comment by lwasylow** [comment]
Some of the changes been implemented in PR#895
There are still issues regarding whitespace vs double whitespace.

**Comment by jgebal** [comment]
@lwasylow  - what should we do about this issue?

**Comment by lwasylow** [comment]
I think we close it for now. Only problem is a whitespace vs double space. Not much we can do and no one raised as an issue.

**Comment by jgebal** [comment]
We should probably mention it in documentation.
It only applies to cursor/object/nested-table comparison - right?

**Comment by lwasylow** [comment]
Yes it's only when we use xml as part of cursor comparison. Once we stop 11. 2 we could switch to json maybe.

**Comment by jgebal** [comment]
One more Idea that comes to my mind is to use `ANYDATA.convertObject()` and store XMTYPE as ANYDATA. This again will be n overhead but I wonder which one is worse to-CLOB or to-ANYDATA conversion.
