### ISSUE TITLE
ORA-01031 Error when installing utPLSQL on Oracle Autonomous Data Warehouse

### ISSUE THREAD

**Issue by ranched** [utPLSQL/utPLSQL#894]
**Describe the bug**

Installing utPLSQL on Oracle Cloud ADW (Autonomous Data Warehouse) fails at "Installing component UT_COMPOUND_DATA_TMP" with error ORA-01031 insufficient privileges. 

**Provide version info**
utPLSQL: v3.1.6
Database version: Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 (Oracle Autonomous Data Warehouse)

**Information about client software**
SQLDeveloper 18.3.0.277

**To Reproduce**
1. Download and install Oracle SQLDeveloper
2. Download utPLSQL version 3.1.6
3. Connect to Oracle Cloud Autonomous Data Warehouse instance from SQLDeveloper
4. Run the installer with parameters from SQLDeveloper:
`@/home/dev/utPLSQL/source/install_headless.sql UT3 [password] data`
5. Installer stops at `Installing component UT_COMPOUND_DATA_TMP` with error `ORA-01031`

**Expected behavior**
Expected utPLSQL to have installed without error (error is for insufficient privileges ORA-01031)

**Example code**
Install script log with error attached.

**Additional context**
I am connected as the admin but ADW has some administration limitations and I'm wondering if these are interfering.
Here is a [link](https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/experienced-database-users.html#GUID-791E7112-07F7-46F0-BD81-777C8FAD83A0) to the SQL command limitations on ADW.

[utPLSQL_installer_error.log](https://github.com/utPLSQL/utPLSQL/files/3035616/utPLSQL_installer_error.log)

**Comment by jgebal** [comment]
Looks like it is the limitation on ADW. You cannot have tables that store XMLType data.
This is a limitation described in documentation.
There isn't much we can do today to sort this out as we rely on this structure to enable cursor data comparison.

You could ask Oracle on plans to remove that restriction.

@lwasylow - looks like we have another problem to think of.

**Comment by ranched** [comment]
I though that might be the case, thanks for the verification.

**Comment by lwasylow** [comment]
It's a interesting case. I would like to keep that open as next iteration of utPlsql should keep that in mind. Is that same limitation for json?

**Comment by PhilippSalvisberg** [comment]
@jgebal using a clob column and converting it to a transient xmltype could be an option.

**Comment by jgebal** [comment]
Yes. But it makes it ~5 times slower on cursor compare.
I see this as a workaround but not sure if it's the ultimate solution.

**Comment by lwasylow** [comment]
Or table type with same structure, memory for performance I guess.

**Comment by lwasylow** [comment]
Or work in memory on table type and hope it wont blow up on too much data.

**Comment by lwasylow** [comment]
Or insert as CLOB but create a view on top of table that cast to XML ? Not tested performance.

**Comment by PhilippSalvisberg** [comment]
A view converting the CLOB column to XMLTYPE would work. It's a nice solution because you could the PL/SQL Code as is. However, you'd need an instead-of trigger to convert XMLTYPE to CLOB for inserts. So there will be probably more overall conversions done than necessary.

**Comment by lwasylow** [comment]
Well inserts are done as part of ref cursor extract getclobval so that's one option, other as you said a trigger.

**Comment by jgebal** [comment]
That could actually be neat workaround.
We could add exception handling on create table with XMLTYPE and introduce CLOB table wirh view and `instead of` trigger.
Will be slow but only on installs that dont support XMLTYPE.

**Comment by jgebal** [comment]
Here is what I suggest as a solution.

Modify the script that creates `UT_COMPOUND_DATA_TMP` so that if it fails it creates:
- a table `UT_COMPOUND_DATA_TMP$` with CLOB column 
- a view `UT_COMPOUND_DATA_TMP` that exposes CLOB column as XMLTYPE,
- an instead of trigger that takes care of converting XMLTYPE into CLOB

We should perform some basic comparison tests to know what is the expected performance hit on this solution.

The performance hit should be mentioned in somewhere in the installation documentation.

@ranched - would that solution work for you?

**Comment by PhilippSalvisberg** [comment]
AFAIK, future versions of ADW will support XMLType.

**Comment by ranched** [comment]
@jgebal I was able to get the install working with a solution that @lwasylow provided after a discussion in the slack channel. I normally don't work on PLSQ. When I filed this issue I was creating a devops demo showcasing Oracle's Autonomous Data Warehouse and cloud Developer platform and wanted to give utPLSQL a cameo in the demo as the testing tool. Here's a link if anyone is curious, [DevOps Around Autonomous Data Warehouse](https://youtu.be/AcWaYWAgOeQ) Anyways, I got it working for my purposes! Thanks for the follow up!

**Comment by jgebal** [comment]
I suggest to apply the workaround in utPLSQL so that it works on existing autonomous DW.
If we do it right, it will have zero impact on existing code.

**Comment by jgebal** [comment]
@ranched , @PhilippSalvisberg - do you know if XMLType tables are still an issue on ADW?
I wonder if we should implement this or just close the issue?

**Comment by PhilippSalvisberg** [comment]
@jgebal No, you use XMLTYPE in ADW. I've just checked. Works.

**Comment by jgebal** [comment]
Closing, since XMLTYPE tables are now supported in ADW.
