### ISSUE TITLE
How to do discussions?

### ISSUE THREAD

**Issue by PaulWalkerUK** [utPLSQL/utPLSQL#9]
On Sourceforge, we had two discussion forums:
- [utPLSQL Development](https://sourceforge.net/p/utplsql/discussion/utplsql-dev/)
- [General Discussion](https://sourceforge.net/p/utplsql/discussion/general/)

GitHub doesn't do forums. What do we do instead?
### GitHub Issues

I think Issues might work OK, but they could be mixed up with other types of issues. Labels should help with this (i.e. [Filter on the discussion label](https://github.com/utPLSQL/utPLSQL/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion)) . I'm also experimenting with [waffle.io](https://waffle.io/utPLSQL/utPLSQL) to help visualise Issues - discussions would probably work best in their own column. I like the idea that it's part of GitHub - no separate site, no separate logins, everything links and cross-references really well, etc. It's actually pretty close to being a forum, once you've done the initial filtering on a label. I want to carry on with this at least in the interim unless/until we find something better
### Slack

I've just had a quick look at Slack. I've never used it and know next to nothing about it, but it seems to be a popular tool. The main issue I've seen so far is that while the conversations can be public, people have to be invited before they can contribute. This doesn't necessarily rule it out (new people can always ask to be added), but it's not great.
### Gitter

[Gitter](https://gitter.im/) looks to integrate very nicely with GitHub. The conversation seems more like a chat room rather than threaded converations, but I think we could setup different rooms to talk about the main different subjects.
### Google+ Communities

In commit e798cf8 @rlove suggested that other projects have used Google+ Communities.

What does anyone think?

**Comment by Shoelace** [comment]
I dont see any particular need to use anything other then github issues..

slack/gitter are just chat room style things..  i beleive you can create 'rooms' for each discussion.. but I think that would get unwieldy.  
but as you said i think the only thing thats missing is the 'threaded' part as in being able to reply directly to previous comments.
and gitter apparently does not keep a lot of history.


other options
https://www.discourse.org/  (but requires hosting)

http://ost.io/ also looks promising (test forum http://ost.io/@Shoelace/SL_utilities/topics/1 ) but it doesnt appear to do threading either..


which brings you back to.. how important is a threaded discussion. maybe a straight chronological list is better..? and just use the discussion label as you are..

**Comment by jgebal** [comment]
Slack could be good for active developers. It's more instant.
Within issues don't really fit into generic or off topic discussions.

**Comment by jgebal** [comment]
Can we close this discussion?
