### ISSUE TITLE
Documentation: update install/usage section

### ISSUE THREAD

**Issue by Shoelace** [utPLSQL/utPLSQL#90]
the readme in eth v3 banch is missing the "how to install" and " how to use" sections.

the master branch readme https://github.com/utPLSQL/utPLSQL/blob/master/README.md
has about 2 lines on each..

shoudl possibel also add trouble shooting..

maybe just add a link to the embedded documentation..

https://utplsql.github.io/utPLSQL/version3/latest/files/docsource/topics/install-txt.html

**Comment by jgebal** [comment]
@Shoelace,
Can you review the current state of readme and, if possible, update the missing pieces or at least provide feedback on current state?

**Comment by jgebal** [comment]
It would be good if someone could take up the task of reviewing the generation of documentation and fix/update release process to automatically generate the documentation for the project.

**Comment by jgebal** [comment]
Install guide is now referenced in readme.
