### ISSUE TITLE
Default password not complex enough on 18.4

### ISSUE THREAD

**Issue by nicetheory** [utPLSQL/utPLSQL#900]
**Describe the bug**
Pulled v 3.1.6 of utPLSQL to install on new 18.4 database in cloud.
Running standard install_headless.sql gives the following error:
ORA-28003: password verification for the specified password failed
ORA-20000: password must contain 2 or more special characters

**Provide version info**
utPLSQL version 3.1.6
Oracle Database 18c Standard Edition 2 Release 18.0.0.0.0

Solution: Changed default password in install file to "XNtxj8eEgA#$6b6f" (replaced two characters with special characters) and reran install.

(I'm just accepting the default password, because I lock the account afterwards with
alter user ut3 no authentication;)

**Comment by PhilippSalvisberg** [comment]
Thank you @nicetheory for reporting this issue. 

As [documented](http://utplsql.org/utPLSQL/v3.1.6/userguide/install.html) you may pass `username`, `password` and `tablespace` as parameters to `install_headless.sql`. Hence it is not necessary to change the files for the installation.

However, I agree that the default password should match the default Oracle password validation rules.

Nonetheless it is virtually impossible to ensure that this error does not occur when a custom password verification function is used. In such cases a password matching the requirements have to be passed as parameter.

What do you expect us to change?

**Comment by nicetheory** [comment]
Hello, Philipp!

I'm aware that i can give those parameters, but just thought that it might be even more easy if the default password submitted passed the password complexity-check. I've checked with my colleague and we haven't changed the passord-complexity-settings, but it might be a possibility that Oracle Cloud has changed defaults.
My solution was to change line 33 in install_headless.sql from
coalesce('&&2','XNtxj8eEgA**6X**6b6f') ut3_password,
to:
coalesce('&&2','XNtxj8eEgA**#$**6b6f') ut3_password,

Installation went like a breeze after that, whereafter I locked the account. :-)

**Comment by PhilippSalvisberg** [comment]
Thanks Vidar for the update. 

Could you please send us the result of the following query?

```
select p.profile, p.resource_name, p.limit 
  from dba_profiles p
 where p.resource_name = 'PASSWORD_VERIFY_FUNCTION'
   and p.profile = (
           select u.profile 
             from dba_users u
            where u.username = 'UT3'
       );
```
This would help us to see what verification function was used in your case. 

Thanks a lot.

**Comment by nicetheory** [comment]
DEFAULT	PASSWORD_VERIFY_FUNCTION	ORA12C_STRONG_VERIFY_FUNCTION

Jepp - someone seems to have set it a bit higher... (wasn't me)

**Comment by PhilippSalvisberg** [comment]
Thanks. This helps!

**Comment by PhilippSalvisberg** [comment]
We should ensure that all passwords used are compatible to the following verification functions:

- `ORA12C_STIG_VERIFY_FUNCTION`
- `ORA12C_STRONG_VERIFY_FUNCTION`
- `ORA12C_VERIFY_FUNCTION`
- `VERIFY_FUNCTION`
- `VERIFY_FUNCTION_11G`

We could simply check that by calling these functions directly. The list might change for every Oracle Database release. The list above is based on the following query:

```
select object_name from dba_objects 
 where owner = 'SYS'
   and object_type = 'FUNCTION'
   and object_name like '%VERIFY%';
```

We could implement that as utPLSQL tests. However they need to be version specific, since not all of these functions are available in Oracle Database version 11.2.

**Comment by nicetheory** [comment]
That would be a very thorough and functionally good solution. It would expose if the verification functions have changed requirements from version to version, but not if new verification functions emerge.
Me - I would just have changed the password(s), but of course - there's no challenge in that. ;-)

**Comment by lwasylow** [comment]
I think a manage of the list between versions and db customization would create some overhead, effort vs just providing a parameter might be not worth it. Would personally suggest to change the password to strongest possible unless of course there are some backwards compatibility issues.

**Comment by PhilippSalvisberg** [comment]
Thanks Vidar. You just gave me another idea. We could query for the installed verification functions and test all of them. This would simplify the test itself, since no version specific stuff is necessary and it would address the issue that new versions may come with additional verification functions. 

Of course the naïve query above needs some improvement to avoid false positives.

**Comment by lwasylow** [comment]
@phsalvisberg that sounds like a more viable solution requiring much less maintenance.

**Comment by PhilippSalvisberg** [comment]
@lwasylow another challenge ist to avoid hardcoding (duplicating) the password in the test case itself...

**Comment by jgebal** [comment]
Is it really worth the effort?
Most DBA's wouldn't want to use default password when installing.
For non-enterprise use-cases, we could make the default pass strong enough to make it comply with default "strong" pass rule  (as suggested by @nicetheory ).

**Comment by lwasylow** [comment]
It's not worth. 
I think just make it comply.

**Comment by PhilippSalvisberg** [comment]
I agree. After reading this again, I thought that changing the default password might have negative side effects. Users that have installed utPLSQL in their local database with default settings will have to change their stored passwords (e.g. in the IDE) as well. Hence keeping the current password, is a viable option.

A database may have configured custom password verification functions. In such cases it cannot be the expectation that the installation works without passing a password to the installation procedure. I'm really tempted to close this issue without action.

**Comment by mathewbutler** [comment]
Could we instead parameterise the password, forcing a user to supply at install time. For internal deploys we would supply password in the environment.

**Comment by lwasylow** [comment]
It is parameter but optional. So its up to user to choose password if required different than default

**Comment by nicetheory** [comment]
As stated in original post, I only use the password during installation. The account is subsequently locked. That’s how I like it.
This is no big issue for me. Was just a tip, since it may seem that some cloud environments require higher password complexity.

**Comment by PhilippSalvisberg** [comment]
The password can be passed as parameter. When no password is passed the default is used. If the password does not match the password policy (which may be very different for every target installation) an error is thrown during the installation. The solution is to repeat the installation with a complying password. 

As stated earlier, changing the current procedure is not worth the effort. Hence, I'm closing this issue
