### ISSUE TITLE
If the function/procedure being tested has a commit statement, does any annotation allow to ignore this commit while executing tests?

### ISSUE THREAD

**Issue by vasu5235** [utPLSQL/utPLSQL#905]
**Is your feature request related to a problem? Please describe.**
Consider the table `'my_table' `consisting of one column allowing integers.

Modifying the **BETWNSTR** function as:
```
create or replace function betwnstr( a_string varchar2, a_start_pos integer, a_end_pos integer ) return varchar2 
is
begin
  insert into MY_TABLE values (78);
  commit;
  SYS.DBMS_OUTPUT.PUT_LINE('Insert completed');
  if a_start_pos = 0 then
    return substr( a_string, a_start_pos, a_end_pos - a_start_pos );
  else
    return substr( a_string, a_start_pos, a_end_pos - a_start_pos + 1);
  end if;
end;
```
**Describe the solution you'd like**
I propose that an annotation should exists that allows executing unit tests on the above function but ignoring the `commit `statement altogether i.e. after running the 2 unit tests as described below, executing `SELECT * FROM my_table; ` should not contain the inserted integer from the `insert `statement in **BETWNSTR** function 
Please let me know if there already exists a way to ignore the commit 
**Additional context**
Test package:
```
create or replace package test_betwnstr as
  --%suite(Between string function)
  
  --%test(Returns substring from start position to end position)
  procedure basic_usage;

  --%test(Returns substring when start position is zero)
  procedure zero_start_position;

end;
```
Test package body:
```
create or replace package body test_betwnstr as

  procedure basic_usage is
  begin
    ut.expect( betwnstr( '1234567', 2, 5 ) ).to_equal('2345');
  end;

  procedure zero_start_position is
  begin
    ut.expect( betwnstr( '1234567', 0, 5 ) ).to_equal('12345');
  end;

end;
```

**Comment by lwasylow** [comment]
Hi that is not possible.
Commit in design save a current state of data.
What you can do is to create after test to clean up a table.
