### ISSUE TITLE
Logging of DML statements executed to facilitate ease of rollback 

### ISSUE THREAD

**Issue by vasu5235** [utPLSQL/utPLSQL#910]
**Is your feature request related to a problem? Please describe.**
With reference to issue #905 which suggested that if the application code/function to be tested has `commit `statements, one should create an after test procedure to revert the DML statements executed. 

**Describe the solution you'd like**
Can we have a logging feature (annotation) that can recognise DML statements like INSERT, UPDATE and log it into a file (can be anything else) which would help to generate the reverse DML statements.

**Describe alternatives you've considered**
The only option that I see here, is to manually identify each & every DML statement and write the reverse script for it.

Please comment if there exists an alternative approach to achieve this.

**Comment by lwasylow** [comment]
I'm not sure that really possible. If I execute delete from table to remove all. There is no option to write reverse script of insert without first knowing content of data. If you need to revert changes done by test that are committed you should write reverse statement in procedure and execute them in annotation `--%aftertest` for example.

**Comment by vasu5235** [comment]
> I'm not sure that really possible. If I execute delete from table to remove all. There is no option to write reverse script of insert without first knowing content of data. If you need to revert changes done by test that are committed you should write reverse statement in procedure and execute them in annotation `--%aftertest` for example.

Agreed but at least if the statements are logged, it can act be used as a reference for generating reverse statement, like you said if a delete from table was executed, we would know that necessary insert scripts are needed. What do you think?

**Comment by lwasylow** [comment]
There are other tools in database to track dml changes and audit database. The utPLSQL is a framework to execute tests and is not aware the content of the package being tested not it cares. It just assess the expected value with value received. If you looking for logging tool the simplest not the best would be create a trigger to log dml changes on table or enable database audit.
Ask Tom got similar question (here) [https://asktom.oracle.com/pls/apex/asktom.search?tag=log-dml-ddl-and-dcl-user-activity] 
You can probably setup this in script in your dB before execution of tests.

**Comment by jgebal** [comment]
What is it that you are trying to achieve by testing?
Are you trying to use framework to discover what procedure is doing?

**Comment by ThisGuenter** [comment]
Maybe using logminer to create the undo sql is a possible solution

**Comment by PhilippSalvisberg** [comment]
I would not reinvent features that already exist. 

For example you can do the following, after enabling supplemental logging on database level, e.g. via `alter database add supplemental log data (all) columns;` and granting the user the `select any transaction` privilege:

```
create table t as select * from emp;
delete from t where empno in (7698, 7521);
commit;
select undo_sql
  from flashback_transaction_query
 where logon_user = USER 
   and operation = 'DELETE'
   and table_name = 'T'
   and undo_sql is not null;
```

The result of the last query looks similar to the following:

```
UNDO_SQL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
insert into "SCOTT"."T"("EMPNO","ENAME","JOB","MGR","HIREDATE","SAL","COMM","DEPTNO") values ('7521','WARD','SALESMAN','7698',TO_DATE('22.02.1981 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),'1250','500','30');
insert into "SCOTT"."T"("EMPNO","ENAME","JOB","MGR","HIREDATE","SAL","COMM","DEPTNO") values ('7698','BLAKE','MANAGER','7839',TO_DATE('01.05.1981 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),'2850',NULL,'30');
```

However, there are a lot of cases where it is not trivial to find the complete set of undo statements in the right order. And I wonder if something like that should become a part of the utPLSQL framework, even if it would be easy to implement (which is not the case, especially in a generic way dealing with all corner cases). 

Actually, I think the application test cases should handle the setup and teardown themselves. If transactions are really needed, then the effort is higher. This will automatically reduce automatically the amount of code with transactions. Especially when developing in test-driven mode.
