### ISSUE TITLE
EXCLUDE for columns doesn't work as expected

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#911]
When excluding columns, the column is still considered in data-type comparison.
Also, excluding column still impacts column order of expected and actual.

Example:
`
open l_expected for 
  select to_Char(null) id, 'ok' name from dual;
open l_actual for 
  select 'ok' name, to_number(null) id from dual;

ut.expect(l_actual).to_equal(l_expected).excude('ID');
`

The above example should work as column ID is exluded and so effective comparison should be on cursors:
`
open l_expected for 
  select 'ok' name from dual;
open l_actual for 
  select 'ok' name from dual;
`

**Comment by lwasylow** [comment]
The excluding or including should happen when we building a cursor details type. I will have a look when back.

**Comment by lwasylow** [comment]
I tracked issue to member function cursor details filter columns. It removes excluded columns but not update column position. When the column pop from stack column position has to shift down.
