### ISSUE TITLE
exclude / join_by on collections

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#912]
When using exclude / include / join_by with collections, we are forced to use syntax:
'object_type_name/attribute' for those features.

As far as I remember it used to work differently and you only needed to use attribute name.

**Comment by lwasylow** [comment]
But what would happen if we have an attribute of collection and then column with same name. The access by path for me seems natural and remove any ambiguity from names.

**Comment by jgebal** [comment]
Thisvis for anydata.convertCollection.
When comparing two collections directly

**Comment by lwasylow** [comment]
Ok so anydata collection compare? I think issue lies in how anytype get type resolve collection. I believe it return name of itself need to verify that

**Comment by lwasylow** [comment]
I can change it to use attribute base syntax.
Change would be that if compare type is anydata and custom type or collection then we will skip a first level of cursor details e.g. TEST_DUMMY_OBJECT and instead add the attributes as level 1.

The more challenging is the displaying the results.
This still uses old XML query type which read from xml generated so it contains the <TEST_DUMMY_OBJECT>. 
My suggestion would be the leave a display to contain datytype name.
