### ISSUE TITLE
ut_coverage_cobertura_reporter generates wrong line breaks

### ISSUE THREAD

**Issue by tkleiber** [utPLSQL/utPLSQL#917]
I have generated attached coburtura coverage.
There are several linebreaks eg. in line 39 which breaks the xml validation against http://cobertura.sourceforge.net/xml/coverage-04.dtd.

[ut_coverage_cobertura_reporter.zip](https://github.com/utPLSQL/utPLSQL-cli/files/3162141/ut_coverage_cobertura_reporter.zip)

![cobertura](https://user-images.githubusercontent.com/2185441/57453731-67c9ff00-7267-11e9-90c6-82394af74313.png)

Version:
OS: SLES 11.4
utPLSQL-cli 3.1.6.local
utPLSQL-java-api 3.1.6.411
Java-Version: 1.8.0_66
ORACLE_HOME: null
NLS_LANG: null

**Comment by jgebal** [comment]
The issue was confirmed, tested and will be fixed by upcoming Pull Request
