### ISSUE TITLE
Does ut.expect() return anything? Is it possible to get success failure for each ut.expect call?

### ISSUE THREAD

**Issue by vasu5235** [utPLSQL/utPLSQL#929]
**Is your feature request related to a problem? Please describe.**
For ease of running tests, I plan to create a table and dynamically generate ```ut.expect``` queries using table data.

**Describe the solution you'd like**
The table structure can have columns: 
1. TestId
2. Function call string; e.g: betwnstr('utPLSQL', 1, 2)
3. Matcher name
4. Return value
5. Result 

Approach is to load data from above table in a cursor and dynamically form the ```ut.expect(function_call_string).to_matcher_name(return_value)``` query and run it from a test procedure.

Is it possible to get the success/failure status of each ```ut.expect()``` call so that the result can be stored in Result column or if you can point me to which table does utPLSQL use to store the outputs.

**Comment by lwasylow** [comment]
Expect was designed to work within a framework with a correct annotations and put into packages. What is you trying to achieve? Can't see that making running tests easier. If you want to run all tests why not select * from table(ut. Run()).

**Comment by vasu5235** [comment]
> Expect was designed to work within a framework with a correct annotations and put into packages. What is you trying to achieve? Can't see that making running tests easier. If you want to run all tests why not select * from table(ut. Run()).

Does this work? ut.Run(ut.expect(betwnstr('testString',2,4))

**Comment by lwasylow** [comment]
It will not work.
Framework is to run tests expectations are part of framework. As per documentation a functional test must have a annotations and a expectation. Results of tests are build up and consumed by reporters.

**Comment by vasu5235** [comment]
Thank you so much for your prompt replies. Last query, can you point me to how/where in the source code the results of tests are build up? 

It will help me to understand how ut.expect() works and if I can contribute with my idea.

**Comment by vasu5235** [comment]
> Expect was designed to work within a framework with a correct annotations and put into packages. What is you trying to achieve? Can't see that making running tests easier. If you want to run all tests why not select * from table(ut. Run())
> I think there were some talks about separate matchers etc. but currently this is not supported.

Also, can you please elaborate on what you meant by running select * from table(ut.Run())

**Comment by lwasylow** [comment]
http://utplsql.org/utPLSQL/latest/userguide/running-unit-tests.html

Is got all information about ut.run.
