### ISSUE TITLE
Query: Something similar to utPLSQL.addtest from v2.3 does not exist in v3+ right?

### ISSUE THREAD

**Issue by vasu5235** [utPLSQL/utPLSQL#930]
The ```utPLSQL.addtest``` (ref: [http://utplsql.org/utPLSQL/v2.3.1/utplsql.html](http://utplsql.org/utPLSQL/v2.3.1/utplsql.html)),  way of registering a test programtically was depreceated in favour of using``` %test``` annotation.

Please correct me if I am wrong here. And if there are any other ways to register a test in v3+

So far I think the only way is using ```%test``` annotation.

PS: You are an amazing community and prompt support! Thank you all!

**Comment by lwasylow** [comment]
Hi Vasu
No unfortunately there is no other way for the user to add tests. Maybe it helps looking at some test generator which you could leverage and enhance. I have started https://github.com/lwasylow/utPlssqlTestGen and Philip got also included his version in sqldev utPLSQL plugin. Hope that helps

**Comment by pesse** [comment]
Hey @vasu5235 ,

thank you very much for appreciating the folks behind utPLSQL, it's literally our motivational fuel :)
I am very interested in your use-case - it seems like you have a certain idea how the framework should work, probably to solve an actual problem you have.
While the framework doesn't support what you asked for, I wonder if we can find a way to solve your problem in a different way if you share more details of what you'd like to achieve.

Feel free to provide more information here, join our slack channel or poke me via Twitter or E-Mail.

**Comment by vasu5235** [comment]
Thanks Lukasz. Appreciate the help. Will work on the provided link.
