### ISSUE TITLE
Question: How to read the XML report in SONAR? 

### ISSUE THREAD

**Issue by vasu5235** [utPLSQL/utPLSQL#941]
Can you please guide me by mentioning how to enable SONAR to read XML reports from `ut_sonar_test_reporter` through 

Issue #566 suggests sonar-generic-coverage, a similar question was posted in #623 but closed without comments. 

Does sonar-generic-coverage support the generated xUnit XML ?
Will the sonar-project.properties file from this url work?

[https://github.com/utPLSQL/utPLSQL/blob/develop/sonar-project.properties](https://github.com/utPLSQL/utPLSQL/blob/develop/sonar-project.properties)

**Comment by felipebz** [comment]
Hi @vasu5235.

You can use the `ut_sonar_test_reporter` to generate a XML in the ["Generic Test Data" format](https://docs.sonarqube.org/latest/analysis/generic-test/) for SonarQube, then you can output the result to a file then pass its path to the `sonar.testExecutionReportPaths` property.

**Comment by jgebal** [comment]
You can have a look at our utPLSQD-demo-project to see an example of integration.
You need to run sinar-scanner on your project after test execution (with priject based coverage). There is a section in documentation describing how to map packages into project files.

**Comment by vasu5235** [comment]
Thank you all. Appreciate the detailed response.
