### ISSUE TITLE
Compilation error in ut_compound_data_helper

### ISSUE THREAD

**Issue by felipebz** [utPLSQL/utPLSQL#947]
Hi!

I just tried to install the new utPLSQL v3.1.7 on Oracle Database 11.2.0.4.0 and I noticed the package `ut_compound_data_helper` wasn't compile correctly.

The compilation error occurs on the code below:

https://github.com/utPLSQL/utPLSQL/blob/e40966493a52979715697914f94dee1c9edf8e85/source/expectations/data_values/ut_compound_data_helper.pkb#L727-L736

```
Errors for PACKAGE BODY TESTES.UT_COMPOUND_DATA_HELPER:

LINE/COL ERROR
-------- -----------------------------------------------------------------
730/5    PL/SQL: SQL Statement ignored
732/10   PL/SQL: ORA-22905: cannot access rows from a non-nested table item
732/16   PLS-00642: local collection types not allowed in SQL statements
--------------------------------------------------------------
```

This usage of `TABLE(local collection)` is supported only on Oracle 12c and newer.

**Comment by lwasylow** [comment]
Hmm, that's weird it passed our build on 11g. We will look into why in first pla9it slipped through. Thanks for reporting that.

**Comment by jgebal** [comment]
Thanks @felipebz for reporting the issue. It's really odd it didn't fail on our 11.2 XE build.
We will look into fixing it.

**Comment by lwasylow** [comment]
Hi @felipebz , in meantime can you checkout a branch : [fix/json_11_2_comp]( https://github.com/utPLSQL/utPLSQL/tree/fix/json_11_2_comp) that should address a problem.

**Comment by lwasylow** [comment]
Hi @felipebz does your database uses native or interpreted compilation?

**Comment by felipebz** [comment]
> Hi @felipebz , in meantime can you checkout a branch : [fix/json_11_2_comp](https://github.com/utPLSQL/utPLSQL/tree/fix/json_11_2_comp) that should address a problem.

Yes, it fixes the issue. :+1: 

> Hi @felipebz does your database uses native or interpreted compilation?

PLSQL_CODE_TYPE is defined as interpreted. But I tried to forcing native compilation (adding a `alter session set plsql_code_type = 'native';` to install.sql from the official v3.1.7 release) and it doesn't help, I see the same error. I don't have any ideia why this works fine in the CI.

**Comment by felipebz** [comment]
By the way, I've just tried to install 3.1.7 on Oracle XE 11g and it compiles without any errors. Querying the `all_plsql_object_settings` view in this XE (11.2.0.2) and my real DB (11.2.0.4) shows the same settings. That's very weird.
