### ISSUE TITLE
Automate Deployment by Tagging Release

### ISSUE THREAD

**Issue by rlove** [utPLSQL/utPLSQL#95]
Create a new `deployed_readme.md`
-  Light on Markdown features so that easily read with text editor
- Brief introduction to product
-  Describes the directories and where to go in the documentation for getting started and installation.
- links back to the project

Create a new `release_notes.md`
- Will only contain notable changes since prior release.
- Will be used as the text for the github release notes.
- This will not be a complete release note history we have [GitHub Releases](https://github.com/utPLSQL/utPLSQL/releases) for that.

Create a script `.travis\create_deploy_zip.sh` that will generate ZIP file named `$TRAVIS_TAG.zip` with the following structure:
-   root directory contains:
  - `readme.md` which is really  `deployed_readme.md` renamed
  - `LICENSE`  from repo root
  - `authors.md` from repo root
  - `CONTRIBUTING.md` from repo root
  - `release_notes.md` from repo root
  - NOTE: Existing `readme.md` will not be deployed.
-  `examples/`  contains existing repo `examples` directory 
-  `docs/markdown/` contains markdown version of documentation in repo `docs` directory
-  `docs/html/` contains the html version of the documentation which is in the repo's `root/site/` directory after build_docs.sh is called
-  `source/` contains current repo `source` directory
- Create script `.travis\deploy_release.sh`
  - Setup to only execute on a tagged build.
  - Calls script `.travis\create_deploy_zip.sh` 
  - Creates GitHub Release using:
    - ZIP File created
    - `release_notes.md` will be used for description.
    - Release name will match TAG Name

**Comment by jgebal** [comment]
@rlove I was thinking.. about making the code in a way that each file contain info about the version.
That could be in a dual mode:
- Comment pointing to the version and source of the file (UTPLSQL project). The comment could also contain brief license info with link to full license.
- A function returning project version number for each component

What I did in any_data project was a bit hacky but I don't know any good way to do this using pure SQL scripting. Have a look [here](https://github.com/jgebal/any_data/blob/master/VERSION.sql) for version specification file and [here](https://github.com/jgebal/any_data/blob/master/sources/converter/any_data_builder.pkb#L32-L35) for implementation of component with embedded version.

What would be great is to have a process, that would scan through all the source files and replace the version tag in them with a version number. And with each build in develop (version3) branch we could bump development version by build number. So we would have v.3.0.0.170-alpha at this time.

**Comment by rlove** [comment]
@jgebal I think that would be a great feature.   I am going to keep it simple at first just to get it done, then we can add things like that.

**Comment by rlove** [comment]
Greatly simplified the release archive.     This has been completed.    New issues should be opened to handle additions.   This was resolved in PR #166
