### ISSUE TITLE
be_true matcher doesn't set expected value

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#97]
The be_true matcher doesn't set expected value. Should check other matches for that.

**Comment by jgebal** [comment]
Hi @Pazus 
This is by desing.
The matchers: `be_true`, `be_false`, `be_null`, `be_like`, `match` do not set the `expected`.
The reason behind that is the fact that they do not accept input `expected`
Matchers `be_true`, `be_false`, `be_null` are testing state of a variable.
Reporting on those matchers would be more confusing as we would be saying:
```
expected: FALSE(BOOLEAN) 
to be_true: TRUE(BOOLEAN)
```
With the current implementation we're simply saying:
```
expected: FALSE(BOOLEAN) 
to be_true
```

For the be_like and be_matching we're using the `additional_info` field to represent the parameters passed to the matcher.

**Comment by Pazus** [comment]
Than please take a look at my #99 PR, maybe I've implemented expected/actual value reporting wrong way.
