### ISSUE TITLE
Creating test packages before actually running the test cases

### ISSUE THREAD

**Issue by rhadbe** [utPLSQL/utPLSQL#973]
I created a test package in notepad but it's not on the test schema or database schema. However, it's present in git repository or working directory am using to specify source packages and test packages. 

Is there a way to create the test package (or suite) in schema before actually starting running test cases? 
To what i understood, we have goal "test" to trigger the execution of test suites and test cases written within a test suite. Do we have any other goal or a method which will create the test packages first and then we can use "test" goal to actually trigger the test cases execution.?

**Comment by lwasylow** [comment]
Hi @rhadbe 
I'm not entirly undestand a problem / question.
The creation of the objects in the database is out of scope of utPLSQL which is a testing framework.
There are solutions for database migration like  Flyway etc that can auto deploy your objects e.g. tests packages.

Is that what you meant ?

**Comment by rhadbe** [comment]
> Hi @rhadbe
> I'm not entirly undestand a problem / question.
> The creation of the objects in the database is out of scope of utPLSQL which is a testing framework.
> There are solutions for database migration like Flyway etc that can auto deploy your objects e.g. tests packages.
> 
> Is that what you meant ?

yeah, i thought creation/compilation of test packages might be something which falls within the scope of testing framework and can be done via some maven goal.

**Comment by lwasylow** [comment]
Hi 
Im afraid not.
Database deployment is a separate functionality that is not part of utPLSQL.
Saying that I think you can easily write a scripts to deploy your packages as part of CI/CD job for example in Jenkins.

**Comment by rhadbe** [comment]
> Hi
> Im afraid not.
> Database deployment is a separate functionality that is not part of utPLSQL.
> Saying that I think you can easily write a scripts to deploy your packages as part of CI/CD job for example in Jenkins.

Yeah, i did same as you suggested. I just want to check, is there a functionality or a maven goal which is already present and I might be not aware of. 

Thanks a lot for your quick turnaround on my issue.
