### ISSUE TITLE
How to determine return value of ut.expect?

### ISSUE THREAD

**Issue by sggreener** [utPLSQL/utPLSQL#987]
Phillip,

I am a fan of this project. 

I mainly use the SQL Developer extension to generate a test file, then fill in that file with tests.

utPLSQL has really helped in improve the quality of my PLSQL package and object code.

Thanks for all your work.

Now this question is probably in the help, but I can't find it.

When ut.expect executes I wish to be able to detect whether if passed or failed.....

ut.expect(...).to_equal(...);

if ( failed ) then
  -- do something
else
  -- do something else
end if;

Can this be done? If so, how?

regards
Simon

**Comment by PhilippSalvisberg** [comment]
Thanks @sggreener for the appreciation. It's nice to hear such feedback from time to time.

I transferred this issue to the utPLSQL core repository. As @jgebal the question is related more to utPLSQL in general than to the SQL Developer extension.

**Comment by sggreener** [comment]
Thank you for taking the time to respond.

And, in particular, thanks for the links to articles to help me learn more.

My request was pretty minor and based on being a lack of understanding of unit testing.

I will have a read.

Thanks
Simon

**Comment by sggreener** [comment]
Phillip,

Yes I know what you mean about getting feedback or thanks. It seems to be the lot for some projects.

I don't know why I have continued to hope that we could finally get GeoRaptor back up and running. We haven't managed to do so since 4.0 came along. Finding you and your resources has been wonderful. But you might have to deal with me again come November as the students will finish their final year project and move on regardless as to whether it is finished or not!

I've written back to @jgebal. It was a relatively minor issue anyway.

Regards
Simon
⁣39 Cliff View Drive, Allens Rivulet, Tas 7150
(H) 0362396397
(M) 0418396391
www.spatialdbadvisor.com / www.spdba.com.au
