### ISSUE TITLE
Is it possible to show 'success'ful assertions in junit/xunit report like 'failures'

### ISSUE THREAD

**Issue by MS-24** [utPLSQL/utPLSQL#989]
I am looking for a solution on junit/xunit report xml.
For failed test cases in report we could see something like below. 
> 
![junit_errors](https://user-images.githubusercontent.com/39770054/64274380-e6f2e980-cf60-11e9-8aa5-77ccbde9eb26.png)
> 
I need something similar for the success scenario . This is needed to show report to stakeholders without showing the code which they least interested . All they are interested is , to check what assertions were used in the test case.

The below is the snippet for failures in junit xml report

```
\<failure\>
&quot;Something Wrong in process flow&quot;
Actual: 1 (number) was expected to equal: 0 (number) 
at &quot;tstUTPLSQL.TEST_SAMPLE_SUITE&quot;, line 243 ut.expect( test_sample_suite&apos;Something Wrong in process flow&apos;).to_equal(0);

\</failure\>
```

Similarly is it possible to provide something like below in junit report xml?

```
\<success\>
&quot;All right in process flow&quot;
Actual: 1 (number) was expected to equal: 1 (number) 
at &quot;tstUTPLSQL.TEST_SAMPLE_SUITE&quot;, line 243 ut.expect( test_sample_suite&apos;all right in process flow&apos;).to_equal(0);
\</success\>

```
Please suggest .
Thanks!!

**Comment by MS-24** [comment]
Hi @jgebal , @lwasylow

Could you please suggest , how assertion can be displayed in junit/xunit report when clicked on successful test case in Jenkins.

Thanks!!

**Comment by lwasylow** [comment]
Hi MS-24, Ive not been using Jenkins for a while as now on Azure. It depends on the Jenkins plugin itself. If the plugin has the ability to display the success then it's possible otherwise not. Maybe instead you can also produce a simple log reporter output and publish from Workspace as artifact. This has all tests listed but it's not displayed in Jenkins

**Comment by jgebal** [comment]
Hi @MS-24 

Successful assertions are not reported in any reporter, not only JUnit.

This is a common practice (not just utPLSQL), RSpec 
Is it that: 
- the business/stakeholders don't trust your tests
- the tests don't have descriptions (or have bad descriptions)
- single test is testing more than single scenario/use case

There is very low value in reporting expectations on successful test and the signal/noise ratio of your test results will grow rapidly with growing number of tests.

At the moment, the only way I see it done is by having a separate reporter or using DBMS_OUTPUT in your tests.

I would suggest starting by asking the question "WHY?" they want to see this?
Seems like they are more interested in HOW things were tested rather then WHAT was tested.

You might end up showing code anyway if they go into the HOW.

**Comment by MS-24** [comment]
> Hi MS-24, Ive not been using Jenkins for a while as now on Azure. It depends on the Jenkins plugin itself. If the plugin has the ability to display the success then it's possible otherwise not. Maybe instead you can also produce a simple log reporter output and publish from Workspace as artifact. This has all tests listed but it's not displayed in Jenkins

Hi @lwasylow 
Thanks for the reply. I am talking w.r.t  xml that gets generated here.

I am using the below code to generate xml report.


```
utplsql run $myDB -p=testutplsql \
-f=ut_xunit_reporter -o=$WORKSPACE/xunit_test_results.xml
```

The above code generates 'xunit_test_results.xml' which would be picked by Jenkins plugin to show the report.
In the xunit_test_results.xml I would able to see a tag  "failure" from which Jenkins plugin understanding that it is a failure and showing the format as  in my first comment.

But for the successful test cases there is no tag like "success" , then Jenkins plugin would pick and show that in the report when clicked on a specific test case.
Hope I am clear in stating my requirement .

**Comment by MS-24** [comment]
> Hi @MS-24
> Successful assertions are not reported in any reporter, not only JUnit.
> This is a common practice (not just utPLSQL), RSpec
> Is it that:
> 
> the business/stakeholders don't trust your tests
> the tests don't have descriptions (or have bad descriptions)
> single test is testing more than single scenario/use case
> 
> There is very low value in reporting expectations on successful test and the signal/noise ratio of your test results will grow rapidly with growing number of tests.
> At the moment, the only way I see it done is by having a separate reporter or using DBMS_OUTPUT in your tests.
> I would suggest starting by asking the question "WHY?" they want to see this?
> Seems like they are more interested in HOW things were tested rather then WHAT was tested.
> You might end up showing code anyway if they go into the HOW.

Thanks @jgebal  - Taken the point. I have already provided my feedback on complications here. But checking if at all it is feasible to provide as an optional feature. If they are adamant on this I would use your suggestion on another report or dbms_output message. 

Thanks!!

**Comment by PhilippSalvisberg** [comment]
>Is it possible to show 'success'ful assertions in junit/xunit report like 'failures'

The answer to this question is simple: **No, this is not possible** based on the current [Junit XML schema](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd#L64-L79). See also [this documentation](https://llg.cubic.org/docs/junit/) which provides explanations per tag.

The only option is to report some assert related text via `DBMS_OUTPUT`. This will be shown within `system-out` tags.
