### ISSUE TITLE
Installation on a schema with CREATE ANY CONTEXT fails for version 3.1.8

### ISSUE THREAD

**Issue by MickeVr** [utPLSQL/utPLSQL#992]
Recently we upgraded utPLSQL from version 3.1.7 to 3.1.8. Version 3.1.8 needs the CREATE CONTEXT privilege. Our DBA granted us this privilege with the CREATE ANY CONTEXT grant, but the installation fails with error:

ERROR at line 1:
16:33:47       [exec] ORA-20000: The following privileges are required for user "XXX" to install into schema "XXX"
16:33:47       [exec] -  CREATE CONTEXT Please read the installation documentation at http://utplsql.org/utPLSQL/
16:33:47       [exec] ORA-06512: at line 27

**Provide version info**
Version 3.1.8, on Oracle 12.1

**Expected behavior**
I expect that the installations cript runs without issues

**Additional context**
I found the issue in check_sys_grants.sql

**Comment by jgebal** [comment]
Micke,
Thanks for reporting this issue.
Even bigger thank you for fixing it!

Great first contribution 👍

**Comment by jgebal** [comment]
Closed by #993
