### ISSUE TITLE
Restricted columns in cursor compare

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#997]
**Describe the bug**
Due to the nature of cursor comparison implementation, when comparing cursor containing one of column names:
- ITEM_DATA
- DATA_ID
- ITEM_NO
- DUP_NO
- POSITION

The cursor comparison fails.

**Provide version info**
utPLSQL v3.1.8

**To Reproduce**
This can be observed on 3.1.8 with following block:
```sql
set serverout on
declare
  l_actual   sys_refcursor;
  l_expected sys_refcursor;
begin
  open l_actual   for select * from all_arguments where rownum = 1;
  open l_expected for select * from all_arguments where rownum = 1;
  ut.expect(l_actual).to_equal(l_expected);
end;
/
```

**Expected behavior**

utPLSQL should not prevent column names that are commonly used / possible to use.

One idea would be to use quoted and more unusual names for internal columns in cursor compare: `"UT3$_Item#Data"`

**Comment by apexbine** [comment]
Also bumped into the 'position bug'.
To make this issue easier to find, I'll just mention _ORA-00918: column ambiguously defined_.
